### ISSUE TITLE
Tabular predictor does not respect time limit

### ISSUE THREAD

**Issue by nilsplettenberg** [autogluon/autogluon#1402]
Training a model for a tabular dataset sometimes runs much longer than the given time limit. 
For the example given below, fitting takes roughly the 3600s: 
`AutoGluon training complete, total runtime = 3600.42s ...`
But after that, fitting of L1 models takes over 30 additional minutes, leading to a runtime of more than 150% of the time limit.

Here is the code (v.0.3.1):

```
predictor = TabularPredictor(
            label=target,
            problem_type="multiclass",
            path=model_path,
            eval_metric="balanced_accuracy",
        ).fit(
            train_data=data["train"][features_],
            time_limit=3600),
            presets=[
                "high_quality_fast_inference_only_refit",
                "optimize_for_deployment",
            ],
            excluded_model_types=["KNN"],
        )
```

Full logs:
```
Presets specified: ['high_quality_fast_inference_only_refit', 'optimize_for_deployment']
Beginning AutoGluon training ... Time limit = 3600s
AutoGluon will save models to "/tmp/tmpoms31z4m/"
AutoGluon Version:  0.3.1
Train Data Rows:    33614
Train Data Columns: 6
Preprocessing data ...
Train Data Class Count: 3
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
        Available Memory:                    8572.62 MB
        Train Data (Original)  Memory Usage: 1.61 MB (0.0% of available memory)
        Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
        Stage 1 Generators:
                Fitting AsTypeFeatureGenerator...
        Stage 2 Generators:
                Fitting FillNaFeatureGenerator...
        Stage 3 Generators:
                Fitting IdentityFeatureGenerator...
        Stage 4 Generators:
                Fitting DropUniqueFeatureGenerator...
        Types of features in original data (raw dtype, special dtypes):
                ('int', []) : 6 | ['white_piece0_strength', 'white_piece0_file', 'white_piece0_rank', 'black_piece0_strength', 'black_piece0_file', ...]
        Types of features in processed data (raw dtype, special dtypes):
                ('int', []) : 6 | ['white_piece0_strength', 'white_piece0_file', 'white_piece0_rank', 'black_piece0_strength', 'black_piece0_file', ...]
        0.1s = Fit runtime
        6 features in original data used to generate 6 features in processed data.
        Train Data (Processed) Memory Usage: 1.61 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.1s ...
AutoGluon will gauge predictive performance using evaluation metric: 'balanced_accuracy'
        To change this, specify the eval_metric argument of fit()
AutoGluon will fit 2 stack levels (L1 to L2) ...
Excluded Model Types: ['KNN']
        Found 'KNN' model in hyperparameters, but 'KNN' is present in `excluded_model_types` and will be removed.
        Found 'KNN' model in hyperparameters, but 'KNN' is present in `excluded_model_types` and will be removed.
Fitting 11 L1 models ...
Fitting model: NeuralNetFastAI_BAG_L1 ... Training model for up to 2399.33s of the 3599.9s of remaining time.
generated new fontManager
Metric balanced_accuracy is not supported by this model - using log_loss instead
Metric balanced_accuracy is not supported by this model - using log_loss instead
Metric balanced_accuracy is not supported by this model - using log_loss instead
Metric balanced_accuracy is not supported by this model - using log_loss instead
Metric balanced_accuracy is not supported by this model - using log_loss instead
Metric balanced_accuracy is not supported by this model - using log_loss instead
Metric balanced_accuracy is not supported by this model - using log_loss instead
Metric balanced_accuracy is not supported by this model - using log_loss instead
Metric balanced_accuracy is not supported by this model - using log_loss instead
Metric balanced_accuracy is not supported by this model - using log_loss instead
        0.8325   = Validation score   (balanced_accuracy)
        1008.86s         = Training   runtime
        1.25s    = Validation runtime
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 1389.16s of the 2589.72s of remaining time.
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
        0.7362   = Validation score   (balanced_accuracy)
        135.84s  = Training   runtime
        1.07s    = Validation runtime
Fitting model: LightGBM_BAG_L1 ... Training model for up to 1252.17s of the 2452.73s of remaining time.
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
        0.8182   = Validation score   (balanced_accuracy)
        143.75s  = Training   runtime
        0.92s    = Validation runtime
Fitting model: RandomForestGini_BAG_L1 ... Training model for up to 1107.42s of the 2307.98s of remaining time.
        0.715    = Validation score   (balanced_accuracy)
        4.0s     = Training   runtime
        1.66s    = Validation runtime
Fitting model: RandomForestEntr_BAG_L1 ... Training model for up to 1101.51s of the 2302.08s of remaining time.
        0.7132   = Validation score   (balanced_accuracy)
        4.37s    = Training   runtime
        1.79s    = Validation runtime
Fitting model: CatBoost_BAG_L1 ... Training model for up to 1095.08s of the 2295.65s of remaining time.
        0.77     = Validation score   (balanced_accuracy)
        144.94s  = Training   runtime
        0.15s    = Validation runtime
Fitting model: ExtraTreesGini_BAG_L1 ... Training model for up to 949.91s of the 2150.48s of remaining time.
        0.7143   = Validation score   (balanced_accuracy)
        3.57s    = Training   runtime
        1.69s    = Validation runtime
Fitting model: ExtraTreesEntr_BAG_L1 ... Training model for up to 944.39s of the 2144.96s of remaining time.
        0.7112   = Validation score   (balanced_accuracy)
        3.67s    = Training   runtime
        1.71s    = Validation runtime
Fitting model: XGBoost_BAG_L1 ... Training model for up to 938.76s of the 2139.32s of remaining time.
        0.8038   = Validation score   (balanced_accuracy)
        907.85s  = Training   runtime
        0.34s    = Validation runtime
Fitting model: NeuralNetMXNet_BAG_L1 ... Training model for up to 30.5s of the 1231.06s of remaining time.
        Warning: Exception caused NeuralNetMXNet_BAG_L1 to fail during training... Skipping this model.
                libopenblas.so.0: cannot open shared object file: No such file or directory
Detailed Traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/autogluon/tabular/trainer/abstract_trainer.py", line 962, in _train_and_save
    model = self._train_single(X, y, model, X_val, y_val, **model_fit_kwargs)
  File "/usr/local/lib/python3.7/site-packages/autogluon/tabular/trainer/abstract_trainer.py", line 934, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, **model_fit_kwargs)
  File "/usr/local/lib/python3.7/site-packages/autogluon/core/models/abstract/abstract_model.py", line 522, in fit
    out = self._fit(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py", line 153, in _fit
    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 189, in _fit
    n_repeats=n_repeats, n_repeat_start=n_repeat_start, save_folds=save_bag_folds, groups=groups, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 388, in _fit_folds
    fold_fitting_strategy.after_all_folds_scheduled()
  File "/usr/local/lib/python3.7/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 59, in after_all_folds_scheduled
    self._fit_fold_model(*job)
  File "/usr/local/lib/python3.7/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 64, in _fit_fold_model
    fold_model = self._fit(model_base, time_start_fold, time_limit_fold, fold_ctx, kwargs)
  File "/usr/local/lib/python3.7/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 111, in _fit
    fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, **kwargs_fold)
  File "/usr/local/lib/python3.7/site-packages/autogluon/core/models/abstract/abstract_model.py", line 522, in fit
    out = self._fit(**kwargs)
  File "/usr/local/lib/python3.7/site-packages/autogluon/tabular/models/tabular_nn/tabular_nn_model.py", line 168, in _fit
    try_import_mxnet()
  File "/usr/local/lib/python3.7/site-packages/autogluon/core/utils/try_import.py", line 31, in try_import_mxnet
    import mxnet as mx
  File "/usr/local/lib/python3.7/site-packages/mxnet/__init__.py", line 23, in <module>
    from .context import Context, current_context, cpu, gpu, cpu_pinned
  File "/usr/local/lib/python3.7/site-packages/mxnet/context.py", line 23, in <module>
    from .base import classproperty, with_metaclass, _MXClassPropertyMetaClass
  File "/usr/local/lib/python3.7/site-packages/mxnet/base.py", line 351, in <module>
    _LIB = _load_lib()
  File "/usr/local/lib/python3.7/site-packages/mxnet/base.py", line 342, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/usr/local/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libopenblas.so.0: cannot open shared object file: No such file or directory
Fitting model: LightGBMLarge_BAG_L1 ... Training model for up to 30.45s of the 1231.02s of remaining time.
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
        Ran out of time, early stopping on iteration 1. Best iteration is:
        [1]     train_set's multi_logloss: 0.908581     train_set's balanced_accuracy: 0.333333 valid_set's multi_logloss: 0.908982     valid_set's balanced_accuracy: 0.333333
        Time limit exceeded... Skipping LightGBMLarge_BAG_L1.
Completed 1/20 k-fold bagging repeats ...
Fitting model: WeightedEnsemble_L2 ... Training model for up to 360.0s of the 1225.96s of remaining time.
        0.8338   = Validation score   (balanced_accuracy)
        10.5s    = Training   runtime
        0.01s    = Validation runtime
Excluded Model Types: ['KNN']
        Found 'KNN' model in hyperparameters, but 'KNN' is present in `excluded_model_types` and will be removed.
        Found 'KNN' model in hyperparameters, but 'KNN' is present in `excluded_model_types` and will be removed.
Fitting 11 L2 models ...
Fitting model: NeuralNetFastAI_BAG_L2 ... Training model for up to 1215.43s of the 1215.4s of remaining time.
Metric balanced_accuracy is not supported by this model - using log_loss instead
        Ran out of time, stopping training early. (Stopping on epoch 1)
Metric balanced_accuracy is not supported by this model - using log_loss instead
        Ran out of time, stopping training early. (Stopping on epoch 2)
Metric balanced_accuracy is not supported by this model - using log_loss instead
        Ran out of time, stopping training early. (Stopping on epoch 2)
Metric balanced_accuracy is not supported by this model - using log_loss instead
        Ran out of time, stopping training early. (Stopping on epoch 2)
Metric balanced_accuracy is not supported by this model - using log_loss instead
        Ran out of time, stopping training early. (Stopping on epoch 2)
Metric balanced_accuracy is not supported by this model - using log_loss instead
        Ran out of time, stopping training early. (Stopping on epoch 2)
Metric balanced_accuracy is not supported by this model - using log_loss instead
        Ran out of time, stopping training early. (Stopping on epoch 3)
Metric balanced_accuracy is not supported by this model - using log_loss instead
        Ran out of time, stopping training early. (Stopping on epoch 3)
Metric balanced_accuracy is not supported by this model - using log_loss instead
        Ran out of time, stopping training early. (Stopping on epoch 4)
Metric balanced_accuracy is not supported by this model - using log_loss instead
        Ran out of time, stopping training early. (Stopping on epoch 5)
        0.9305   = Validation score   (balanced_accuracy)
        1155.6s  = Training   runtime
        6.72s    = Validation runtime
Fitting model: LightGBMXT_BAG_L2 ... Training model for up to 53.01s of the 52.98s of remaining time.
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
        Ran out of time, early stopping on iteration 3. Best iteration is:
        [3]     train_set's multi_logloss: 0.747221     train_set's balanced_accuracy: 0.595142 valid_set's multi_logloss: 0.744995     valid_set's balanced_accuracy: 0.595184
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
        Ran out of time, early stopping on iteration 3. Best iteration is:
        [3]     train_set's multi_logloss: 0.749193     train_set's balanced_accuracy: 0.595804 valid_set's multi_logloss: 0.752152     valid_set's balanced_accuracy: 0.597072
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
        Ran out of time, early stopping on iteration 2. Best iteration is:
        [2]     train_set's multi_logloss: 0.800251     train_set's balanced_accuracy: 0.493369 valid_set's multi_logloss: 0.799265     valid_set's balanced_accuracy: 0.5
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
        Ran out of time, early stopping on iteration 2. Best iteration is:
        [2]     train_set's multi_logloss: 0.799845     train_set's balanced_accuracy: 0.532195 valid_set's multi_logloss: 0.800703     valid_set's balanced_accuracy: 0.539432
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
        Ran out of time, early stopping on iteration 4. Best iteration is:
        [4]     train_set's multi_logloss: 0.702614     train_set's balanced_accuracy: 0.612254 valid_set's multi_logloss: 0.704426     valid_set's balanced_accuracy: 0.613473
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
        Ran out of time, early stopping on iteration 2. Best iteration is:
        [2]     train_set's multi_logloss: 0.803377     train_set's balanced_accuracy: 0.539092 valid_set's multi_logloss: 0.80468      valid_set's balanced_accuracy: 0.538565
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
        Ran out of time, early stopping on iteration 3. Best iteration is:
        [3]     train_set's multi_logloss: 0.751318     train_set's balanced_accuracy: 0.587514 valid_set's multi_logloss: 0.752479     valid_set's balanced_accuracy: 0.579174
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
        Ran out of time, early stopping on iteration 3. Best iteration is:
        [3]     train_set's multi_logloss: 0.749762     train_set's balanced_accuracy: 0.594679 valid_set's multi_logloss: 0.750252     valid_set's balanced_accuracy: 0.598176
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
        Ran out of time, early stopping on iteration 3. Best iteration is:
        [3]     train_set's multi_logloss: 0.746821     train_set's balanced_accuracy: 0.596367 valid_set's multi_logloss: 0.749928     valid_set's balanced_accuracy: 0.593648
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
        Ran out of time, early stopping on iteration 2. Best iteration is:
        [2]     train_set's multi_logloss: 0.802773     train_set's balanced_accuracy: 0.50689  valid_set's multi_logloss: 0.801471     valid_set's balanced_accuracy: 0.512494
        Time limit exceeded... Skipping LightGBMXT_BAG_L2.
Completed 1/20 k-fold bagging repeats ...
Fitting model: WeightedEnsemble_L3 ... Training model for up to 360.0s of the -0.38s of remaining time.
        0.9305   = Validation score   (balanced_accuracy)
        0.01s    = Training   runtime
        0.01s    = Validation runtime
AutoGluon training complete, total runtime = 3600.42s ...
Fitting 1 L1 models ...
Fitting model: NeuralNetFastAI_BAG_L1_FULL ...
Metric balanced_accuracy is not supported by this model - using log_loss instead
        Stopping at the best epoch learned earlier - 27.
        873.91s  = Training   runtime
Fitting 1 L1 models ...
Fitting model: LightGBMXT_BAG_L1_FULL ...
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
        582.88s  = Training   runtime
Fitting 1 L1 models ...
Fitting model: LightGBM_BAG_L1_FULL ...
/usr/local/lib/python3.7/site-packages/lightgbm/engine.py:239: UserWarning: 'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. Pass 'log_evaluation()' callback via 'callbacks' argument instead.
  _log_warning("'verbose_eval' argument is deprecated and will be removed in a future release of LightGBM. "
        593.76s  = Training   runtime
Fitting 1 L1 models ...
Fitting model: RandomForestGini_BAG_L1_FULL ...
        0.715    = Validation score   (balanced_accuracy)
        3.79s    = Training   runtime
        1.89s    = Validation runtime
Fitting 1 L1 models ...
Fitting model: RandomForestEntr_BAG_L1_FULL ...
        0.7132   = Validation score   (balanced_accuracy)
        3.83s    = Training   runtime
        1.63s    = Validation runtime
Fitting 1 L1 models ...
Fitting model: CatBoost_BAG_L1_FULL ...
        11.35s   = Training   runtime
Fitting 1 L1 models ...
Fitting model: ExtraTreesGini_BAG_L1_FULL ...
        0.7143   = Validation score   (balanced_accuracy)
        3.2s     = Training   runtime
        1.94s    = Validation runtime
Fitting 1 L1 models ...
Fitting model: ExtraTreesEntr_BAG_L1_FULL ...
        0.7112   = Validation score   (balanced_accuracy)
        3.7s     = Training   runtime
        2.15s    = Validation runtime
Fitting 1 L1 models ...
Fitting model: XGBoost_BAG_L1_FULL ...
        83.93s   = Training   runtime
Fitting 1 L2 models ...
Fitting model: NeuralNetFastAI_BAG_L2_FULL ...
Metric balanced_accuracy is not supported by this model - using log_loss instead
        Stopping at the best epoch learned earlier - 2.
        95.29s   = Training   runtime
Deleting model NeuralNetFastAI_BAG_L1. All files under /tmp/tmpoms31z4m/models/NeuralNetFastAI_BAG_L1/ will be removed.
Deleting model LightGBMXT_BAG_L1. All files under /tmp/tmpoms31z4m/models/LightGBMXT_BAG_L1/ will be removed.
Deleting model LightGBM_BAG_L1. All files under /tmp/tmpoms31z4m/models/LightGBM_BAG_L1/ will be removed.
Deleting model RandomForestGini_BAG_L1. All files under /tmp/tmpoms31z4m/models/RandomForestGini_BAG_L1/ will be removed.
Deleting model RandomForestEntr_BAG_L1. All files under /tmp/tmpoms31z4m/models/RandomForestEntr_BAG_L1/ will be removed.
Deleting model CatBoost_BAG_L1. All files under /tmp/tmpoms31z4m/models/CatBoost_BAG_L1/ will be removed.
Deleting model ExtraTreesGini_BAG_L1. All files under /tmp/tmpoms31z4m/models/ExtraTreesGini_BAG_L1/ will be removed.
Deleting model ExtraTreesEntr_BAG_L1. All files under /tmp/tmpoms31z4m/models/ExtraTreesEntr_BAG_L1/ will be removed.
Deleting model XGBoost_BAG_L1. All files under /tmp/tmpoms31z4m/models/XGBoost_BAG_L1/ will be removed.
Deleting model WeightedEnsemble_L2. All files under /tmp/tmpoms31z4m/models/WeightedEnsemble_L2/ will be removed.
Deleting model NeuralNetFastAI_BAG_L2. All files under /tmp/tmpoms31z4m/models/NeuralNetFastAI_BAG_L2/ will be removed.
Deleting model WeightedEnsemble_L3. All files under /tmp/tmpoms31z4m/models/WeightedEnsemble_L3/ will be removed.
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("/tmp/tmpoms31z4m/")
```

**Comment by Innixma** [comment]
Thanks for the logs!

Currently, refit presets do not respect time limit strictly, as the model refit logic occurs after the original training (which does respect time limit). Normally the refit logic only takes ~10% or less of the original time limit, however in your case for some reason the FastAI neural network refit model took a very long time to train compared to what was expected (expectation was ~100 seconds). If you prefer to strictly respect time limit, don't use refit_full presets or send AG some smaller portion of the actual hard time limit to give lee-way to the refit time overhead.

We will consider improving the time limit adherence in refit models for future releases.

**Comment by Innixma** [comment]
In general this hasn't been a major issue for users, and is complex to address, so I'm resolving for now.
