### ISSUE TITLE
 ValueError: signal only works in main thread

### ISSUE THREAD

**Issue by DevadharshiniKalaivanan** [autogluon/autogluon#1539]
I am trying to intergrate Autogluon object detection HPO with flask I'm facing these issues while trying to pass the datasets 

``` 
No GPU detected/allowed, using most conservative search space.
Randomly split train_data into train[35]/validation[1] splits.
Starting HPO experiments
  0%|          | 0/2 [00:00<?, ?it/s]modified configs(<old> != <new>): {
root.dataset         voc_tiny != auto
root.dataset_root    ~/.mxnet/datasets/ != auto
root.train.early_stop_baseline 0.0 != -inf
root.train.early_stop_patience -1 != 10
root.train.seed      233 != 241
root.train.epochs    20 != 1
root.train.early_stop_max_value 1.0 != inf
root.gpus            (0, 1, 2, 3) != ()
root.ssd.base_network vgg16_atrous != mobilenet1.0
root.ssd.data_shape  300 != 512
root.ssd.transfer    ssd_512_resnet50_v1_coco != ssd_512_mobilenet1.0_coco
}
Saved config to /home/devadharshini/Downloads/od/224a0ca1/.trial_0/config.yaml
Using transfer learning from ssd_512_mobilenet1.0_coco, the other network parameters are ignored.
 50%|█████     | 1/2 [00:01<00:01,  1.70s/it]modified configs(<old> != <new>): {
root.dataset         voc_tiny != auto
root.yolo3.base_network darknet53 != mobilenet1.0
root.yolo3.transfer  yolo3_darknet53_coco != yolo3_mobilenet1.0_coco
root.dataset_root    ~/.mxnet/datasets/ != auto
root.train.seed      233 != 241
root.train.early_stop_baseline 0.0 != -inf
root.train.epochs    20 != 1
root.train.early_stop_patience -1 != 10
root.train.early_stop_max_value 1.0 != inf
root.gpus            (0, 1, 2, 3) != ()
}
Saved config to /home/devadharshini/Downloads/od/224a0ca1/.trial_1/config.yaml
Using transfer learning from yolo3_mobilenet1.0_coco, the other network parameters are ignored.
100%|██████████| 2/2 [00:07<00:00,  3.77s/it]
modified configs(<old> != <new>): {
root.dataset         voc_tiny != auto
root.dataset_root    ~/.mxnet/datasets/ != auto
root.train.early_stop_baseline 0.0 != -inf
root.train.early_stop_patience -1 != 10
root.train.seed      233 != 241
root.train.epochs    20 != 1
root.train.early_stop_max_value 1.0 != inf
root.gpus            (0, 1, 2, 3) != ()
root.ssd.base_network vgg16_atrous != mobilenet1.0
root.ssd.data_shape  300 != 512
root.ssd.transfer    ssd_512_resnet50_v1_coco != ssd_512_mobilenet1.0_coco
}
Saved config to /home/devadharshini/Downloads/od/224a0ca1/.trial_0/config.yaml
Using transfer learning from ssd_512_mobilenet1.0_coco, the other network parameters are ignored.
Finished, total runtime is 10.05 s
{ 'best_config': { 'dataset': 'auto',
                   'dataset_root': 'auto',
                   'estimator': <class 'gluoncv.auto.estimators.ssd.ssd.SSDEstimator'>,
                   'gpus': [],
                   'horovod': False,
                   'num_workers': 4,
                   'resume': '',
                   'save_interval': 1,
                   'ssd': { 'amp': False,
                            'base_network': 'mobilenet1.0',
                            'data_shape': 512,
                            'filters': None,
                            'nms_thresh': 0.45,
                            'nms_topk': 400,
                            'ratios': ( [1, 2, 0.5],
                                        [1, 2, 0.5, 3, 0.3333333333333333],
                                        [1, 2, 0.5, 3, 0.3333333333333333],
                                        [1, 2, 0.5, 3, 0.3333333333333333],
                                        [1, 2, 0.5],
                                        [1, 2, 0.5]),
                            'sizes': (30, 60, 111, 162, 213, 264, 315),
                            'steps': (8, 16, 32, 64, 100, 300),
                            'syncbn': False,
                            'transfer': 'ssd_512_mobilenet1.0_coco'},
                   'train': { 'batch_size': 16,
                              'dali': False,
                              'early_stop_baseline': -inf,
                              'early_stop_max_value': inf,
                              'early_stop_min_delta': 0.001,
                              'early_stop_patience': 10,
                              'epochs': 1,
                              'log_interval': 100,
                              'lr': 0.001,
                              'lr_decay': 0.1,
                              'lr_decay_epoch': (160, 200),
                              'momentum': 0.9,
                              'seed': 241,
                              'start_epoch': 0,
                              'wd': 0.0005},
                   'valid': { 'batch_size': 16,
                              'iou_thresh': 0.5,
                              'metric': 'voc07',
                              'val_interval': 1}},
  'total_time': 10.048343420028687,
  'train_map': -1,
  'valid_map': -1}
Exception on /detection [POST]
Traceback (most recent call last):
  File "/home/devadharshini/Downloads/od/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/devadharshini/Downloads/od/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/devadharshini/Downloads/od/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/devadharshini/Downloads/od/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/devadharshini/Downloads/od/main.py", line 94, in detection_upload
    detector.fit(dataset_train, time_limit=time_limit, hyperparameters=hyperparameters,
  File "/home/devadharshini/Downloads/od/venv/lib/python3.8/site-packages/autogluon/vision/configs/presets_configs.py", line 18, in _call
    return f(*gargs, **gkwargs)
  File "/home/devadharshini/Downloads/od/venv/lib/python3.8/site-packages/autogluon/vision/detector/detector.py", line 306, in fit
    self._detector = task.fit(train_data, tuning_data, 1 - holdout_frac, random_state)
  File "/home/devadharshini/Downloads/od/venv/lib/python3.8/site-packages/gluoncv/auto/tasks/object_detection.py", line 396, in fit
    raise RuntimeError(f'Unexpected error happened during fit: {pprint.pformat(results, indent=2)}')
RuntimeError: Unexpected error happened during fit: { 'args': { 'dist_ip_addrs': None,
            'early_stop_baseline': -inf,
            'early_stop_max_value': inf,
            'early_stop_patience': 10,
            'epochs': 1,
            'final_fit': True,
            'gpus': [],
            'log_dir': '/home/devadharshini/Downloads/od/224a0ca1',
            'lr': 0.001,
            'ngpus_per_trial': 0,
            'nthreads_per_trial': 32,
            'num_trials': 2,
            'num_workers': 4,
            'presets': 'best_quality',
            'scheduler': 'local',
            'search_strategy': 'random',
            'seed': 241,
            'time_limits': 14400,
            'train_data':                           image  ...                         image_attr
0   train/JPEGImages/000038.jpg  ...  {'width': 500.0, 'height': 375.0}
1   train/JPEGImages/000051.jpg  ...  {'width': 500.0, 'height': 375.0}
2   train/JPEGImages/000055.jpg  ...  {'width': 500.0, 'height': 333.0}
3   train/JPEGImages/000058.jpg  ...  {'width': 500.0, 'height': 375.0}
4   train/JPEGImages/000072.jpg  ...  {'width': 333.0, 'height': 500.0}
5   train/JPEGImages/000094.jpg  ...  {'width': 500.0, 'height': 333.0}
6   train/JPEGImages/000111.jpg  ...  {'width': 500.0, 'height': 375.0}
7   train/JPEGImages/000163.jpg  ...  {'width': 500.0, 'height': 432.0}
8   train/JPEGImages/000164.jpg  ...  {'width': 500.0, 'height': 375.0}
9   train/JPEGImages/000201.jpg  ...  {'width': 500.0, 'height': 344.0}
10  train/JPEGImages/000219.jpg  ...  {'width': 333.0, 'height': 500.0}
11  train/JPEGImages/000264.jpg  ...  {'width': 333.0, 'height': 500.0}
12  train/JPEGImages/000302.jpg  ...  {'width': 500.0, 'height': 375.0}
14  train/JPEGImages/000353.jpg  ...  {'width': 500.0, 'height': 375.0}
15  train/JPEGImages/000364.jpg  ...  {'width': 500.0, 'height': 375.0}
16  train/JPEGImages/000374.jpg  ...  {'width': 500.0, 'height': 375.0}
17  train/JPEGImages/000419.jpg  ...  {'width': 500.0, 'height': 375.0}
18  train/JPEGImages/000427.jpg  ...  {'width': 500.0, 'height': 334.0}
19  train/JPEGImages/000463.jpg  ...  {'width': 500.0, 'height': 175.0}
20  train/JPEGImages/000467.jpg  ...  {'width': 500.0, 'height': 331.0}
21  train/JPEGImages/000497.jpg  ...  {'width': 500.0, 'height': 500.0}
22  train/JPEGImages/000499.jpg  ...  {'width': 500.0, 'height': 375.0}
23  train/JPEGImages/000525.jpg  ...  {'width': 500.0, 'height': 331.0}
24  train/JPEGImages/000532.jpg  ...  {'width': 500.0, 'height': 331.0}
25  train/JPEGImages/000553.jpg  ...  {'width': 500.0, 'height': 375.0}
26  train/JPEGImages/000570.jpg  ...  {'width': 500.0, 'height': 375.0}
27  train/JPEGImages/000579.jpg  ...  {'width': 500.0, 'height': 332.0}
28  train/JPEGImages/000583.jpg  ...  {'width': 500.0, 'height': 276.0}
29  train/JPEGImages/000630.jpg  ...  {'width': 500.0, 'height': 375.0}
30  train/JPEGImages/000655.jpg  ...  {'width': 500.0, 'height': 375.0}
31  train/JPEGImages/000685.jpg  ...  {'width': 500.0, 'height': 375.0}
32  train/JPEGImages/000686.jpg  ...  {'width': 500.0, 'height': 375.0}
33  train/JPEGImages/000733.jpg  ...  {'width': 450.0, 'height': 435.0}
34  train/JPEGImages/000770.jpg  ...  {'width': 500.0, 'height': 375.0}
35  train/JPEGImages/000775.jpg  ...  {'width': 500.0, 'height': 465.0}

[35 rows x 3 columns],
            'transfer': Categorical['ssd_512_mobilenet1.0_coco', 'yolo3_mobilenet1.0_coco'],
            'val_data':                           image  ...                         image_attr
13  train/JPEGImages/000348.jpg  ...  {'width': 500.0, 'height': 334.0}

[1 rows x 3 columns],
            'wall_clock_tick': 1644409062.5332477},
  'best_config': {'transfer▁choice': 0},
  'best_reward': -inf,
  'config_history': OrderedDict(),
  'metadata': { 'resources_per_trial': {'num_cpus': 4, 'num_gpus': 0},
                'search_space': OrderedDict([ ( 'transfer▁choice',
                                                Categorical['ssd_512_mobilenet1.0_coco', 'yolo3_mobilenet1.0_coco'])]),
                'search_strategy': RandomSearcher(
ConfigSpace: Configuration space object:
  Hyperparameters:
    transfer▁choice, Type: Categorical, Choices: {0, 1}, Default: 0
.
Number of Trials: 2.
Best Config: {'transfer▁choice': 0}
Best Reward: -inf),
                'stop_criterion': {'max_reward': 0.9, 'time_limits': 14400}},
  'reward_attr': 'map_reward',
  'time': 2.4987130165100098,
  'total_time': 10.048343420028687,
  'traceback': 'Traceback (most recent call last):\n'
               '  File '
               '"/home/devadharshini/Downloads/od/venv/lib/python3.8/site-packages/gluoncv/auto/tasks/object_detection.py", '
               'line 141, in _train_object_detection\n'
               '    result = estimator.fit(train_data=train_data, '
               'val_data=val_data, time_limit=wall_clock_tick-tic)\n'
               '  File '
               '"/home/devadharshini/Downloads/od/venv/lib/python3.8/site-packages/gluoncv/auto/estimators/base_estimator.py", '
               'line 175, in fit\n'
               '    ret = self._fit(train_data, val_data, '
               'time_limit=time_limit) if not resume else \\\n'
               '  File '
               '"/home/devadharshini/Downloads/od/venv/lib/python3.8/site-packages/gluoncv/auto/estimators/ssd/ssd.py", '
               'line 87, in _fit\n'
               '    return self._resume_fit(train_data, val_data, '
               'time_limit=time_limit)\n'
               '  File '
               '"/home/devadharshini/Downloads/od/venv/lib/python3.8/site-packages/gluoncv/auto/estimators/ssd/ssd.py", '
               'line 112, in _resume_fit\n'
               '    train_loader, val_loader, train_eval_loader = '
               '_get_dataloader(\n'
               '  File '
               '"/home/devadharshini/Downloads/od/venv/lib/python3.8/site-packages/gluoncv/auto/estimators/ssd/utils.py", '
               'line 68, in _get_dataloader\n'
               '    train_loader = gluon.data.DataLoader(\n'
               '  File '
               '"/home/devadharshini/Downloads/od/venv/lib/python3.8/site-packages/mxnet/gluon/data/dataloader.py", '
               'line 665, in __init__\n'
               '    original_sigint_handler = signal.signal(signal.SIGINT, '
               'signal.SIG_IGN)\n'
               '  File "/usr/lib/python3.8/signal.py", line 47, in signal\n'
               '    handler = _signal.signal(_enum_to_int(signalnum), '
               '_enum_to_int(handler))\n'
               'ValueError: signal only works in main thread\n',
  'train_map': -1,
  'training_history': OrderedDict([(0, []), (1, [])]),
  'valid_map': -1}
127.0.0.1 - - [09/Feb/2022 13:47:52] "POST /detection HTTP/1.1" 500 -
/home/devadharshini/Downloads/od/main.py:99: DeprecationWarning: The 'attachment_filename' parameter has been renamed to 'download_name'. The old name will be removed in Flask 2.1.
  return send_file('Detection_Model.ag', attachment_filename='Detection_Model.ag')
Exception on /detection [GET]
Traceback (most recent call last):
  File "/home/devadharshini/Downloads/od/venv/lib/python3.8/site-packages/flask/app.py", line 2073, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/devadharshini/Downloads/od/venv/lib/python3.8/site-packages/flask/app.py", line 1518, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/devadharshini/Downloads/od/venv/lib/python3.8/site-packages/flask/app.py", line 1516, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/devadharshini/Downloads/od/venv/lib/python3.8/site-packages/flask/app.py", line 1502, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/devadharshini/Downloads/od/main.py", line 99, in detection_upload
    return send_file('Detection_Model.ag', attachment_filename='Detection_Model.ag')
  File "/home/devadharshini/Downloads/od/venv/lib/python3.8/site-packages/flask/helpers.py", line 612, in send_file
    return werkzeug.utils.send_file(
  File "/home/devadharshini/Downloads/od/venv/lib/python3.8/site-packages/werkzeug/utils.py", line 701, in send_file
    stat = os.stat(path)
FileNotFoundError: [Errno 2] No such file or directory: '/home/devadharshini/Downloads/od/Detection_Model.ag'
127.0.0.1 - - [09/Feb/2022 14:08:20] "GET /detection?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1" 500 -
```

**Comment by fcoppey** [comment]
same issue here

**Comment by Innixma** [comment]
Marking as completed, given that ObjectDetection has been entirely refactored and will exist in autogluon.multimodal going forward. Please re-open if issue persists in latest pre-release / v0.7
