### ISSUE TITLE
[BUG] Unable to train on multiple GPUs in Sagemaker Notebook Terminal

### ISSUE THREAD

**Issue by melrubino** [autogluon/autogluon#1650]
- [ X] I have checked that this bug exists on the latest stable version of AutoGluon
- [ ] and/or I have checked that this bug exists on the latest mainline of AutoGluon via source installation

**Describe the bug**
Autogluon 0.4.0 TextPredictor training on p3.8xl 4-GPU instance in Sagemaker Notebook terminal, with `env.num_gpus: 4` setting.  I get an error in spawning multiprocessing.  When I train with everything the same, but only on a single GPU within the same instance and setup, it trains without a problem.

**Expected behavior**
Train across all 4 GPUs in the p3.8xl instance with no errors.

**To Reproduce**
* SageMaker Notebook p3.8xl instance
* python 3.7.12.  
* pip install torch==1.10.0 autogluon.text==0.4.0 awswrangler pandas autofluon.features==0.4.0
* python train.py

Code:
in `train.py` file
```from argparse import Namespace

import pandas as pd
import awswrangler as wr
from autogluon.text import TextPredictor

args = Namespace(
    train_filename = "s3://ccds-asin-drc/eu/modeling-data/mf2_no_emb/train/0/train.parquet",
)

model_config = {
    "eval_metric": "accuracy",
    "time_limit": 60*60*3,
    "features": ['label', 'item_name_orig']
}

hyperparameters = {
    'model.hf_text.checkpoint_name': 'microsoft/mdeberta-v3-base',
    'optimization.top_k': 1,
    'optimization.lr_decay': 0.9,
    'optimization.learning_rate': 1e-4,
    'env.precision': 32,
    'env.per_gpu_batch_size': 4,
    'env.num_gpus': 4
}

train_df = wr.s3.read_parquet(args.full_train_filename)
print(train_df.info())

predictor = TextPredictor(
    label='label',
    eval_metric=model_config['eval_metric']
)

predictor.fit(
    train_data=train_df[model_config['features']],
    hyperparameters=hyperparameters,
    time_limit=model_config['time_limit']
)

```

**Screenshots**
Error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/multiprocessing/spawn.py", line 105, in spawn_main
    exitcode = _main(fd)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/multiprocessing/spawn.py", line 114, in _main
    prepare(preparation_data)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/multiprocessing/spawn.py", line 225, in prepare
    _fixup_main_from_path(data['init_main_from_path'])
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/multiprocessing/spawn.py", line 277, in _fixup_main_from_path
    run_name="__mp_main__")
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/ec2-user/SageMaker/rubinome_labs/lab/202203_drc_multilingual/train_textonly.py", line 46, in <module>
    time_limit=model_config['time_limit']
  File "/home/ec2-user/myagenv/lib/python3.7/site-packages/autogluon/text/text_prediction/predictor.py", line 248, in fit
    seed=seed,
  File "/home/ec2-user/myagenv/lib/python3.7/site-packages/autogluon/text/automm/predictor.py", line 410, in fit
    enable_progress_bar=self._enable_progress_bar,
  File "/home/ec2-user/myagenv/lib/python3.7/site-packages/autogluon/text/automm/predictor.py", line 561, in _fit
    ckpt_path=self._ckpt_path,  # this is to resume training that was broken accidentally
  File "/home/ec2-user/myagenv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 741, in fit
    self._fit_impl, model, train_dataloaders, val_dataloaders, datamodule, ckpt_path
  File "/home/ec2-user/myagenv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 685, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/home/ec2-user/myagenv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 777, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/home/ec2-user/myagenv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1199, in _run
    self._dispatch()
  File "/home/ec2-user/myagenv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1279, in _dispatch
    self.training_type_plugin.start_training(self)
  File "/home/ec2-user/myagenv/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 173, in start_training
    self.spawn(self.new_process, trainer, self.mp_queue, return_result=False)
  File "/home/ec2-user/myagenv/lib/python3.7/site-packages/pytorch_lightning/plugins/training_type/ddp_spawn.py", line 201, in spawn
    mp.spawn(self._wrapped_function, args=(function, args, kwargs, return_queue), nprocs=self.num_processes)
  File "/home/ec2-user/myagenv/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 230, in spawn
    return start_processes(fn, args, nprocs, join, daemon, start_method='spawn')
  File "/home/ec2-user/myagenv/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 179, in start_processes
    process.start()
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/multiprocessing/process.py", line 112, in start
    self._popen = self._Popen(self)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/multiprocessing/popen_spawn_posix.py", line 42, in _launch
    prep_data = spawn.get_preparation_data(process_obj._name)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/multiprocessing/spawn.py", line 143, in get_preparation_data
    _check_not_importing_main()
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/multiprocessing/spawn.py", line 136, in _check_not_importing_main
    is not going to be frozen to produce an executable.''')
RuntimeError: 
        An attempt has been made to start a new process before the
        current process has finished its bootstrapping phase.

        This probably means that you are not using fork to start your
        child processes and you have forgotten to use the proper idiom
        in the main module:

            if __name__ == '__main__':
                freeze_support()
                ...

        The "freeze_support()" line can be omitted if the program
        is not going to be frozen to produce an executable.
```

**Installed Versions**
Which version of AutoGluon are you are using?  
If you are using 0.4.0 and newer, please run the following code snippet:
<details>

```python
INSTALLED VERSIONS
------------------
date                 : 2022-04-06
time                 : 15:22:16.975165
python               : 3.7.12.final.0
OS                   : Linux
OS-release           : 4.14.252-131.483.amzn1.x86_64
Version              : #1 SMP Mon Nov 1 20:48:11 UTC 2021
machine              : x86_64
processor            : x86_64
num_cores            : 32
cpu_ram_mb           : 245845
cuda version         : 11.450.142.00
num_gpus             : 4
gpu_ram_mb           : [8404, 8476, 16160, 16160]
avail_disk_size_mb   : 11391

autogluon.common     : 0.4.0
autogluon.core       : 0.4.0
autogluon.features   : 0.4.0
autogluon.text       : 0.4.0
autogluon_contrib_nlp: None
boto3                : 1.21.34
dask                 : 2021.11.2
distributed          : 2021.11.2
fairscale            : 0.4.6
matplotlib           : 3.5.1
nptyping             : 1.4.4
numpy                : 1.21.5
omegaconf            : 2.1.1
pandas               : 1.3.5
PIL                  : 9.0.1
psutil               : 5.8.0
pytorch_lightning    : 1.5.10
ray                  : None
requests             : 2.27.1
scipy                : 1.7.3
sentencepiece        : None
skimage              : 0.19.2
sklearn              : 1.0.2
smart_open           : 5.2.1
timm                 : 0.5.4
torchmetrics         : 0.7.3
tqdm                 : 4.64.0
transformers         : 4.16.2
```

</details>

**Additional context**

**Comment by Abhinavb08** [comment]
I see a similar issue while training the text predictor 0.4 on an instance with multiple GPUs on SageMaker Studio.

**Comment by sxjscience** [comment]
@Abhinavb08 @melrubino  We need to write the code like follows (protect `.fit()` with `if __name__ == "__main__":`):

```python
import pandas as pd
import awswrangler as wr
from autogluon.text import TextPredictor

args = Namespace(
    train_filename = "s3://ccds-asin-drc/eu/modeling-data/mf2_no_emb/train/0/train.parquet",
)

model_config = {
    "eval_metric": "accuracy",
    "time_limit": 60*60*3,
    "features": ['label', 'item_name_orig']
}

hyperparameters = {
    'model.hf_text.checkpoint_name': 'microsoft/mdeberta-v3-base',
    'optimization.top_k': 1,
    'optimization.lr_decay': 0.9,
    'optimization.learning_rate': 1e-4,
    'env.precision': 32,
    'env.per_gpu_batch_size': 4,
    'env.num_gpus': 4
}

train_df = wr.s3.read_parquet(args.full_train_filename)
print(train_df.info())

if __name__ == "__main__":
    predictor = TextPredictor(
        label='label',
        eval_metric=model_config['eval_metric']
    )

    predictor.fit(
        train_data=train_df[model_config['features']],
        hyperparameters=hyperparameters,
        time_limit=model_config['time_limit']
    )

```

**Comment by Innixma** [comment]
Marking as complete, please create a new issue if issue persists in v0.7 release / pre-release when using autogluon.multimodal.
