### ISSUE TITLE
AutoMMPredictor has error loading checkpoint

### ISSUE THREAD

**Issue by KuanWeiBeCool** [autogluon/autogluon#1905]
Hi AutoGluon team, I was recently using AutoMMPredictor for my project. The training got interrupted somehow and I tried to load the model back using `predictor = AutoMMPredictor.load(path=model_path, resume=True, verbosity=4)` , where `model_path`  is the path to the directory of the model. I got the following error:
```
raise RuntimeError(error_msg)
RuntimeError: Early stopping conditioned on metric `val_accuracy` which is not available. Pass in or modify your `EarlyStopping` callback to use any of the following: ``
```
Could anyone look into the issue? Thanks!

For the complete traceback:

```
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/torch/multiprocessing/spawn.py", line 69, in_wrap
    fn(i, *args)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/pytorch_lightning/strategies/launchers/spawn.py", line 101, in _wrapping_function
    results = function(*args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 811, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1236, in _run
    results = self._run_stage()
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1323, in _run_stage
    return self._run_train()
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1353, in _run_train
    self.fit_loop.run()
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/pytorch_lightning/loops/fit_loop.py", line 269, in advance
    self._outputs = self.epoch_loop.run(self._data_fetcher)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 205, in run
    self.on_advance_end()
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 255, in on_advance_end
    self._run_validation()
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 309, in _run_validation
    self.val_loop.run()
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/pytorch_lightning/loops/base.py", line 211, in run
    output = self.on_run_end()
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 206, in on_run_end
    self._on_evaluation_end()
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 282, in _on_evaluation_end
    self.trainer._call_callback_hooks("on_validation_end", *args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 1636, in _call_callback_hooks
    fn(self, self.lightning_module, *args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/pytorch_lightning/callbacks/early_stopping.py", line 184, in on_validation_end
    self._run_early_stopping_check(trainer)
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/pytorch_lightning/callbacks/early_stopping.py", line 191, in _run_early_stopping_check
    logs
  File "/home/ec2-user/anaconda3/envs/JupyterSystemEnv/lib/python3.7/site-packages/pytorch_lightning/callbacks/early_stopping.py", line 145, in _validate_condition_metric
    raise RuntimeError(error_msg)
RuntimeError: Early stopping conditioned on metric `val_accuracy` which is not available. Pass in or modify your `EarlyStopping` callback to use any of the following: ``

```

**Comment by sxjscience** [comment]
@Linuxdex is taking a look.

**Comment by Linuxdex** [comment]
Excuse me, I can't reproduce your error for the time being. Can I have more details about your training?

**Comment by KuanWeiBeCool** [comment]
Thanks @sxjscience!
Sure @Linuxdex, here is what I have done: I firstly initiate a predictor using the following code:
`predictor = AutoMMPredictor(label='atin', path=model_path, verbosity=4)`
Then, I fit the predictor by calling `predictor.fit(train_data=df_train)`. After that, I let it trained for **more than one epoch** (I remember it was at 5 epoch) and the training got interrupted for some unknown reason. I then tried to resume the training by calling `predictor = AutoMMPredictor.load(path=model_path, resume=True, verbosity=4)` and the error popped upt. Also I used script for training so no variables will be stored after the interrupt happened.

Hope this helps!

**Comment by Linuxdex** [comment]
Thanks, @KuanWeiBeCool for the detailed information.
I tried to train and load in a similar way to what you have done, but I still can't reproduce the problem.
Would you like to try the latest autogluon and pytorch-lightning？

Hope this will help you!

**Comment by KuanWeiBeCool** [comment]
Thanks for your effort @Linuxdex! It might be a random case last time then. I will let you know if I see the same issue again using the latest AG

**Comment by Innixma** [comment]
Marking as resolved, please create a new issue if error persists in latest release.
