### ISSUE TITLE
[BUG] TabularPredictor.load('model').leaderboard(extra_info=True): No such file or directory: 'ag-model\\models\\KNeighborsDist\\info.pkl'

### ISSUE THREAD

**Issue by 2-5** [autogluon/autogluon#2452]
- [x] I have checked that this bug exists on the latest stable version of AutoGluon
- [ ] and/or I have checked that this bug exists on the latest mainline of AutoGluon via source installation

**Describe the bug**
`TabularPredictor.load('model').leaderboard(extra_info=True)` fails

**To Reproduce**
First train a model:
```python
from autogluon.tabular import TabularDataset, TabularPredictor

train_data = TabularDataset('https://autogluon.s3.amazonaws.com/datasets/Inc/train.csv')
predictor = TabularPredictor(label='class', path='ag-model').fit(train_data=train_data, time_limit=10)
```

In a **separate** script load it and get the `leaderboard` with `extra_info=True`.

```python
from autogluon.tabular import TabularPredictor

predictor = TabularPredictor.load('ag-model')
predictor.leaderboard(extra_info=True)
```

**IMPORTANT** do not combine these two steps in the same script, it will not fail then (which is weird).

Error:

```python
Traceback (most recent call last):
  File ".pyenv\lib\site-packages\autogluon\core\models\abstract\abstract_model.py", line 1436, in load_info
    return load_pkl.load(path=load_path)
  File ".pyenv\lib\site-packages\autogluon\common\loaders\load_pkl.py", line 42, in load
    with compression_fn_map[compression_fn]['open'](validated_path, 'rb', **compression_fn_kwargs) as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'ag-model\\models\\KNeighborsDist\\info.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "stat.py", line 4, in <module>
    predictor.leaderboard(extra_info=True)
  File ".pyenv\lib\site-packages\autogluon\tabular\predictor\predictor.py", line 1606, in leaderboard
    return self._learner.leaderboard(X=data, extra_info=extra_info, extra_metrics=extra_metrics,
  File ".pyenv\lib\site-packages\autogluon\tabular\learner\abstract_learner.py", line 632, in leaderboard
    leaderboard = trainer.leaderboard(extra_info=extra_info)
  File ".pyenv\lib\site-packages\autogluon\core\trainer\abstract_trainer.py", line 2339, in leaderboard
    info = self.get_info(include_model_info=True)
  File ".pyenv\lib\site-packages\autogluon\core\trainer\abstract_trainer.py", line 2479, in get_info
    info['model_info'] = self.get_models_info()
  File ".pyenv\lib\site-packages\autogluon\core\trainer\abstract_trainer.py", line 2494, in get_models_info
    model_info_dict[model] = model_type.load_info(path=model_path)
  File ".pyenv\lib\site-packages\autogluon\core\models\abstract\abstract_model.py", line 1439, in load_info
    model = cls.load(path=path, reset_paths=True)
  File ".pyenv\lib\site-packages\autogluon\core\models\abstract\abstract_model.py", line 851, in load
    model = load_pkl.load(path=file_path, verbose=verbose)
  File ".pyenv\lib\site-packages\autogluon\common\loaders\load_pkl.py", line 43, in load
    object = pickle.load(fin)
  File ".pyenv\lib\site-packages\daal4py\sklearn\__init__.py", line 17, in <module>
    from .monkeypatch.dispatcher import enable as patch_sklearn
  File ".pyenv\lib\site-packages\daal4py\sklearn\monkeypatch\dispatcher.py", line 30, in <module>
    from ..linear_model.coordinate_descent import Lasso as Lasso_daal4py
  File ".pyenv\lib\site-packages\daal4py\sklearn\linear_model\__init__.py", line 18, in <module>
    from .linear import LinearRegression
  File ".pyenv\lib\site-packages\daal4py\sklearn\linear_model\linear.py", line 17, in <module>
    from ._linear import *
  File ".pyenv\lib\site-packages\daal4py\sklearn\linear_model\_linear.py", line 26, in <module>
    from sklearn.utils.fixes import sparse_lsqr
ImportError: cannot import name 'sparse_lsqr' from 'sklearn.utils.fixes' (.pyenv\lib\site-packages\sklearn\utils\fixes.py)
```

Seems to be related to `scikit-learn-1.1.3` and `scikit-learn-intelex-2021.5.4`, if I remove the `sklearnex` package the script above doesn't fail anymore.

Issue: https://github.com/intel/scikit-learn-intelex/issues/1007

Seems to be fixed in `scikit-learn-intelex-2021.6.3`, but `autogluon-tabular-0.6.0` pins the version to `scikit-learn-intelex (<2021.6,>=2021.5)`

**Installed Versions**
<details>

```
INSTALLED VERSIONS
------------------
python              : 3.9.13.final.0
OS                  : Windows
OS-release          : 10

autogluon.common    : 0.6.0
autogluon.core      : 0.6.0
autogluon.features  : 0.6.0
autogluon.tabular   : 0.6.0
autogluon.timeseries: 0.6.0
boto3               : 1.26.13
catboost            : 1.1.1
dask                : 2021.11.2
distributed         : 2021.11.2
fastai              : 2.7.10
gluonts             : 0.11.2
hyperopt            : 0.2.7
joblib              : 1.2.0
lightgbm            : 3.3.3
matplotlib          : 3.6.2
networkx            : 2.8.8
numpy               : 1.23.5
pandas              : 1.5.1
psutil              : 5.8.0
pytorch_lightning   : 1.7.7
ray                 : 2.0.1
requests            : 2.28.1
scipy               : 1.9.3
setuptools          : 65.6.0
sklearn             : 1.1.3
statsmodels         : 0.13.5
torch               : 1.12.1+cu116
tqdm                : 4.64.1
xgboost             : 1.7.1
```

</details>

**Comment by Innixma** [comment]
Thanks for taking a look at this!!

Can you also try `>=2021.7` versions and see if those work? If so then I can try setting the range to include 2021.6 and 2021.7

**Comment by 2-5** [comment]
That's the version that I tested, `scikit_learn_intelex-2021.7.0`, so I can confirm that 2021.7 works.

**Comment by Innixma** [comment]
Thanks! I will look into upgrading the version requirement range.
