### ISSUE TITLE
[BUG] 'pandas._libs.tslibs.offsets.MonthBegin' object has no attribute '_period_dtype_code'

### ISSUE THREAD

**Issue by Enderfga** [autogluon/autogluon#2475]
My data is sorted by month frequency like 1844-01-01,1844-02-01, and I used ignore_time_index=True, and I ran it exactly as the example on the official website, but I still got the error：
'pandas._libs.tslibs.offsets.MonthBegin' object has no attribute '_period_dtype_code'
Traceback (most recent call last):
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/autogluon/timeseries/models/abstract/model_trial.py", line 38, in model_trial
    model = fit_and_save_model(
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/autogluon/timeseries/models/abstract/model_trial.py", line 72, in fit_and_save_model
    model.fit(
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/autogluon/timeseries/models/abstract/abstract_timeseries_model.py", line 188, in fit
    return super().fit(**kwargs)
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 587, in fit
    out = self._fit(**kwargs)
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/autogluon/timeseries/models/sktime/abstract_sktime.py", line 140, in _fit
    self._to_skt_data_frame(train_data[[self.target]]), fh=self._fh()
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/autogluon/timeseries/models/sktime/abstract_sktime.py", line 95, in _to_skt_data_frame
    data.index.get_level_values(1).to_period(freq=data.freq),  # noqa
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/pandas/core/indexes/extension.py", line 95, in method
    result = attr(self._data, *args, **kwargs)
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/pandas/core/arrays/_mixins.py", line 84, in method
    return meth(self, *args, **kwargs)
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/pandas/core/arrays/datetimes.py", line 1184, in to_period
    return PeriodArray._from_datetime64(self._ndarray, freq, tz=self.tz)
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/pandas/core/arrays/period.py", line 286, in _from_datetime64
    data, freq = dt64arr_to_periodarr(data, freq, tz)
  File "/root/miniconda3/envs/myenv/lib/python3.9/site-packages/pandas/core/arrays/period.py", line 1119, in dt64arr_to_periodarr
    base = freq._period_dtype_code
AttributeError: 'pandas._libs.tslibs.offsets.MonthBegin' object has no attribute '_period_dtype_code'

please help me

**Comment by shchur** [comment]
Hi, 

1. What version of AutoGluon are you using?
2. Can you please share the code that you ran that resulted in this error?

**Comment by Enderfga** [comment]
Thanks for the reply ！
1. version is 0.5.2 (I originally thought I was on the latest version, I will try to upgrade to fix this) 
3. the code is exactly the same as the quickstart on the official site

**Comment by Enderfga** [comment]
I am excited and guilty to reply to you, my model started training very successfully, I am sorry it was my oversight

**Comment by shchur** [comment]
No worries
