### ISSUE TITLE
[BUG] TimeSeriesPredictor.info() raises an exception and then exits

### ISSUE THREAD

**Issue by fantauzzi** [autogluon/autogluon#2498]
- [ X] I have checked that this bug exists on the latest stable version of AutoGluon
- [ ] and/or I have checked that this bug exists on the latest mainline of AutoGluon via source installation

**Describe the bug**
`TimeSeriesPredictor.info()` raises an exception `AttributeError: 'str' object has no attribute 'name'`

```
Traceback (most recent call last):
  File "/home/fanta/.pyenv/versions/python3.9.14/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 1436, in load_info
    return load_pkl.load(path=load_path)
  File "/home/fanta/.pyenv/versions/python3.9.14/lib/python3.9/site-packages/autogluon/common/loaders/load_pkl.py", line 42, in load
    with compression_fn_map[compression_fn]['open'](validated_path, 'rb', **compression_fn_kwargs) as fin:
FileNotFoundError: [Errno 2] No such file or directory: 'autogluon/models/Naive/info.pkl'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/fanta/workspace/autogluon_example/main.py", line 50, in <module>
    main()
  File "/home/fanta/workspace/autogluon_example/main.py", line 46, in main
    info = predictor.info() # AttributeError: 'str' object has no attribute 'name'
  File "/home/fanta/.pyenv/versions/python3.9.14/lib/python3.9/site-packages/autogluon/timeseries/predictor.py", line 599, in info
    return self._learner.get_info(include_model_info=True)
  File "/home/fanta/.pyenv/versions/python3.9.14/lib/python3.9/site-packages/autogluon/timeseries/learner.py", line 393, in get_info
    trainer_info = trainer.get_info(include_model_info=include_model_info)
  File "/home/fanta/.pyenv/versions/python3.9.14/lib/python3.9/site-packages/autogluon/timeseries/trainer/abstract_trainer.py", line 262, in get_info
    info["model_info"] = self.get_models_info()
  File "/home/fanta/.pyenv/versions/python3.9.14/lib/python3.9/site-packages/autogluon/timeseries/trainer/abstract_trainer.py", line 217, in get_models_info
    model_info_dict[model] = model_type.load_info(path=model_path)
  File "/home/fanta/.pyenv/versions/python3.9.14/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 1440, in load_info
    return model.get_info()
  File "/home/fanta/.pyenv/versions/python3.9.14/lib/python3.9/site-packages/autogluon/timeseries/models/abstract/abstract_timeseries_model.py", line 136, in get_info
    info_dict = super().get_info()
  File "/home/fanta/.pyenv/versions/python3.9.14/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 1412, in get_info
    'eval_metric': self.eval_metric.name,
AttributeError: 'str' object has no attribute 'name'
```

**Expected behavior**
The method should display and return the required information, as per [documentation](https://auto.gluon.ai/stable/api/autogluon.predictor.html?highlight=timeseriespredictor#module-5).

**To Reproduce**
https://github.com/fantauzzi/autogluon_example

Comment out line# 45 (otherwise you get another error, see https://github.com/autogluon/autogluon/issues/2497)
Run `main.py` 

Line #46 should reproduce the issue.

**Screenshots**
N/A

**Installed Versions**
Which version of AutoGluon are you are using?  
If you are using 0.4.0 and newer, please run the following code snippet:
<details>

```python
/home/fanta/.pyenv/versions/3.9.14/envs/python3.9.14/lib/python3.9/site-packages/autogluon/multimodal/data/process_image.py:27: UserWarning: Encountered error while import mmcv: No module named 'mmcv'
  warnings.warn(f"Encountered error while import mmcv: {e}")
/home/fanta/.pyenv/versions/3.9.14/envs/python3.9.14/lib/python3.9/site-packages/autogluon/multimodal/data/process_image.py:35: UserWarning: Encountered error while import mmdet: No module named 'mmdet'
  warnings.warn(f"Encountered error while import mmdet: {e}")
/home/fanta/.pyenv/versions/3.9.14/envs/python3.9.14/lib/python3.9/site-packages/autogluon/multimodal/models/mmdet_image.py:19: UserWarning: Encountered error while import mmcv: No module named 'mmcv'
  warnings.warn(f"Encountered error while import mmcv: {e}")
/home/fanta/.pyenv/versions/3.9.14/envs/python3.9.14/lib/python3.9/site-packages/autogluon/multimodal/models/mmdet_image.py:27: UserWarning: Encountered error while import mmdet: No module named 'mmdet'
  warnings.warn(f"Encountered error while import mmdet: {e}")
/home/fanta/.pyenv/versions/3.9.14/envs/python3.9.14/lib/python3.9/site-packages/autogluon/multimodal/optimization/lit_mmdet.py:19: UserWarning: Encountered error while import mmdet and mmcv: No module named 'mmdet'
  warnings.warn(f"Encountered error while import mmdet and mmcv: {e}")

INSTALLED VERSIONS
------------------
date                   : 2022-11-30
time                   : 15:11:19.121993
python                 : 3.9.14.final.0
OS                     : Linux
OS-release             : 5.15.0-53-generic
Version                : #59-Ubuntu SMP Mon Oct 17 18:53:30 UTC 2022
machine                : x86_64
processor              : x86_64
num_cores              : 16
cpu_ram_mb             : 32022
cuda version           : 11.510.85.02
num_gpus               : 1
gpu_ram_mb             : [7602]
avail_disk_size_mb     : 309915

accelerate             : 0.13.2
albumentations         : 1.1.0
autogluon.common       : 0.6.0
autogluon.core         : 0.6.0
autogluon.features     : 0.6.0
autogluon.multimodal   : 0.6.0
autogluon.tabular      : 0.6.0
autogluon.text         : 0.6.0
autogluon.timeseries   : 0.6.0
autogluon.vision       : 0.6.0
boto3                  : 1.26.13
catboost               : 1.1.1
dask                   : 2021.11.2
defusedxml             : 0.7.1
distributed            : 2021.11.2
evaluate               : 0.2.2
fairscale              : 0.4.6
fastai                 : 2.7.10
gluoncv                : 0.11.0
gluonts                : 0.11.2
hyperopt               : 0.2.7
joblib                 : 1.2.0
jsonschema             : 4.8.0
lightgbm               : 3.3.3
matplotlib             : 3.6.2
networkx               : 2.8.8
nlpaug                 : 1.1.10
nltk                   : 3.7
nptyping               : 1.4.4
numpy                  : 1.22.4
omegaconf              : 2.1.2
openmim                : None
pandas                 : 1.5.1
PIL                    : 9.0.1
psutil                 : 5.8.0
pycocotools            : None
pytorch-metric-learning: None
pytorch_lightning      : 1.7.7
ray                    : 2.0.1
requests               : 2.28.1
scipy                  : 1.8.1
sentencepiece          : 0.1.97
seqeval                : None
setuptools             : 58.1.0
skimage                : 0.19.3
sklearn                : 1.1.3
smart_open             : 5.2.1
statsmodels            : 0.13.5
text-unidecode         : None
timm                   : 0.6.11
torch                  : 1.12.0+cu113
torchmetrics           : 0.8.2
torchtext              : 0.13.0
torchvision            : 0.13.0+cu113
tqdm                   : 4.64.1
transformers           : 4.23.1
xgboost                : 1.7.1
```

</details>

**Additional context**
Also see https://github.com/autogluon/autogluon/issues/2497

**Comment by shchur** [comment]
Fixed by #2510
