### ISSUE TITLE
AutoGluon fails installation on Super Computer [BUG]

### ISSUE THREAD

**Issue by asmgx** [autogluon/autogluon#2521]
I am trying to install AutoGluon on my university computer (Linux)

I followed the instruction given here https://auto.gluon.ai/stable/index.html

```
pip3 install -U pip
pip3 install -U setuptools wheel

# CPU version of pytorch has smaller footprint - see installation instructions in
# pytorch documentation - https://pytorch.org/get-started/locally/
pip3 install torch==1.12+cpu torchvision==0.13.0+cpu torchtext==0.13.0 -f https://download.pytorch.org/whl/cpu/torch_stable.html

pip3 install autogluon
```

all steps ended successfully except for the last one **pip3 install autogluon**

I am getting this error

```

user99@tinaroo1:~/autogluon> pip3 install autogluon
Keyring is skipped due to an exception: 'EntryPoints' object has no attribute 'get'
Defaulting to user installation because normal site-packages is not writeable
Collecting autogluon
  Using cached autogluon-0.6.0-py3-none-any.whl (9.8 kB)
Collecting autogluon.multimodal==0.6.0
  Using cached autogluon.multimodal-0.6.0-py3-none-any.whl (279 kB)
Collecting autogluon.timeseries[all]==0.6.0
  Using cached autogluon.timeseries-0.6.0-py3-none-any.whl (101 kB)
Collecting autogluon.features==0.6.0
  Using cached autogluon.features-0.6.0-py3-none-any.whl (59 kB)
Collecting autogluon.core[all]==0.6.0
  Using cached autogluon.core-0.6.0-py3-none-any.whl (224 kB)
Collecting autogluon.vision==0.6.0
  Using cached autogluon.vision-0.6.0-py3-none-any.whl (49 kB)
Collecting autogluon.tabular[all]==0.6.0
  Using cached autogluon.tabular-0.6.0-py3-none-any.whl (285 kB)
Collecting autogluon.text==0.6.0
  Using cached autogluon.text-0.6.0-py3-none-any.whl (62 kB)
Requirement already satisfied: numpy<1.24,>=1.21 in /home/user99/.local/lib/python3.7/site-packages (from autogluon.core[all]==0.6.0->autogluon) (1.21.5)
Requirement already satisfied: scipy<1.10.0,>=1.5.4 in /home/user99/.local/lib/python3.7/site-packages (from autogluon.core[all]==0.6.0->autogluon) (1.7.1)
Collecting autogluon.common==0.6.0
  Using cached autogluon.common-0.6.0-py3-none-any.whl (41 kB)
Requirement already satisfied: matplotlib in /mnt/sw/legacy/sw1/RCC/Anaconda/2020.02/lib/python3.7/site-packages (from autogluon.core[all]==0.6.0->autogluon) (3.2.2)
Requirement already satisfied: tqdm>=4.38.0 in /mnt/sw/legacy/sw1/RCC/Anaconda/2020.02/lib/python3.7/site-packages (from autogluon.core[all]==0.6.0->autogluon) (4.47.0)
Requirement already satisfied: requests in /mnt/sw/legacy/sw1/RCC/Anaconda/2020.02/lib/python3.7/site-packages (from autogluon.core[all]==0.6.0->autogluon) (2.24.0)
Requirement already satisfied: scikit-learn<1.2,>=1.0.0 in /home/user99/.local/lib/python3.7/site-packages (from autogluon.core[all]==0.6.0->autogluon) (1.0.2)
Requirement already satisfied: pandas!=1.4.0,<1.6,>=1.2.5 in /home/user99/.local/lib/python3.7/site-packages (from autogluon.core[all]==0.6.0->autogluon) (1.3.5)
Requirement already satisfied: boto3 in /home/user99/.local/lib/python3.7/site-packages (from autogluon.core[all]==0.6.0->autogluon) (1.26.23)
Requirement already satisfied: dask<=2021.11.2,>=2021.09.1 in /home/user99/.local/lib/python3.7/site-packages (from autogluon.core[all]==0.6.0->autogluon) (2021.11.2)
Requirement already satisfied: distributed<=2021.11.2,>=2021.09.1 in /home/user99/.local/lib/python3.7/site-packages (from autogluon.core[all]==0.6.0->autogluon) (2021.11.2)
Requirement already satisfied: ray<2.1,>=2.0 in /home/user99/.local/lib/python3.7/site-packages (from autogluon.core[all]==0.6.0->autogluon) (2.0.1)
Requirement already satisfied: hyperopt<0.2.8,>=0.2.7 in /home/user99/.local/lib/python3.7/site-packages (from autogluon.core[all]==0.6.0->autogluon) (0.2.7)
Requirement already satisfied: psutil<6,>=5.7.3 in /home/user99/.local/lib/python3.7/site-packages (from autogluon.features==0.6.0->autogluon) (5.9.4)
Collecting seqeval<=1.2.2
  Using cached seqeval-1.2.2.tar.gz (43 kB)
  Preparing metadata (setup.py) ... done
Collecting omegaconf<2.2.0,>=2.1.1
  Using cached omegaconf-2.1.2-py3-none-any.whl (74 kB)
Collecting scikit-image<0.20.0,>=0.19.1
  Using cached scikit_image-0.19.3-cp37-cp37m-manylinux_2_12_x86_64.manylinux2010_x86_64.whl (13.5 MB)
Collecting sentencepiece<0.2.0,>=0.1.95
  Using cached sentencepiece-0.1.97-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (1.3 MB)
Collecting torchmetrics<0.9.0,>=0.8.0
  Using cached torchmetrics-0.8.2-py3-none-any.whl (409 kB)
Requirement already satisfied: torchvision<0.14.0 in /home/user99/.local/lib/python3.7/site-packages (from autogluon.multimodal==0.6.0->autogluon) (0.13.0+cpu)
Collecting accelerate<0.14,>=0.9
  Using cached accelerate-0.13.2-py3-none-any.whl (148 kB)
Collecting evaluate<=0.2.2
  Using cached evaluate-0.2.2-py3-none-any.whl (69 kB)
Collecting nptyping<1.5.0,>=1.4.4
  Using cached nptyping-1.4.4-py3-none-any.whl (31 kB)
Collecting defusedxml<=0.7.1,>=0.7.1
  Using cached defusedxml-0.7.1-py2.py3-none-any.whl (25 kB)
Collecting openmim<=0.2.1,>0.1.5
  Using cached openmim-0.2.1-py2.py3-none-any.whl (49 kB)
Requirement already satisfied: torchtext<0.14.0 in /home/user99/.local/lib/python3.7/site-packages (from autogluon.multimodal==0.6.0->autogluon) (0.13.0)
Collecting albumentations<=1.2.0,>=1.1.0
  Using cached albumentations-1.2.0-py3-none-any.whl (113 kB)
Collecting pycocotools<2.0.7,>=2.0.5
  Using cached pycocotools-2.0.6.tar.gz (24 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: -11
  ╰─> [35 lines of output]
      OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 50 current, 514567 max
      OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 50 current, 514567 max
      OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 50 current, 514567 max
      OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 50 current, 514567 max
      OpenBLAS blas_thread_init: pthread_create: Resource temporarily unavailable
      OpenBLAS blas_thread_init: RLIMIT_NPROC 50 current, 514567 max
      Traceback (most recent call last):
        File "/home/user99/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 351, in <module>
          main()
        File "/home/user99/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/home/user99/.local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/scratch/user/user99/tmp/pip-build-env-j7xhslnv/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/scratch/user/user99/tmp/pip-build-env-j7xhslnv/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "/scratch/user/user99/tmp/pip-build-env-j7xhslnv/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 7, in <module>
        File "/scratch/user/user99/tmp/pip-build-env-j7xhslnv/overlay/lib/python3.7/site-packages/numpy/__init__.py", line 142, in <module>
          from . import add_newdocs
        File "/scratch/user/user99/tmp/pip-build-env-j7xhslnv/overlay/lib/python3.7/site-packages/numpy/add_newdocs.py", line 13, in <module>
          from numpy.lib import add_newdoc
        File "/scratch/user/user99/tmp/pip-build-env-j7xhslnv/overlay/lib/python3.7/site-packages/numpy/lib/__init__.py", line 8, in <module>
          from .type_check import *
        File "/scratch/user/user99/tmp/pip-build-env-j7xhslnv/overlay/lib/python3.7/site-packages/numpy/lib/type_check.py", line 11, in <module>
          import numpy.core.numeric as _nx
        File "/scratch/user/user99/tmp/pip-build-env-j7xhslnv/overlay/lib/python3.7/site-packages/numpy/core/__init__.py", line 16, in <module>
          from . import multiarray
      KeyboardInterrupt
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: -11
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
user99@tinaroo1:~/autogluon>

```

I wonder if it makes sense to anyone and can help me fixing that.

**Comment by Innixma** [comment]
It appears like your issue is with the pycoco package. You may want to focus on that package specifically when debugging.

**Comment by bryanyzhu** [comment]
Hi, based on the error message, the issue might be different than #2494 . The error message here shows `pthread_create: Resource temporarily unavailable`, which means it takes more threads than default in your system when building wheels. See these posts for similar issues, [stackoverflow](https://stackoverflow.com/questions/52026652/openblas-blas-thread-init-pthread-create-resource-temporarily-unavailable), [eDFTpy](http://edftpy.rutgers.edu/faq.html). Maybe you can try to set the environment variable first, like `export OMP_NUM_THREADS=1` or `export OPENBLAS_NUM_THREADS=1`

**Comment by sxjscience** [comment]
Also, @asmgx what’s the Linux distribution that you are using? In addition, I recommend Anaconda, which is a tested environments.

**Comment by bryanyzhu** [comment]
@asmgx  Hi, we have removed pycocotools from our dependencies and release 0.6.1. Please try `pip install autogluon` again. Let me know if the problem persist, thank you.

**Comment by Innixma** [comment]
Marking as resolved due to removing pycoco dependency. Please indicate if this problem has been fixed, and please re-open if errors still occur in AutoGluon v0.6.1.
