### ISSUE TITLE
[BUG] error occurred for japanese ner task

### ISSUE THREAD

**Issue by HeroadZ** [autogluon/autogluon#3030]
- [x] I have checked that this bug exists on the latest stable version of AutoGluon
- [x] and/or I have checked that this bug exists on the latest mainline of AutoGluon via source installation

**Describe the bug**
According to [chinese ner documentation](https://auto.gluon.ai/stable/tutorials/multimodal/text_prediction/chinese_ner.htm), I try to finetune a japanese ner model.
But the current autogluon code seems doesn't support bert japanese tokenizer.

**Expected behavior**
I change the model from `hfl/chinese-lert-small` to `cl-tohoku/bert-base-japanese-v2`. I want autogluon to do training for me, the same thing in chinese ner documentation.

**To Reproduce**
ner_ja.csv
```csv
text,entity_annotations
SPRiNGSと最も仲の良いライバルグループ。,"[{""entity_group"": ""\u305d\u306e\u4ed6\u306e\u7d44\u7e54\u540d"", ""start"": 0, ""end"": 7}]"
レッドフォックス株式会社は、東京都千代田区に本社を置くITサービス企業である。,"[{""entity_group"": ""\u6cd5\u4eba\u540d"", ""start"": 0, ""end"": 12}, {""entity_group"": ""\u5730\u540d"", ""start"": 14, ""end"": 21}]"
松友美佐紀は、日本のバドミントン選手。,"[{""entity_group"": ""\u4eba\u540d"", ""start"": 0, ""end"": 5}, {""entity_group"": ""\u5730\u540d"", ""start"": 7, ""end"": 9}]"
ライターの兵庫慎司は普通にアイドルポップスとして出すと売れず、無理にバンドとコラボレーションさせるのも先例からして上手くいかない、それならロックミュージシャンと制作すればいいということになったのではないかとしている。,"[{""entity_group"": ""\u4eba\u540d"", ""start"": 5, ""end"": 9}]"
またCMソング、コミックスイメージアルバム、ゲームミュージック等にボーカルとして多数参加している他、コーラスとして他のアーティストのアルバム等にも参加している。,[]
```
ner_ja.py
```py
# %%
import autogluon.multimodal
from autogluon.core.utils.loaders import load_pd
from autogluon.multimodal.utils import visualize_ner
train_data = load_pd.load('./ner_ja.csv')
train_data.head(5)

# %%
visualize_ner(train_data["text"].iloc[0], train_data["entity_annotations"].iloc[0])
# %%
from autogluon.multimodal import MultiModalPredictor
import uuid

label_col = "entity_annotations"
model_path = f"./tmp/{uuid.uuid4().hex}-automm_ner"  # You can rename it to the model path you like
predictor = MultiModalPredictor(problem_type="ner", label=label_col, path=model_path)
predictor.fit(
    train_data=train_data,
    hyperparameters={'model.ner_text.checkpoint_name':'cl-tohoku/bert-base-japanese-v2'},
    time_limit=300, #second
)
```

**Screenshots**

**Installed Versions**
Which version of AutoGluon are you are using?  
If you are using 0.4.0 and newer, please run the following code snippet:
I'm using the latest 0.7.0
<details>

```python
INSTALLED VERSIONS
------------------
date                   : 2023-03-11
time                   : 23:44:27.255365
python                 : 3.8.10.final.0
OS                     : Linux
OS-release             : 5.4.72-microsoft-standard-WSL2
Version                : #1 SMP Wed Oct 28 23:40:43 UTC 2020
machine                : x86_64
processor              : x86_64
num_cores              : 12
cpu_ram_mb             : 15972
cuda version           : 12.527.92.01
num_gpus               : 1
gpu_ram_mb             : [4657]
avail_disk_size_mb     : 223226

accelerate             : 0.16.0
autogluon.common       : 0.7.0
autogluon.core         : 0.7.0
autogluon.features     : 0.7.0
autogluon.multimodal   : 0.7.0
autogluon.tabular      : 0.7.0
autogluon.timeseries   : 0.7.0
boto3                  : 1.26.89
catboost               : 1.1.1
defusedxml             : 0.7.1
evaluate               : 0.3.0
fairscale              : 0.4.13
fastai                 : 2.7.11
gluonts                : 0.12.3
hyperopt               : 0.2.7
jinja2                 : 3.1.2
joblib                 : 1.2.0
jsonschema             : 4.17.3
lightgbm               : 3.3.5
matplotlib             : 3.7.1
networkx               : 2.8.8
nlpaug                 : 1.1.11
nltk                   : 3.8.1
nptyping               : 2.4.1
numpy                  : 1.24.2
omegaconf              : 2.2.3
openmim                : None
pandas                 : 1.5.3
PIL                    : 9.4.0
psutil                 : 5.9.4
pytesseract            : 0.3.10
pytorch-metric-learning: None
pytorch_lightning      : 1.9.4
ray                    : 2.2.0
requests               : 2.28.2
scipy                  : 1.10.1
sentencepiece          : 0.1.97
seqeval                : None
setuptools             : 67.6.0
skimage                : 0.19.3
sklearn                : 1.2.2
statsforecast          : 1.4.0
statsmodels            : 0.13.5
tensorboard            : 2.12.0
text-unidecode         : None
timm                   : 0.6.12
torch                  : 1.13.1+cu117
torchmetrics           : 0.8.2
torchvision            : 0.14.1+cu117
tqdm                   : 4.65.0
transformers           : 4.26.1
ujson                  : 5.7.0
xgboost                : 1.7.4
```

```
AttributeError: Caught AttributeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/chance/ner/venv/lib/python3.8/site-packages/autogluon/multimodal/data/dataset.py", line 100, in 
__getitem__
    per_ret = apply_data_processor(
  File "/home/chance/ner/venv/lib/python3.8/site-packages/autogluon/multimodal/data/utils.py", line 174, in 
apply_data_processor
    per_model_processor(
  File "/home/chance/ner/venv/lib/python3.8/site-packages/autogluon/multimodal/data/process_ner.py", line 178, in 
__call__
    ret = self.process_ner(all_features, feature_modalities, is_training)
  File "/home/chance/ner/venv/lib/python3.8/site-packages/autogluon/multimodal/data/process_ner.py", line 136, in 
process_ner
    label, col_tokens, token_to_word_mappings, word_offsets = process_ner_annotations(
  File "/home/chance/ner/venv/lib/python3.8/site-packages/autogluon/multimodal/data/utils.py", line 270, in 
process_ner_annotations
    col_tokens, token_to_word_mappings, word_offsets = tokenize_ner_text(ner_text, tokenizer)
  File "/home/chance/ner/venv/lib/python3.8/site-packages/autogluon/multimodal/data/utils.py", line 329, in 
tokenize_ner_text
    words_with_offsets = tokenizer.backend_tokenizer.pre_tokenizer.pre_tokenize_str(text)
AttributeError: 'BertJapaneseTokenizer' object has no attribute 'backend_tokenizer'
```
</details>

**Additional context**
main error: AttributeError: 'BertJapaneseTokenizer' object has no attribute 'backend_tokenizer'
In the autogluon > multimodal > data > utils.py line 329
```py
    words_with_offsets = tokenizer.backend_tokenizer.pre_tokenizer.pre_tokenize_str(text)
```

`pip intall fugashi[unidic-lite]` is necessary to run the code above

**Comment by cheungdaven** [comment]
Hi @HeroadZ, thanks for reporting this BUG to us.

We did some refactor since 0.7.0 and you may try the latest version. However, with the checkpoint "cl-tohoku/bert-base-japanese-v2", I still got an issue (related to [issue](https://github.com/huggingface/transformers/issues/14860) of transformer) with the latest autogluon. 

But when I use other checkpoints like ku-nlp/deberta-v2-base-japanese, the code runs through without errors. Feel free to let me know if it addresses your issue.

**Comment by HeroadZ** [comment]
@cheungdaven Thank you for your help! 
> the model that doesn't have a fast tokenizer can't be finetuned by autogluno.

I see.
https://github.com/huggingface/transformers/issues/12381 Japanese fast tokenizer has not been supported yet.
Seems like It's better to check tokenizer.is_fast before using autogluon.
Thank you very much!
