### ISSUE TITLE
[BUG]  RandomForestMSE, ExtraTreesMSE failed on quantile regression. 

### ISSUE THREAD

**Issue by taidbui** [autogluon/autogluon#3176]
**Bug Report Checklist**

- [x] I provided code that demonstrates a minimal reproducible example.  
- [x] I confirmed bug exists on the latest mainline of AutoGluon via source install.  
- [x] I confirmed bug exists on the latest stable version of AutoGluon.  

**Describe the bug**
Quantile regressions failed on RandomForestMSE and ExtraTreesMSE models due to `TypeError: __init__() missing 1 required positional argument: 'estimator'`

**To Reproduce**
```
from autogluon.tabular import TabularPredictor, TabularDataset
data_url = 'https://raw.githubusercontent.com/mli/ag-docs/main/knot_theory/'
train_data = TabularDataset(f'{data_url}train.csv')
label = 'signature'
test_data = TabularDataset(f'{data_url}test.csv')
quantile_levels = [0.1, 0.5, 0.9]  # which quantiles of numeric label-variable we want to predict
predictor = TabularPredictor(label=label, problem_type='quantile', quantile_levels=quantile_levels, ).fit(train_data)
predictor.leaderboard(test_data, silent=True)
```
**Screenshots / Logs**
```
Loaded data from: https://raw.githubusercontent.com/mli/ag-docs/main/knot_theory/train.csv | Columns = 19 / 19 | Rows = 10000 -> 10000
Loaded data from: https://raw.githubusercontent.com/mli/ag-docs/main/knot_theory/test.csv | Columns = 19 / 19 | Rows = 5000 -> 5000
No path specified. Models will be saved in: "AutogluonModels/ag-20230425_131526/"
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20230425_131526/"
AutoGluon Version:  0.7.0
Python Version:     3.9.16
Operating System:   Darwin
Platform Machine:   arm64
Platform Version:   Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
Train Data Rows:    10000
Train Data Columns: 18
Label Column: signature
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    14763.95 MB
	Train Data (Original)  Memory Usage: 1.44 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 5 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Useless Original Features (Count: 1): ['Symmetry_D8']
		These features carry no predictive signal and should be manually investigated.
		This is typically a feature which has the same value for all rows.
		These features do not need to be present at inference time.
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 14 | ['chern_simons', 'cusp_volume', 'injectivity_radius', 'longitudinal_translation', 'meridinal_translation_imag', ...]
		('int', [])   :  3 | ['Unnamed: 0', 'hyperbolic_adjoint_torsion_degree', 'hyperbolic_torsion_degree']
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])     : 9 | ['chern_simons', 'cusp_volume', 'injectivity_radius', 'longitudinal_translation', 'meridinal_translation_imag', ...]
		('int', [])       : 3 | ['Unnamed: 0', 'hyperbolic_adjoint_torsion_degree', 'hyperbolic_torsion_degree']
		('int', ['bool']) : 5 | ['Symmetry_0', 'Symmetry_D3', 'Symmetry_D4', 'Symmetry_D6', 'Symmetry_Z/2 + Z/2']
	0.0s = Fit runtime
	17 features in original data used to generate 17 features in processed data.
	Train Data (Processed) Memory Usage: 1.01 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.04s ...
AutoGluon will gauge predictive performance using evaluation metric: 'pinball_loss'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 9000, Val Rows: 1000
Fitting 4 L1 models ...
Fitting model: RandomForestMSE ...
	Warning: Exception caused RandomForestMSE to fail during training... Skipping this model.
		__init__() missing 1 required positional argument: 'estimator'
Detailed Traceback:
Traceback (most recent call last):
  File "/Users/tb/miniforge3/envs/ag/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1502, in _train_and_save
    model = self._train_single(X, y, model, X_val, y_val, total_resources=total_resources, **model_fit_kwargs)
  File "/Users/tb/miniforge3/envs/ag/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1447, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, total_resources=total_resources, **model_fit_kwargs)
  File "/Users/tb/miniforge3/envs/ag/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 703, in fit
    out = self._fit(**kwargs)
  File "/Users/tb/miniforge3/envs/ag/lib/python3.9/site-packages/autogluon/tabular/models/rf/rf_model.py", line 190, in _fit
    model = model_cls(**params)
  File "/Users/tb/miniforge3/envs/ag/lib/python3.9/site-packages/autogluon/tabular/models/rf/rf_quantile.py", line 688, in __init__
    super(RandomForestQuantileRegressor, self).__init__(
TypeError: __init__() missing 1 required positional argument: 'estimator'
Fitting model: ExtraTreesMSE ...
	Warning: Exception caused ExtraTreesMSE to fail during training... Skipping this model.
		__init__() missing 1 required positional argument: 'estimator'
Detailed Traceback:
Traceback (most recent call last):
  File "/Users/tb/miniforge3/envs/ag/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1502, in _train_and_save
    model = self._train_single(X, y, model, X_val, y_val, total_resources=total_resources, **model_fit_kwargs)
  File "/Users/tb/miniforge3/envs/ag/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1447, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, total_resources=total_resources, **model_fit_kwargs)
  File "/Users/tb/miniforge3/envs/ag/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 703, in fit
    out = self._fit(**kwargs)
  File "/Users/tb/miniforge3/envs/ag/lib/python3.9/site-packages/autogluon/tabular/models/rf/rf_model.py", line 190, in _fit
    model = model_cls(**params)
  File "/Users/tb/miniforge3/envs/ag/lib/python3.9/site-packages/autogluon/tabular/models/rf/rf_quantile.py", line 840, in __init__
    super(ExtraTreesQuantileRegressor, self).__init__(
TypeError: __init__() missing 1 required positional argument: 'estimator'
Fitting model: NeuralNetFastAI ...
	-0.1335	 = Validation score   (-pinball_loss)
	29.2s	 = Training   runtime
	0.18s	 = Validation runtime
Fitting model: NeuralNetTorch ...
```

**Installed Versions**
autogluon=0.7.0

```python

INSTALLED VERSIONS
------------------
date                   : 2023-04-25
time                   : 14:21:31.648487
python                 : 3.9.16.final.0
OS                     : Darwin
OS-release             : 22.4.0
Version                : Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000
machine                : arm64
processor              : arm
num_cores              : 10
cpu_ram_mb             : 32768
cuda version           : None
num_gpus               : 0
gpu_ram_mb             : []
avail_disk_size_mb     : 704609

accelerate             : 0.16.0
autogluon.common       : 0.7.0
autogluon.core         : 0.7.0
autogluon.features     : 0.7.0
autogluon.multimodal   : 0.7.0
autogluon.tabular      : 0.7.0
autogluon.timeseries   : 0.7.0
boto3                  : 1.26.119
catboost               : 1.1.1
defusedxml             : 0.7.1
evaluate               : 0.3.0
fairscale              : 0.4.13
fastai                 : 2.7.12
gluonts                : 0.12.7
hyperopt               : 0.2.7
jinja2                 : 3.1.2
joblib                 : 1.2.0
jsonschema             : 4.17.3
lightgbm               : 3.3.5
matplotlib             : 3.7.1
networkx               : 2.8.8
nlpaug                 : 1.1.11
nltk                   : 3.8.1
nptyping               : 2.4.1
numpy                  : 1.24.3
omegaconf              : 2.2.3
openmim                : None
pandas                 : 1.5.3
PIL                    : 9.4.0
psutil                 : 5.9.5
pytesseract            : 0.3.10
pytorch-metric-learning: None
pytorch_lightning      : 1.9.5
ray                    : 2.2.0
requests               : 2.28.2
scipy                  : 1.10.1
sentencepiece          : 0.1.98
seqeval                : None
setuptools             : 67.7.2
skimage                : 0.19.3
sklearn                : 1.2.2
statsforecast          : 1.4.0
statsmodels            : 0.13.5
tensorboard            : 2.11.2
text-unidecode         : None
timm                   : 0.6.13
torch                  : 1.13.1
torchmetrics           : 0.8.2
torchvision            : 0.14.1
tqdm                   : 4.65.0
transformers           : 4.26.1
ujson                  : 5.7.0
xgboost                : 1.7.5

```

</details>

**Comment by shchur** [comment]
This is caused by the new version of scikit-learn (v1.2.2). The name of the argument in `ForestRegressor` got changed from 
[`base_estimator`](https://github.com/autogluon/autogluon/blob/14e82d40847b8dda2a693c0c6f91a1ba734fc7a4/tabular/src/autogluon/tabular/models/rf/rf_quantile.py#L689) used in our code to [`estimator`](https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/ensemble/_forest.py#L932). 

As a temporary solution, you can try downgrading to v1.1.1 - this definitely works for me locally.

@Innixma I guess we need to add a stricter version cap in [`_setup_utils.py`](https://github.com/autogluon/autogluon/blob/14e82d40847b8dda2a693c0c6f91a1ba734fc7a4/core/src/autogluon/core/_setup_utils.py#L25) or change the kwargs used in `BaseForestQuantileRegressor` in AutoGluon.
