### ISSUE TITLE
[BUG] AutoGluon 0.8.0 TabularPredictor.fit in hung state on SageMaker Notebooks

### ISSUE THREAD

**Issue by anand086** [autogluon/autogluon#3340]
**Bug Report Checklist**

- [ ] I provided code that demonstrates a minimal reproducible example.  
- [ ] I confirmed bug exists on the latest mainline of AutoGluon via source install.  
- [ ] I confirmed bug exists on the latest stable version of AutoGluon.  

**Describe the bug**
I am running the following on SageMaker Notebook [ Amazon Linux 2, Jupyter Lab 3(notebook-al2-v2) ] using the conda_pytorch_p310 kernel (tried conda_python3 as well ) and the training is hung after showing the error specified in Screenshots / Logs section.

```
predictor = TabularPredictor(label=label, path=save_path, problem_type='regression').fit(
        train_data= train_data,  
        excluded_model_types = ['NN_TORCH', 'LR', 'FASTAI'],
        time_limit=1800, 
        presets='best_quality',
    )

```

**Expected behavior**

Model training to continue normally.  
Tried the same with AutoGluon 0.7.0 on Amazon SageMaker Notebooks (conda_python3 Kernel) with the same dataset and the training completed successfully. 

**To Reproduce**

**Screenshots / Logs**

```
AutoGluon will gauge predictive performance using evaluation metric: 'root_mean_squared_error'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
AutoGluon will fit 2 stack levels (L1 to L2) ...
Excluded models: ['NN_TORCH', 'FASTAI'] (Specified by `excluded_model_types`)
Fitting 9 L1 models ...
Fitting model: KNeighborsUnif_BAG_L1 ... Training model for up to 1199.41s of the 1799.57s of remaining time.
/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")
	-112.1775	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.18s	 = Validation runtime
Fitting model: KNeighborsDist_BAG_L1 ... Training model for up to 1193.25s of the 1793.4s of remaining time.
	-114.1985	 = Validation score   (-root_mean_squared_error)
	0.01s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 1193.19s of the 1793.34s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy
2023-06-21 06:46:13,054	ERROR services.py:1169 -- Failed to start the dashboard , return code 1
2023-06-21 06:46:13,055	ERROR services.py:1194 -- Error should be written to 'dashboard.log' or 'dashboard.err'. We are printing the last 20 lines for you. See 'https://docs.ray.io/en/master/ray-observability/ray-logging.html#logging-directory-structure' to find where the log file is.
2023-06-21 06:46:13,056	ERROR services.py:1238 -- 
The last 20 lines of /tmp/ray/session_2023-06-21_06-46-11_108937_29587/logs/dashboard.log (it contains the error message from the dashboard): 
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ray/dashboard/utils.py", line 121, in get_all_modules
    importlib.import_module(name)
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ray/dashboard/modules/reporter/reporter_agent.py", line 52, in <module>
    import gpustat.core as gpustat
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/gpustat/__init__.py", line 16, in <module>
    from .core import GPUStat, GPUStatCollection
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/gpustat/core.py", line 24, in <module>
    from gpustat.nvml import pynvml as N
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/gpustat/nvml.py", line 57, in <module>
    _original_nvmlGetFunctionPointer = pynvml._nvmlGetFunctionPointer
AttributeError: module 'pynvml' has no attribute '_nvmlGetFunctionPointer'
[2023-06-21 06:46:14,377 E 29587 30517] core_worker.cc:569: :info_message: Attempting to recover 11 lost objects by resubmitting their tasks. To disable object reconstruction, set @ray.remote(max_retries=0).
```

**Installed Versions**

<details>

```python
INSTALLED VERSIONS
------------------
date                : 2023-06-21
time                : 07:00:46.215183
python              : 3.10.10.final.0
OS                  : Linux
OS-release          : 5.10.178-162.673.amzn2.x86_64
Version             : #1 SMP Mon Apr 24 23:34:06 UTC 2023
machine             : x86_64
processor           : x86_64
num_cores           : 16
cpu_ram_mb          : 62825
cuda version        : None
num_gpus            : 0
gpu_ram_mb          : []
avail_disk_size_mb  : 47638

autogluon           : None
autogluon.common    : 0.8.0
autogluon.core      : 0.8.0
autogluon.features  : 0.8.0
autogluon.tabular   : 0.8.0
boto3               : 1.26.144
catboost            : 1.2
fastai              : 2.7.12
hyperopt            : 0.2.7
imodels             : None
lightgbm            : 3.3.5
matplotlib          : 3.7.1
networkx            : 3.1
numpy               : 1.24.3
onnxruntime-gpu     : None
pandas              : 1.5.3
psutil              : 5.9.4
ray                 : 2.3.1
requests            : 2.29.0
scikit-learn        : 1.2.2
scikit-learn-intelex: None
scipy               : 1.10.1
setuptools          : 67.7.2
skl2onnx            : None
tabpfn              : 0.1.9
torch               : 1.13.1
tqdm                : 4.65.0
vowpalwabbit        : None
xgboost             : 1.7.6

```

</details>

**Comment by anand086** [comment]
I interrupted the kernel and re-ran the TabularPredictor.fit which errored out with the following:

```
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 1199.33s of the 1799.51s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy
	Warning: Exception caused LightGBMXT_BAG_L1 to fail during training... Skipping this model.
		System error: Broken pipe
Detailed Traceback:
Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1544, in _train_and_save
    model = self._train_single(X, y, model, X_val, y_val, total_resources=total_resources, **model_fit_kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1485, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, total_resources=total_resources, **model_fit_kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/autogluon/core/models/abstract/abstract_model.py", line 811, in fit
    out = self._fit(**kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py", line 161, in _fit
    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 256, in _fit
    self._fit_folds(X=X, y=y, model_base=model_base, X_pseudo=X_pseudo, y_pseudo=y_pseudo,
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 549, in _fit_folds
    fold_fitting_strategy.after_all_folds_scheduled()
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 529, in after_all_folds_scheduled
    X, y, X_pseudo, y_pseudo = self._prepare_data()
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 747, in _prepare_data
    X = self.ray.put(self.X)
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ray/_private/worker.py", line 2452, in put
    object_ref = worker.put_object(value, owner_address=serialize_owner_address)
  File "/home/ec2-user/anaconda3/envs/pytorch_p310/lib/python3.10/site-packages/ray/_private/worker.py", line 621, in put_object
    self.core_worker.put_serialized_object_and_increment_local_ref(
  File "python/ray/_raylet.pyx", line 1780, in ray._raylet.CoreWorker.put_serialized_object_and_increment_local_ref
  File "python/ray/_raylet.pyx", line 1669, in ray._raylet.CoreWorker._create_put_buffer
  File "python/ray/_raylet.pyx", line 209, in ray._raylet.check_status
ray.exceptions.RaySystemError: System error: Broken pipe
```

**Comment by yinweisu** [comment]
Some user reported pining some dependencies will solve the issue:
`gpustat==1.0.0 and "PyYAML"==6.0, "protobuf"==4.22.3`

**Comment by Innixma** [comment]
Marking as resolved as this hasn't been reported by others, so it may have been fixed. Please create a new GitHub issue if the problem still exists in the latest AutoGluon release.
