### ISSUE TITLE
[BUG] MultiLabelPredictor (Tabular ) runs out of disk space with Local disk is full error

### ISSUE THREAD

**Issue by saraswat40** [autogluon/autogluon#3372]
I am trying to use the Tabular MultiLabelPredictor on a large number of labels (3000 ). I have set presets = ['optimize_for_deployment']. Ray stores fairly large objects in the ray_spilled_directory and eventually the process runs out of disk space. Is this expected?

`Warning: Exception caused XGBoost_BAG_L1 to fail during training... Skipping this model.
		Local disk is full
The object cannot be created because the local object store is full and the local disk's utilization is over capacity (95% by default).Tip: Use `df` on this node to check disk usage and `ray memory` to check object store memory usage.
Detailed Traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/autogluon/core/trainer/abstract_trainer.py", line 1502, in _train_and_save
    model = self._train_single(X, y, model, X_val, y_val, total_resources=total_resources, **model_fit_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/autogluon/core/trainer/abstract_trainer.py", line 1447, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, total_resources=total_resources, **model_fit_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/autogluon/core/models/abstract/abstract_model.py", line 703, in fit
    out = self._fit(**kwargs)
  File "/usr/local/lib/python3.8/dist-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py", line 154, in _fit
    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 248, in _fit
    self._fit_folds(X=X, y=y, model_base=model_base, X_pseudo=X_pseudo, y_pseudo=y_pseudo,
  File "/usr/local/lib/python3.8/dist-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 540, in _fit_folds
    fold_fitting_strategy.after_all_folds_scheduled()
  File "/usr/local/lib/python3.8/dist-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 488, in after_all_folds_scheduled
    X, y, X_pseudo, y_pseudo = self._prepare_data()
  File "/usr/local/lib/python3.8/dist-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 657, in _prepare_data
    X = self.ray.put(self.X)
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/worker.py", line 2375, in put
    object_ref = worker.put_object(value, owner_address=serialize_owner_address)
  File "/usr/local/lib/python3.8/dist-packages/ray/_private/worker.py", line 619, in put_object
    self.core_worker.put_serialized_object_and_increment_local_ref(
  File "python/ray/_raylet.pyx", line 1708, in ray._raylet.CoreWorker.put_serialized_object_and_increment_local_ref
  File "python/ray/_raylet.pyx", line 1597, in ray._raylet.CoreWorker._create_put_buffer
  File "python/ray/_raylet.pyx", line 193, in ray._raylet.check_status
ray.exceptions.OutOfDiskError: Local disk is full
The object cannot be created because the local object store is full and the local disk's utilization is over capacity (95% by default).Tip: Use `df` on this node to check disk usage and `ray memory` to check object store memory usage.
No base models to train on, skipping auxiliary stack level 2...`

Here is a screenshot of the contents of the ray_spilled_objects directory:
![image](https://github.com/autogluon/autogluon/assets/3200933/0e4a4fcf-d546-4285-b5c3-7c26ce567c8e)

Another issue is that this is logged at a 'WARNING' level. It should probably be an 'ERROR' since model training will not continue after this.

**Comment by Innixma** [comment]
MultiLabelPredictor will fit AutoGluon once for each label, so if you have 3000 labels, that is 3000 AutoGluon predictors. This is likely to run out-of-disk for large datasets. I'd recommend using a specialized solution for extreme multi-label problems that is able to scale better than AutoGluon in this case.

I've created #4301 to track the improvement of raising an exception when out-of-disk occurs.
