### ISSUE TITLE
Error with custom model - pickle

### ISSUE THREAD

**Issue by ryan11lee** [autogluon/autogluon#3485]
I am working to build in a custom model. I followed the steps in the documentation as detailed below. 

```python
import numpy as np
import pandas as pd

from autogluon.core.models import AbstractModel
from autogluon.features.generators import LabelEncoderFeatureGenerator

class CustomKernelRidgeModel(AbstractModel):
    def __init__(self, **kwargs):
        # Simply pass along kwargs to parent, and init our internal `_feature_generator` variable to None
        super().__init__(**kwargs)
        self._feature_generator = None

    # The `_preprocess` method takes the input data and transforms it to the internal representation usable by the model.
    # `_preprocess` is called by `preprocess` and is used during model fit and model inference.
    def _preprocess(self, X: pd.DataFrame, is_train=False, **kwargs) -> np.ndarray:
        print(f'Entering the `_preprocess` method: {len(X)} rows of data (is_train={is_train})')
        X = super()._preprocess(X, **kwargs)

        if is_train:
            # X will be the training data.
            self._feature_generator = LabelEncoderFeatureGenerator(verbosity=0)
            self._feature_generator.fit(X=X)
        if self._feature_generator.features_in:
            # This converts categorical features to numeric via stateful label encoding.
            X = X.copy()
            X[self._feature_generator.features_in] = self._feature_generator.transform(X=X)
        # Add a fillna call to handle missing values.
        # Some algorithms will be able to handle NaN values internally (LightGBM).
        # In those cases, you can simply pass the NaN values into the inner model.
        # Finally, convert to numpy for optimized memory usage and because sklearn RF works with raw numpy input.
        return X.fillna(0).to_numpy(dtype=np.float32)

    # The `_fit` method takes the input training data (and optionally the validation data) and trains the model.
    def _fit(self,
             X: pd.DataFrame,  # training data
             y: pd.Series,  # training labels
             # X_val=None,  # val data (unused in RF model)
             # y_val=None,  # val labels (unused in RF model)
             # time_limit=None,  # time limit in seconds (ignored in tutorial)
             **kwargs):  # kwargs includes many other potential inputs, refer to AbstractModel documentation for details
        print('Entering the `_fit` method')

        # First we import the required dependencies for the model. Note that we do not import them outside of the method.
        # This enables AutoGluon to be highly extensible and modular.
        # For an example of best practices when importing model dependencies, refer to LGBModel.
        from sklearn.kernel_ridge import KernelRidge


        # Valid self.problem_type values include ['binary', 'multiclass', 'regression', 'quantile', 'softclass']
        if self.problem_type in ['regression']:
            model_cls = KernelRidge


        # Make sure to call preprocess on X near the start of `_fit`.
        # This is necessary because the data is converted via preprocess during predict, and needs to be in the same format as during fit.
        X = self.preprocess(X, is_train=True)
        # This fetches the user-specified (and default) hyperparameters for the model.
        params = self._get_model_params()
        print(f'Hyperparameters: {params}')
        # self.model should be set to the trained inner model, so that internally during predict we can call `self.model.predict(...)`
        self.model = model_cls(**params)
        self.model.fit(X, y)
        print('Exiting the `_fit` method')

    # The `_set_default_params` method defines the default hyperparameters of the model.
    # User-specified parameters will override these values on a key-by-key basis.
    def _set_default_params(self):
        default_params = {"alpha":1e-05, 
                          "gamma":0.05, 
                          "kernel":'cosine', 
                          "degree":1, 
                          "coef0":0.05
        }
        for param, val in default_params.items():
            self._set_default_param_value(param, val)

    # The `_get_default_auxiliary_params` method defines various model-agnostic parameters such as maximum memory usage and valid input column dtypes.
    # For most users who build custom models, they will only need to specify the valid/invalid dtypes to the model here.
    def _get_default_auxiliary_params(self) -> dict:
        default_auxiliary_params = super()._get_default_auxiliary_params()
        extra_auxiliary_params = dict(
            get_features_kwargs=dict(
                # the total set of raw dtypes are: ['int', 'float', 'category', 'object', 'datetime']
                # object feature dtypes include raw text and image paths, which should only be handled by specialized models
                # datetime raw dtypes are generally converted to int in upstream pre-processing,
                # so models generally shouldn't need to explicitly support datetime dtypes.
                valid_raw_types=['int', 'float', 'category'],
            ),
        )
        default_auxiliary_params.update(extra_auxiliary_params)
        return default_auxiliary_params

```

Tabular predictor works when we add the custom model with tuned hyperparameters to be trained alongside the default models, however when I turn on "best_quality' as I want to include the model in the multilayer stack ensembling I get the following error: 

 ```
Fitting model: CustomKernelRidgeModel_BAG_L1 ...
	Fitting 5 child models (S1F1 - S1F5) | Fitting with ParallelLocalFoldFittingStrategy
	Warning: Exception caused CustomKernelRidgeModel_BAG_L1 to fail during training... Skipping this model.
		ray::_ray_fit() (pid=238613, ip=172.30.0.9)
  File "/home/user/miniconda3/envs/multivariate/lib/python3.10/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 406, in _ray_fit
    save_path = fold_model.save()
  File "/home/user/miniconda3/envs/multivariate/lib/python3.10/site-packages/autogluon/core/models/abstract/abstract_model.py", line 1026, in save
    save_pkl.save(path=file_path, object=self, verbose=verbose)
  File "/home/user/miniconda3/envs/multivariate/lib/python3.10/site-packages/autogluon/common/savers/save_pkl.py", line 27, in save
    save_with_fn(validated_path, object, pickle_fn, format=format, verbose=verbose, compression_fn=compression_fn, compression_fn_kwargs=compression_fn_kwargs)
  File "/home/user/miniconda3/envs/multivariate/lib/python3.10/site-packages/autogluon/common/savers/save_pkl.py", line 47, in save_with_fn
    pickle_fn(object, fout)
  File "/home/user/miniconda3/envs/multivariate/lib/python3.10/site-packages/autogluon/common/savers/save_pkl.py", line 25, in pickle_fn
    return pickle.dump(o, buffer, protocol=4)
_pickle.PicklingError: Can't pickle <class '__main__.CustomKernelRidgeModel'>: attribute lookup CustomKernelRidgeModel on __main__ failed
Detailed Traceback:
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/multivariate/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1733, in _train_and_save
    model = self._train_single(X, y, model, X_val, y_val, total_resources=total_resources, **model_fit_kwargs)
  File "/home/ryanlee/miniconda3/envs/multivariate/lib/python3.10/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1684, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, total_resources=total_resources, **model_fit_kwargs)
  File "/home/ryanlee/miniconda3/envs/multivariate/lib/python3.10/site-packages/autogluon/core/models/abstract/abstract_model.py", line 829, in fit
    out = self._fit(**kwargs)
  File "/home/user/miniconda3/envs/multivariate/lib/python3.10/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py", line 169, in _fit
    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)
  File "/home/user/miniconda3/envs/multivariate/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 266, in _fit
    self._fit_folds(
  File "/home/user/miniconda3/envs/multivariate/lib/python3.10/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 592, in _fit_folds
    fold_fitting_strategy.after_all_folds_scheduled()
  File "/home/user/miniconda3/envs/multivariate/lib/python3.10/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 581, in after_all_folds_scheduled
    raise processed_exception
  File "/home/user/miniconda3/envs/multivariate/lib/python3.10/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 541, in after_all_folds_scheduled
    fold_model, pred_proba, time_start_fit, time_end_fit, predict_time, predict_1_time = self.ray.get(finished)
  File "/home/ryanlee/miniconda3/envs/multivariate/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 105, in wrapper
    return func(*args, **kwargs)
  File "/home/user/miniconda3/envs/multivariate/lib/python3.10/site-packages/ray/_private/worker.py", line 2380, in get
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(PicklingError): ray::_ray_fit() (pid=238613, ip=172.30.0.9)
  File "/home/user/miniconda3/envs/multivariate/lib/python3.10/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 406, in _ray_fit
    save_path = fold_model.save()
  File "/home/user/miniconda3/envs/multivariate/lib/python3.10/site-packages/autogluon/core/models/abstract/abstract_model.py", line 1026, in save
    save_pkl.save(path=file_path, object=self, verbose=verbose)
  File "/home/ryanlee/miniconda3/envs/multivariate/lib/python3.10/site-packages/autogluon/common/savers/save_pkl.py", line 27, in save
    save_with_fn(validated_path, object, pickle_fn, format=format, verbose=verbose, compression_fn=compression_fn, compression_fn_kwargs=compression_fn_kwargs)
  File "/home/user/miniconda3/envs/multivariate/lib/python3.10/site-packages/autogluon/common/savers/save_pkl.py", line 47, in save_with_fn
    pickle_fn(object, fout)
  File "/home/user/miniconda3/envs/multivariate/lib/python3.10/site-packages/autogluon/common/savers/save_pkl.py", line 25, in pickle_fn
    return pickle.dump(o, buffer, protocol=4)
_pickle.PicklingError: Can't pickle <class '__main__.CustomKernelRidgeModel'>: attribute lookup CustomKernelRidgeModel on __main__ failed

```

**Comment by ryan11lee** [comment]
https://github.com/autogluon/autogluon/issues/2438 solved it for me
