### ISSUE TITLE
[BUG]fit MultiModals on linux，load model on win10

### ISSUE THREAD

**Issue by doraemonlei** [autogluon/autogluon#3531]
loda model on linux, no bug:
`/root/anaconda3/envs/env_autogluon0.7/lib/python3.9/site-packages/torch/functional.py:504: UserWarning: torch.meshgrid: in an upcoming release, it will be required to pass the indexing argument. (Triggered internally at /home/conda/feedstock_root/build_artifacts/pytorch-recipe_1673738523684/work/aten/src/ATen/native/TensorShape.cpp:3190.)
  return _VF.meshgrid(tensors, **kwargs)  # type: ignore[attr-defined]
Load pretrained checkpoint: /root/workspace/chenfeibing_code/MultiModals_fra08_fiveRatio_5610Samples_SixHoursTimeLimit/model.ckpt`

loda on win10:
`RuntimeError: Error(s) in loading state_dict for TimmAutoModelForImagePrediction:
        Unexpected key(s) in state_dict: "model.layers.0.blocks.0.attn.relative_position_index", 
"model.layers.0.blocks.1.attn_mask", "model.layers.0.blocks.1.attn.relative_position_index", 
"model.layers.1.blocks.0.attn.relative_position_index", "model.layers.1.blocks.1.attn_mask", 
"model.layers.1.blocks.1.attn.relative_position_index", "model.layers.2.blocks.0.attn.relative_position_index", 
"model.layers.2.blocks.1.attn_mask", "model.layers.2.blocks.1.attn.relative_position_index", 
"model.layers.2.blocks.2.attn.relative_position_index", "model.layers.2.blocks.3.attn_mask", 
"model.layers.2.blocks.3.attn.relative_position_index", "model.layers.2.blocks.4.attn.relative_position_index", 
"model.layers.2.blocks.5.attn_mask", "model.layers.2.blocks.5.attn.relative_position_index", 
"model.layers.2.blocks.6.attn.relative_position_index", "model.layers.2.blocks.7.attn_mask", 
"model.layers.2.blocks.7.attn.relative_position_index", "model.layers.2.blocks.8.attn.relative_position_index", 
"model.layers.2.blocks.9.attn_mask", "model.layers.2.blocks.9.attn.relative_position_index", 
"model.layers.2.blocks.10.attn.relative_position_index", "model.layers.2.blocks.11.attn_mask", 
"model.layers.2.blocks.11.attn.relative_position_index", "model.layers.2.blocks.12.attn.relative_position_index", 
"model.layers.2.blocks.13.attn_mask", "model.layers.2.blocks.13.attn.relative_position_index", 
"model.layers.2.blocks.14.attn.relative_position_index", "model.layers.2.blocks.15.attn_mask", 
"model.layers.2.blocks.15.attn.relative_position_index", "model.layers.2.blocks.16.attn.relative_position_index", 
"model.layers.2.blocks.17.attn_mask", "model.layers.2.blocks.17.attn.relative_position_index", 
"model.layers.3.blocks.0.attn.relative_position_index", "model.layers.3.blocks.1.attn.relative_position_index". `

**Comment by tonyhoo** [comment]
Thanks for reporting the issue. Can you provide version details for both linux and win10 environments? You can run following codes on both platform and paste the output here:

```
from autogluon.core.utils import show_versions
show_versions()
```

**Comment by celise88** [comment]
I'm having a similar issue trying to use HPO (text classification task).  It seems to be occurring after the HPO process is complete and it is attempting to arrive at the final model (see traceback below).  I am running on a macOS with m1 chip. 

Removing non-optimal trials and only keep the best one.
Start to fuse 3 checkpoints via the greedy soup algorithm.
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/caitlinlahuis/Documents/MyPythonLibs/SIOPMLC2024/.venv/lib/python3.10/site-packages/autogluon/multimodal/predictor.py", line 518, in fit
    self._learner.fit(
  File "/Users/caitlinlahuis/Documents/MyPythonLibs/SIOPMLC2024/.venv/lib/python3.10/site-packages/autogluon/multimodal/learners/base.py", line 655, in fit
    fit_returns = self.execute_fit()
  File "/Users/caitlinlahuis/Documents/MyPythonLibs/SIOPMLC2024/.venv/lib/python3.10/site-packages/autogluon/multimodal/learners/base.py", line 560, in execute_fit
    hyperparameter_tune(
  File "/Users/caitlinlahuis/Documents/MyPythonLibs/SIOPMLC2024/.venv/lib/python3.10/site-packages/autogluon/multimodal/utils/hpo.py", line 225, in hyperparameter_tune
    learner = build_final_learner(
  File "/Users/caitlinlahuis/Documents/MyPythonLibs/SIOPMLC2024/.venv/lib/python3.10/site-packages/autogluon/multimodal/utils/hpo.py", line 121, in build_final_learner
    learner.top_k_average(
  File "/Users/caitlinlahuis/Documents/MyPythonLibs/SIOPMLC2024/.venv/lib/python3.10/site-packages/autogluon/multimodal/learners/base.py", line 1402, in top_k_average
    self._load_state_dict(
  File "/Users/caitlinlahuis/Documents/MyPythonLibs/SIOPMLC2024/.venv/lib/python3.10/site-packages/autogluon/multimodal/learners/base.py", line 2119, in _load_state_dict
    load_result = self._model.load_state_dict(state_dict, strict=strict)
  File "/Users/caitlinlahuis/Documents/MyPythonLibs/SIOPMLC2024/.venv/lib/python3.10/site-packages/torch/nn/modules/module.py", line 2041, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for HFAutoModelForTextPrediction:
        Missing key(s) in state_dict: "model.embeddings.word_embeddings.weight", "model.embeddings.position_embeddings.weight", "model.embeddings.token_type_embeddings.weight", "model.embeddings.LayerNorm.weight", "model.encoder.layer.0.attention.self.query.weight", "model.encoder.layer.0.attention.self.key.weight", "model.encoder.layer.0.attention.self.value.weight", "model.encoder.layer.0.attention.output.dense.weight", "model.encoder.layer.0.attention.output.LayerNorm.weight", "model.encoder.layer.0.intermediate.dense.weight", "model.encoder.layer.0.output.dense.weight", "model.encoder.layer.0.output.LayerNorm.weight", "model.encoder.layer.1.attention.self.query.weight", "model.encoder.layer.1.attention.self.key.weight", "model.encoder.layer.1.attention.self.value.weight", "model.encoder.layer.1.attention.output.dense.weight", "model.encoder.layer.1.attention.output.LayerNorm.weight", "model.encoder.layer.1.intermediate.dense.weight", "model.encoder.layer.1.output.dense.weight", "model.encoder.layer.1.output.LayerNorm.weight", "model.encoder.layer.2.attention.self.query.weight", "model.encoder.layer.2.attention.self.key.weight", "model.encoder.layer.2.attention.self.value.weight", "model.encoder.layer.2.attention.output.dense.weight", "model.encoder.layer.2.attention.output.LayerNorm.weight", "model.encoder.layer.2.intermediate.dense.weight", "model.encoder.layer.2.output.dense.weight", "model.encoder.layer.2.output.LayerNorm.weight", "model.encoder.layer.3.attention.self.query.weight", "model.encoder.layer.3.attention.self.key.weight", "model.encoder.layer.3.attention.self.value.weight", "model.encoder.layer.3.attention.output.dense.weight", "model.encoder.layer.3.attention.output.LayerNorm.weight", "model.encoder.layer.3.intermediate.dense.weight", "model.encoder.layer.3.output.dense.weight", "model.encoder.layer.3.output.LayerNorm.weight", "model.encoder.layer.4.attention.self.query.weight", "model.encoder.layer.4.attention.self.key.weight", "model.encoder.layer.4.attention.self.value.weight", "model.encoder.layer.4.attention.output.dense.weight", "model.encoder.layer.4.attention.output.LayerNorm.weight", "model.encoder.layer.4.intermediate.dense.weight", "model.encoder.layer.4.output.dense.weight", "model.encoder.layer.4.output.LayerNorm.weight", "model.encoder.layer.5.attention.self.query.weight", "model.encoder.layer.5.attention.self.key.weight", "model.encoder.layer.5.attention.self.value.weight", "model.encoder.layer.5.attention.output.dense.weight", "model.encoder.layer.5.attention.output.LayerNorm.weight", "model.encoder.layer.5.intermediate.dense.weight", "model.encoder.layer.5.output.dense.weight", "model.encoder.layer.5.output.LayerNorm.weight", "model.encoder.layer.6.attention.self.query.weight", "model.encoder.layer.6.attention.self.key.weight", "model.encoder.layer.6.attention.self.value.weight", "model.encoder.layer.6.attention.output.dense.weight", "model.encoder.layer.6.attention.output.LayerNorm.weight", "model.encoder.layer.6.intermediate.dense.weight", "model.encoder.layer.6.output.dense.weight", "model.encoder.layer.6.output.LayerNorm.weight", "model.encoder.layer.7.attention.self.query.weight", "model.encoder.layer.7.attention.self.key.weight", "model.encoder.layer.7.attention.self.value.weight", "model.encoder.layer.7.attention.output.dense.weight", "model.encoder.layer.7.attention.output.LayerNorm.weight", "model.encoder.layer.7.intermediate.dense.weight", "model.encoder.layer.7.output.dense.weight", "model.encoder.layer.7.output.LayerNorm.weight", "model.encoder.layer.8.attention.self.query.weight", "model.encoder.layer.8.attention.self.key.weight", "model.encoder.layer.8.attention.self.value.weight", "model.encoder.layer.8.attention.output.dense.weight", "model.encoder.layer.8.attention.output.LayerNorm.weight", "model.encoder.layer.8.intermediate.dense.weight", "model.encoder.layer.8.output.dense.weight", "model.encoder.layer.8.output.LayerNorm.weight", "model.encoder.layer.9.attention.self.query.weight", "model.encoder.layer.9.attention.self.key.weight", "model.encoder.layer.9.attention.self.value.weight", "model.encoder.layer.9.attention.output.dense.weight", "model.encoder.layer.9.attention.output.LayerNorm.weight", "model.encoder.layer.9.intermediate.dense.weight", "model.encoder.layer.9.output.dense.weight", "model.encoder.layer.9.output.LayerNorm.weight", "model.encoder.layer.10.attention.self.query.weight", "model.encoder.layer.10.attention.self.key.weight", "model.encoder.layer.10.attention.self.value.weight", "model.encoder.layer.10.attention.output.dense.weight", "model.encoder.layer.10.attention.output.LayerNorm.weight", "model.encoder.layer.10.intermediate.dense.weight", "model.encoder.layer.10.output.dense.weight", "model.encoder.layer.10.output.LayerNorm.weight", "model.encoder.layer.11.attention.self.query.weight", "model.encoder.layer.11.attention.self.key.weight", "model.encoder.layer.11.attention.self.value.weight", "model.encoder.layer.11.attention.output.dense.weight", "model.encoder.layer.11.attention.output.LayerNorm.weight", "model.encoder.layer.11.intermediate.dense.weight", "model.encoder.layer.11.output.dense.weight", "model.encoder.layer.11.output.LayerNorm.weight", "model.encoder.layer.12.attention.self.query.weight", "model.encoder.layer.12.attention.self.key.weight", "model.encoder.layer.12.attention.self.value.weight", "model.encoder.layer.12.attention.output.dense.weight", "model.encoder.layer.12.attention.output.LayerNorm.weight", "model.encoder.layer.12.intermediate.dense.weight", "model.encoder.layer.12.output.dense.weight", "model.encoder.layer.12.output.LayerNorm.weight", "model.encoder.layer.13.attention.self.query.weight", "model.encoder.layer.13.attention.self.key.weight", "model.encoder.layer.13.attention.self.value.weight", "model.encoder.layer.13.attention.output.dense.weight", "model.encoder.layer.13.attention.output.LayerNorm.weight", "model.encoder.layer.13.intermediate.dense.weight", "model.encoder.layer.13.output.dense.weight", "model.encoder.layer.13.output.LayerNorm.weight", "model.encoder.layer.14.attention.self.query.weight", "model.encoder.layer.14.attention.self.key.weight", "model.encoder.layer.14.attention.self.value.weight", "model.encoder.layer.14.attention.output.dense.weight", "model.encoder.layer.14.attention.output.LayerNorm.weight", "model.encoder.layer.14.intermediate.dense.weight", "model.encoder.layer.14.output.dense.weight", "model.encoder.layer.14.output.LayerNorm.weight", "model.encoder.layer.15.attention.self.query.weight", "model.encoder.layer.15.attention.self.key.weight", "model.encoder.layer.15.attention.self.value.weight", "model.encoder.layer.15.attention.output.dense.weight", "model.encoder.layer.15.attention.output.LayerNorm.weight", "model.encoder.layer.15.intermediate.dense.weight", "model.encoder.layer.15.output.dense.weight", "model.encoder.layer.15.output.LayerNorm.weight", "model.encoder.layer.16.attention.self.query.weight", "model.encoder.layer.16.attention.self.key.weight", "model.encoder.layer.16.attention.self.value.weight", "model.encoder.layer.16.attention.output.dense.weight", "model.encoder.layer.16.attention.output.LayerNorm.weight", "model.encoder.layer.16.intermediate.dense.weight", "model.encoder.layer.16.output.dense.weight", "model.encoder.layer.16.output.LayerNorm.weight", "model.encoder.layer.17.attention.self.query.weight", "model.encoder.layer.17.attention.self.key.weight", "model.encoder.layer.17.attention.self.value.weight", "model.encoder.layer.17.attention.output.dense.weight", "model.encoder.layer.17.attention.output.LayerNorm.weight", "model.encoder.layer.17.intermediate.dense.weight", "model.encoder.layer.17.output.dense.weight", "model.encoder.layer.17.output.LayerNorm.weight", "model.encoder.layer.18.attention.self.query.weight", "model.encoder.layer.18.attention.self.key.weight", "model.encoder.layer.18.attention.self.value.weight", "model.encoder.layer.18.attention.output.dense.weight", "model.encoder.layer.18.attention.output.LayerNorm.weight", "model.encoder.layer.18.intermediate.dense.weight", "model.encoder.layer.18.output.dense.weight", "model.encoder.layer.18.output.LayerNorm.weight", "model.encoder.layer.19.attention.self.query.weight", "model.encoder.layer.19.attention.self.key.weight", "model.encoder.layer.19.attention.self.value.weight", "model.encoder.layer.19.attention.output.dense.weight", "model.encoder.layer.19.attention.output.LayerNorm.weight", "model.encoder.layer.19.intermediate.dense.weight", "model.encoder.layer.19.output.dense.weight", "model.encoder.layer.19.output.LayerNorm.weight", "model.encoder.layer.20.attention.self.query.weight", "model.encoder.layer.20.attention.self.key.weight", "model.encoder.layer.20.attention.self.value.weight", "model.encoder.layer.20.attention.output.dense.weight", "model.encoder.layer.20.attention.output.LayerNorm.weight", "model.encoder.layer.20.intermediate.dense.weight", "model.encoder.layer.20.output.dense.weight", "model.encoder.layer.20.output.LayerNorm.weight", "model.encoder.layer.21.attention.self.query.weight", "model.encoder.layer.21.attention.self.key.weight", "model.encoder.layer.21.attention.self.value.weight", "model.encoder.layer.21.attention.output.dense.weight", "model.encoder.layer.21.attention.output.LayerNorm.weight", "model.encoder.layer.21.intermediate.dense.weight", "model.encoder.layer.21.output.dense.weight", "model.encoder.layer.21.output.LayerNorm.weight", "model.encoder.layer.22.attention.self.query.weight", "model.encoder.layer.22.attention.self.key.weight", "model.encoder.layer.22.attention.self.value.weight", "model.encoder.layer.22.attention.output.dense.weight", "model.encoder.layer.22.attention.output.LayerNorm.weight", "model.encoder.layer.22.intermediate.dense.weight", "model.encoder.layer.22.output.dense.weight", "model.encoder.layer.22.output.LayerNorm.weight", "model.encoder.layer.23.attention.self.query.weight", "model.encoder.layer.23.attention.self.key.weight", "model.encoder.layer.23.attention.self.value.weight", "model.encoder.layer.23.attention.output.dense.weight", "model.encoder.layer.23.attention.output.LayerNorm.weight", "model.encoder.layer.23.intermediate.dense.weight", "model.encoder.layer.23.output.dense.weight", "model.encoder.layer.23.output.LayerNorm.weight". 


I ran what you suggested above and here is the output: 

INSTALLED VERSIONS
------------------
date                   : 2024-02-25
time                   : 18:44:31.809476
python                 : 3.10.13.final.0
OS                     : Darwin
OS-release             : 21.6.0
Version                : Darwin Kernel Version 21.6.0: Fri Sep 15 16:17:13 PDT 2023; root:xnu-8020.240.18.703.5~1/RELEASE_ARM64_T8101
machine                : arm64
processor              : arm
num_cores              : 8
cpu_ram_mb             : 16384.0
cuda version           : None
num_gpus               : 0
gpu_ram_mb             : []
avail_disk_size_mb     : 119929

accelerate             : 0.21.0
async-timeout          : 4.0.3
autogluon              : 1.0.0
autogluon.common       : 1.0.0
autogluon.core         : 1.0.0
autogluon.features     : 1.0.0
autogluon.multimodal   : 1.0.0
autogluon.tabular      : 1.0.0
autogluon.timeseries   : 1.0.0
boto3                  : 1.34.49
catboost               : 1.1.1
defusedxml             : 0.7.1
evaluate               : 0.4.1
fastai                 : 2.7.14
gluonts                : 0.14.4
hyperopt               : 0.2.7
imodels                : None
jinja2                 : 3.1.3
joblib                 : 1.3.2
jsonschema             : 4.17.3
lightgbm               : 4.1.0
lightning              : 2.0.9.post0
matplotlib             : 3.8.3
mlforecast             : 0.10.0
networkx               : 3.2.1
nlpaug                 : 1.1.11
nltk                   : 3.8.1
nptyping               : 2.4.1
numpy                  : 1.26.4
nvidia-ml-py3          : 7.352.0
omegaconf              : 2.2.3
onnxruntime-gpu        : None
openmim                : 0.3.9
orjson                 : 3.9.15
pandas                 : 2.1.4
Pillow                 : 10.2.0
psutil                 : 5.9.5
PyMuPDF                : None
pytesseract            : 0.3.10
pytorch-lightning      : 2.0.9.post0
pytorch-metric-learning: 1.7.3
ray                    : 2.6.3
requests               : 2.28.2
scikit-image           : 0.20.0
scikit-learn           : 1.4.1.post1
scikit-learn-intelex   : None
scipy                  : 1.12.0
seqeval                : 1.2.2
setuptools             : 60.2.0
skl2onnx               : None
statsforecast          : 1.4.0
statsmodels            : 0.14.1
tabpfn                 : None
tensorboard            : 2.15.2
text-unidecode         : 1.3
timm                   : 0.9.16
torch                  : 2.0.1
torchmetrics           : 1.1.2
torchvision            : 0.15.2
tqdm                   : 4.65.2
transformers           : 4.31.0
utilsforecast          : 0.0.10
vowpalwabbit           : None
xgboost                : 2.0.3
