### ISSUE TITLE
[BUG] Training Failure for TimeSeries Models 'DeepAR' and 'PatchTST' on a Fresh Environment

### ISSUE THREAD

**Issue by obwohl** [autogluon/autogluon#3534]
**Description:**
After installing AutoGluon in a fresh environment, I attempted to train TimeSeries models 'DeepAR' and 'PatchTST'. However, both models failed during training due to NotImplementedError for certain operators ('aten::_standard_gamma' and 'aten::lgamma.out') for the MPS device. 

**Steps to Reproduce:**
1. Install AutoGluon in a fresh environment.
2. Attempt to train TimeSeries models 'DeepAR' and 'PatchTST'.

**Expected Behavior:**
The models should be trained successfully without any errors.

**Actual Behavior:**
The training process fails with NotImplementedError for 'aten::_standard_gamma' and 'aten::lgamma.out' operators for the MPS device.

**Error Messages:**
For 'DeepAR' model:
`NotImplementedError: The operator 'aten::_standard_gamma' is not currently implemented for the MPS device.`

For 'PatchTST' model:
`NotImplementedError: The operator 'aten::lgamma.out' is not currently implemented for the MPS device.`

**Environment:**
- AutoGluon version: 0.8.2
- Operating System: MacOS 13.5.2 (22G91)
- Python version: 3.10

**Training Output ("USERNAME" is filled in for privacy reasons)**
Starting training. Start time is 2023-09-18 15:44:10
Saving ./AutogluonModels/2023-09-18 15:44Pr1Val1Win10Qhigh_quality/utils/data/train.pkl
Models that will be trained: ['DeepAR', 'PatchTST']
Training timeseries model DeepAR. 
	Fitting DeepAR with 'num_gpus': 0, 'num_cpus': 12
	Window 0
GluonTS logging is turned on during training. Note that losses reported by GluonTS may not correspond to those specified via `eval_metric`.
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: AutogluonModels/2023-09-18 15:44Pr1Val1Win10Qhigh_quality/models/DeepAR/W0/lightning_logs
	Warning: Exception caused DeepAR to fail during training... Skipping this model.
	The operator 'aten::_standard_gamma' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.
Traceback (most recent call last):
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/autogluon/timeseries/trainer/abstract_trainer.py", line 483, in _train_and_save
    model = self._train_single(train_data, model, val_data=val_data, time_limit=time_limit)
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/autogluon/timeseries/trainer/abstract_trainer.py", line 396, in _train_single
    model.fit(
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/autogluon/timeseries/models/abstract/abstract_timeseries_model.py", line 232, in fit
    return super().fit(**kwargs)
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/autogluon/core/models/abstract/abstract_model.py", line 838, in fit
    out = self._fit(**kwargs)
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/autogluon/timeseries/models/multi_window/multi_window_model.py", line 97, in _fit
    model.fit(
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/autogluon/timeseries/models/abstract/abstract_timeseries_model.py", line 232, in fit
    return super().fit(**kwargs)
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/autogluon/core/models/abstract/abstract_model.py", line 838, in fit
    out = self._fit(**kwargs)
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/autogluon/timeseries/models/gluonts/abstract_gluonts.py", line 361, in _fit
    self.gts_predictor = estimator.train(
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/gluonts/torch/model/estimator.py", line 237, in train
    return self.train_model(
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/gluonts/torch/model/estimator.py", line 205, in train_model
    trainer.fit(
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 532, in fit
    call._call_and_handle_interrupt(
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 571, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 960, in _run
    call._call_callback_hooks(self, "on_fit_start")
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 195, in _call_callback_hooks
    fn(trainer, trainer.lightning_module, *args, **kwargs)
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/pytorch_lightning/callbacks/model_summary.py", line 59, in on_fit_start
    model_summary = self._summary(trainer, pl_module)
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/pytorch_lightning/callbacks/model_summary.py", line 73, in _summary
    return summarize(pl_module, max_depth=self._max_depth)
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/pytorch_lightning/utilities/model_summary/model_summary.py", line 436, in summarize
    return ModelSummary(lightning_module, max_depth=max_depth)
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/pytorch_lightning/utilities/model_summary/model_summary.py", line 192, in __init__
    self._layer_summary = self.summarize()
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/pytorch_lightning/utilities/model_summary/model_summary.py", line 249, in summarize
    self._forward_example_input()
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/pytorch_lightning/utilities/model_summary/model_summary.py", line 279, in _forward_example_input
    model(**input_)
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/gluonts/torch/model/deepar/lightning_module.py", line 68, in forward
    return self.model(*args, **kwargs)
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1538, in _call_impl
    result = forward_call(*args, **kwargs)
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/gluonts/torch/model/deepar/module.py", line 427, in forward
    next_sample = distr.sample()
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/torch/distributions/transformed_distribution.py", line 119, in sample
    x = self.base_dist.sample(sample_shape)
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/torch/distributions/distribution.py", line 158, in sample
    return self.rsample(sample_shape)
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/torch/distributions/studentT.py", line 77, in rsample
    Z = self._chi2.rsample(sample_shape)
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/torch/distributions/gamma.py", line 67, in rsample
    value = _standard_gamma(self.concentration.expand(shape)) / self.rate.expand(shape)
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/torch/distributions/gamma.py", line 11, in _standard_gamma
    return torch._standard_gamma(concentration)
NotImplementedError: The operator 'aten::_standard_gamma' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.

Training timeseries model PatchTST. 
	Fitting PatchTST with 'num_gpus': 0, 'num_cpus': 12
	Window 0
GluonTS logging is turned on during training. Note that losses reported by GluonTS may not correspond to those specified via `eval_metric`.
GPU available: True (mps), used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
HPU available: False, using: 0 HPUs
Missing logger folder: AutogluonModels/2023-09-18 15:44Pr1Val1Win10Qhigh_quality/models/PatchTST/W0/lightning_logs

  | Name  | Type          | Params
----------------------------------------
0 | model | PatchTSTModel | 38.9 K
----------------------------------------
38.5 K    Trainable params
384       Non-trainable params
38.9 K    Total params
0.156     Total estimated model params size (MB)
	Warning: Exception caused PatchTST to fail during training... Skipping this model.
	The operator 'aten::lgamma.out' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.
Traceback (most recent call last):
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/autogluon/timeseries/trainer/abstract_trainer.py", line 483, in _train_and_save
    model = self._train_single(train_data, model, val_data=val_data, time_limit=time_limit)
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/autogluon/timeseries/trainer/abstract_trainer.py", line 396, in _train_single
    model.fit(
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/autogluon/timeseries/models/abstract/abstract_timeseries_model.py", line 232, in fit
    return super().fit(**kwargs)
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/autogluon/core/models/abstract/abstract_model.py", line 838, in fit
    out = self._fit(**kwargs)
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/autogluon/timeseries/models/multi_window/multi_window_model.py", line 97, in _fit
    model.fit(
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/autogluon/timeseries/models/abstract/abstract_timeseries_model.py", line 232, in fit
    return super().fit(**kwargs)
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/autogluon/core/models/abstract/abstract_model.py", line 838, in fit
    out = self._fit(**kwargs)
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/autogluon/timeseries/models/gluonts/abstract_gluonts.py", line 361, in _fit
    self.gts_predictor = estimator.train(
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/gluonts/torch/model/estimator.py", line 237, in train
    return self.train_model(
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/gluonts/torch/model/estimator.py", line 205, in train_model
    trainer.fit(
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 532, in fit
    call._call_and_handle_interrupt(
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 43, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 571, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 980, in _run
    results = self._run_stage()
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1021, in _run_stage
    self._run_sanity_check()
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/pytorch_lightning/trainer/trainer.py", line 1050, in _run_sanity_check
    val_loop.run()
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/pytorch_lightning/loops/utilities.py", line 181, in _decorator
    return loop_run(self, *args, **kwargs)
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 115, in run
    self._evaluation_step(batch, batch_idx, dataloader_idx)
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/pytorch_lightning/loops/evaluation_loop.py", line 376, in _evaluation_step
    output = call._call_strategy_hook(trainer, hook_name, *step_kwargs.values())
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/pytorch_lightning/trainer/call.py", line 294, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/pytorch_lightning/strategies/strategy.py", line 393, in validation_step
    return self.model.validation_step(*args, **kwargs)
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/gluonts/torch/model/patch_tst/lightning_module.py", line 95, in validation_step
    val_loss = self._compute_loss(batch)
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/gluonts/torch/model/patch_tst/lightning_module.py", line 74, in _compute_loss
    self.loss(distr, target) * observed_target
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/gluonts/torch/modules/loss.py", line 69, in __call__
    nll = -input.log_prob(target)
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/torch/distributions/transformed_distribution.py", line 153, in log_prob
    log_prob = log_prob + _sum_rightmost(self.base_dist.log_prob(y),
  File "/Users/USERNAME/anaconda3/envs/ag/lib/python3.10/site-packages/torch/distributions/studentT.py", line 88, in log_prob
    torch.lgamma(0.5 * self.df) -
NotImplementedError: The operator 'aten::lgamma.out' is not currently implemented for the MPS device. If you want this op to be added in priority during the prototype phase of this feature, please comment on https://github.com/pytorch/pytorch/issues/77764. As a temporary fix, you can set the environment variable `PYTORCH_ENABLE_MPS_FALLBACK=1` to use the CPU as a fallback for this op. WARNING: this will be slower than running natively on MPS.

Not fitting ensemble as no models were successfully trained.
Training complete. Models trained: []
Total runtime: 0.69 s
Trainer has no fit models that can predict.
Saving ./AutogluonModels/2023-09-18 15:44Pr1Val1Win10Qhigh_quality/models/trainer.pkl
Saving ./AutogluonModels/2023-09-18 15:44Pr1Val1Win10Qhigh_quality/predictor.pkl
<autogluon.timeseries.predictor.TimeSeriesPredictor at 0x17da35780>

**Comment by shchur** [comment]
Thank you for the bug report!

Could you try disabling the MPS backend with the following code?
```python
import os
os.environ["PYTORCH_ENABLE_MPS_FALLBACK"] = "1"

from autogluon.timeseries import TimeSeriesPredictor
predictor = TimeSeriesPredictor(...).fit(...)
```

**Comment by obwohl** [comment]
Ok, i did that, but it does not help.

**Comment by shchur** [comment]
Could you try setting this environmental variable before calling the Python script, e.g.
```bash
export PYTORCH_ENABLE_MPS_FALLBACK=1

python train_autogluon.py
```
where `train_autogluon.py` is the script that contains the training logic?

**Comment by obwohl** [comment]
that worked! i am working in jupyter lab and adding 
import os
os.environ["PYTORCH_ENABLE_MPS_FALLBACK"] = "1"

as first cell after restarting the kernel did the job. thanks!
