### ISSUE TITLE
[BUG] TensorRT 

### ISSUE THREAD

**Issue by tonyhoo** [autogluon/autogluon#3538]
**Bug Report Checklist**

- [x] I have provided code that demonstrates a minimal reproducible example.
- [x] I have confirmed the bug exists on the latest mainline of AutoGluon via a source install.

**Describe the bug**
I have a Python script using AutoGluon with Pytorch for training a model and TensorRT for inference speedup. This script works fine on a single A100 GPU but it fails when run on multiple GPUs. An error, `AssertionError: Gather function not implemented for CPU tensors`, is raised during the optimization for inference step in the Autogluon's MultiModalPredictor.

**Expected behavior**
The script should run without errors and complete the training and inference tasks successfully even on multiple GPUs.

**To Reproduce**
The script that reproduces the issue is provided in the original Github issue.
```python
import os
import numpy as np
import time
import warnings
import pandas as pd
from autogluon.core.utils.loaders import load_zip
from autogluon.multimodal import MultiModalPredictor
improt torch

if __name__ == '__main__':

    warnings.filterwarnings('ignore')
    np.random.seed(123)

    # Check if GPUs are available
    if torch.cuda.is_available():
        # Get the number of available GPUs
        num_gpus = torch.cuda.device_count()
        print(f"Number of GPUs available: {num_gpus}")
    else:
        print("No GPUs available.")


    ## Dataset
    download_dir = './ag_automm_tutorial'
    zip_file = 'https://automl-mm-bench.s3.amazonaws.com/petfinder_for_tutorial.zip'
    load_zip.unzip(zip_file, unzip_dir=download_dir)

    dataset_path = download_dir + '/petfinder_for_tutorial'
    train_data = pd.read_csv(f'{dataset_path}/train.csv', index_col=0)
    test_data = pd.read_csv(f'{dataset_path}/test.csv', index_col=0)
    label_col = 'AdoptionSpeed'

    image_col = 'Images'
    train_data[image_col] = train_data[image_col].apply(lambda ele: ele.split(';')[0])
    test_data[image_col] = test_data[image_col].apply(lambda ele: ele.split(';')[0])

    def path_expander(path, base_folder):
        path_l = path.split(';')
        return ';'.join([os.path.abspath(os.path.join(base_folder, path)) for path in path_l])

    train_data[image_col] = train_data[image_col].apply(lambda ele: path_expander(ele, base_folder=dataset_path))
    test_data[image_col] = test_data[image_col].apply(lambda ele: path_expander(ele, base_folder=dataset_path))

    ## Training
    hyperparameters = {
        "optimization.max_epochs": 2,
        "model.names": ["numerical_mlp", "categorical_mlp", "timm_image", "hf_text", "fusion_mlp"],
        "model.timm_image.checkpoint_name": "mobilenetv3_small_100",
        "model.hf_text.checkpoint_name": "google/electra-small-discriminator",
        
    }
    print("Training started...")
    predictor = MultiModalPredictor(label=label_col).fit(
        train_data=train_data,
        hyperparameters=hyperparameters,
        time_limit=120, # seconds
    )

    print("Training completed!")
    batch_size = 20
    n_trails = 10
    sample = test_data.head(batch_size)

    # Use first prediction for initialization (e.g., allocating memory)
    y_pred = predictor.predict_proba(sample)

    pred_time = []
    for _ in range(n_trails):
        tic = time.time()
        y_pred = predictor.predict_proba(sample)
        elapsed = time.time()-tic
        pred_time.append(elapsed)
        print(f"elapsed (pytorch): {elapsed*1000:.1f} ms (batch_size={batch_size})")

    print("Started optimizing for inference...")
    model_path = predictor.path
    trt_predictor = MultiModalPredictor.load(path=model_path)
    trt_predictor.optimize_for_inference()
    print("Optimization completed!")

    # Again, use first prediction for initialization (e.g., allocating memory)
    # This will fail on multi GPU enf
    y_pred_trt = trt_predictor.predict_proba(sample)

  ```

**Screenshots / Logs**
```
AssertionError: Gather function not implemented for CPU tensors
Predicting DataLoader 0:   0%|          | 0/1 [00:01<?, ?it/s]
```
The full traceback of the error is provided in the original Github issue.

**Installed Versions**
I have used the following versions:
Autogluon version: 0.8.2
PyTorch version: 1.13.1
TensorRT version: 8.5.3.1
Python version: 3.9
OS: Ubuntu 20.04

<details>

```python
# Replace this code with the output of the following:
from autogluon.core.utils import show_versions
show_versions()
```

</details>

**Comment by AnirudhDagar** [comment]
@tonyhoo `OnnxModule` [doesn't support](https://github.com/autogluon/autogluon/blob/973289cd14b572dbf5175d52133ddd27c0808836/multimodal/src/autogluon/multimodal/models/utils.py#L718C55-L718C55) multi gpu. This is a limitation of ONNX models and not a bug (I'd rather say we need to raise a better error in such a case or warn the user forcing the run to be on a single gpu instead of multi).

More info: https://github.com/microsoft/onnxruntime/issues/16382#issuecomment-1595355632 , https://github.com/microsoft/onnxruntime/issues/16382#issuecomment-1595491119

cc @liangfu 

Besides I had some issues reproducing this issue on the latest version (master) of autogluon, giving me an error:`cannot pickle 'onnxruntime.capi.onnxruntime_pybind11_state.InferenceSession' object` when the `optimize_for_inference` method is called even before the op error.

**Comment by AnirudhDagar** [comment]
@tonyhoo here is the traceback when running the above code snippet in a p3.16xlarge (4xTesla v100 GPUs, cuda11.8) on current master (see exact version details below) as mentioned in the offline discussion:

```
elapsed (pytorch): 44345.4 ms (batch_size=20)
Started optimizing for inference...
Load pretrained checkpoint: /home/ubuntu/autogluon/experimental/AutogluonModels/ag-20231129_074519/model.ckpt
============= Diagnostic Run torch.onnx.export version 2.0.1+cu118 =============
verbose: False, log level: Level.ERROR
======================= 0 NONE 0 NOTE 0 WARNING 0 ERROR ========================

2023-11-29 07:57:12.438728956 [W:onnxruntime:Default, tensorrt_execution_provider.h:75 log] [2023-11-29 07:57:12 WARNING] onnx2trt_utils.cpp:377: Your ONNX model has been generated with INT64 weights, while TensorRT does not natively support INT64. Attempting to cast down to INT32.
Compiling ... (this may take a few minutes)
Traceback (most recent call last):
  File "/home/ubuntu/autogluon/experimental/test_tensorrt.py", line 79, in <module>
    trt_predictor.optimize_for_inference()
  File "/home/ubuntu/autogluon/multimodal/src/autogluon/multimodal/predictor.py", line 913, in optimize_for_inference
    return self._learner.optimize_for_inference(providers=providers)
  File "/home/ubuntu/autogluon/multimodal/src/autogluon/multimodal/utils/export.py", line 211, in optimize_for_inference
    _ = self.predict(data)
  File "/home/ubuntu/autogluon/multimodal/src/autogluon/multimodal/learners/base.py", line 1931, in predict
    outputs = self.predict_per_run(
  File "/home/ubuntu/autogluon/multimodal/src/autogluon/multimodal/learners/base.py", line 1755, in predict_per_run
    outputs = self.run_trainer(
  File "/home/ubuntu/autogluon/multimodal/src/autogluon/multimodal/learners/base.py", line 1189, in run_trainer
    outputs = trainer.predict(
  File "/opt/conda/envs/ag/lib/python3.10/site-packages/lightning/pytorch/trainer/trainer.py", line 852, in predict
    return call._call_and_handle_interrupt(
  File "/opt/conda/envs/ag/lib/python3.10/site-packages/lightning/pytorch/trainer/call.py", line 42, in _call_and_handle_interrupt
    return trainer.strategy.launcher.launch(trainer_fn, *args, trainer=trainer, **kwargs)
  File "/opt/conda/envs/ag/lib/python3.10/site-packages/lightning/pytorch/strategies/launchers/multiprocessing.py", line 119, in launch
    process_context = mp.start_processes(
  File "/opt/conda/envs/ag/lib/python3.10/site-packages/torch/multiprocessing/spawn.py", line 188, in start_processes
    process.start()
  File "/opt/conda/envs/ag/lib/python3.10/multiprocessing/process.py", line 121, in start
    self._popen = self._Popen(self)
  File "/opt/conda/envs/ag/lib/python3.10/multiprocessing/context.py", line 284, in _Popen
    return Popen(process_obj)
  File "/opt/conda/envs/ag/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 32, in __init__
    super().__init__(process_obj)
  File "/opt/conda/envs/ag/lib/python3.10/multiprocessing/popen_fork.py", line 19, in __init__
    self._launch(process_obj)
  File "/opt/conda/envs/ag/lib/python3.10/multiprocessing/popen_spawn_posix.py", line 47, in _launch
    reduction.dump(process_obj, fp)
  File "/opt/conda/envs/ag/lib/python3.10/multiprocessing/reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
TypeError: cannot pickle 'onnxruntime.capi.onnxruntime_pybind11_state.InferenceSession' object
```

<details>
  <summary>Click to expand: Versions</summary>
 
```bash
>>> show_versions()

INSTALLED VERSIONS
------------------
date                   : 2023-11-29
time                   : 08:07:32.878434
python                 : 3.10.0.final.0
OS                     : Linux
OS-release             : 5.15.0-1049-aws
Version                : #54~20.04.1-Ubuntu SMP Fri Oct 6 22:04:33 UTC 2023
machine                : x86_64
processor              : x86_64
num_cores              : 32
cpu_ram_mb             : 245610.5078125
cuda version           : 11.520.61.05
num_gpus               : 4
gpu_ram_mb             : [16160, 16160, 16160, 16160]
avail_disk_size_mb     : 71967

accelerate             : 0.21.0
autogluon              : 1.0.0b20231128
autogluon.eda          : 1.0.0b20231128
autogluon.multimodal   : 1.0.0b20231128
autogluon.timeseries   : 1.0.0b20231128
boto3                  : 1.28.64
defusedxml             : 0.7.1
evaluate               : 0.4.1
gluonts                : 0.14.1
ipython                : 8.12.3
ipywidgets             : 8.1.1
jinja2                 : 3.1.2
joblib                 : 1.3.2
jsonschema             : 4.17.3
lightning              : 2.0.9.post0
matplotlib             : 3.6.3
missingno              : 0.5.2
mlforecast             : 0.10.0
networkx               : 3.0
nlpaug                 : 1.1.11
nltk                   : 3.8.1
nptyping               : 2.4.1
numpy                  : 1.24.1
nvidia-ml-py3          : 7.352.0
omegaconf              : 2.2.3
openmim                : 0.3.9
orjson                 : None
pandas                 : 2.1.3
phik                   : 0.12.3
Pillow                 : 10.1.0
PyMuPDF                : 1.21.1
pyod                   : 1.0.9
pytesseract            : 0.3.10
pytorch-metric-learning: 1.7.3
pytorch_lightning      : 2.0.9.post0
requests               : 2.28.2
scikit-image           : 0.20.0
scikit-learn           : 1.3.2
scipy                  : 1.11.4
seaborn                : 0.12.2
seqeval                : 1.2.2
shap                   : 0.41.0
statsforecast          : 1.4.0
statsmodels            : 0.14.0
suod                   : 0.0.9
tensorboard            : 2.15.1
text-unidecode         : 1.3
timm                   : 0.9.11
torch                  : 2.0.1+cu118
torchmetrics           : 1.1.2
torchvision            : 0.15.2+cu118
tqdm                   : 4.65.2
transformers           : 4.31.0
utilsforecast          : 0.0.10
yellowbrick            : 1.5
 ```

tensorrt details:
```
(ag) ubuntu@ip-172-31-92-227:~/autogluon/experimental$ pip show tensorrt
Name: tensorrt
Version: 8.5.3.1
Summary: A high performance deep learning inference library
Home-page: https://developer.nvidia.com/tensorrt
Author: NVIDIA Corporation
Author-email:
License: Proprietary
Location: /opt/conda/envs/ag/lib/python3.10/site-packages
Requires: nvidia-cublas-cu11, nvidia-cuda-runtime-cu11, nvidia-cudnn-cu11
Required-by:
```

</details>
