### ISSUE TITLE
[BUG] Failed to connect to GCS.

### ISSUE THREAD

**Issue by namelessperson0** [autogluon/autogluon#3894]
**Bug Report Checklist**

- [ ] I provided code that demonstrates a minimal reproducible example.  
- [ ] I confirmed bug exists on the latest mainline of AutoGluon via source install.  
- [ ] I confirmed bug exists on the latest stable version of AutoGluon.  

**Describe the bug**
Getting the below error. 
`ERROR utils.py:1395 -- Failed to connect to GCS. Please check `gcs_server.out` for more details.
`

Previously, I was able to run the same code without this error. 

Now, `ray stop` solves the issue. 

**Installed Versions**

<details>

```python

INSTALLED VERSIONS
------------------
date                   : 2024-01-30
time                   : 09:12:33.121481
python                 : 3.11.7.final.0
OS                     : Linux
OS-release             : 6.2.0-1018-aws
Version                : #18~22.04.1-Ubuntu SMP Wed Jan 10 22:54:16 UTC 2024
machine                : x86_64
processor              : x86_64
num_cores              : 4
cpu_ram_mb             : 15799.16015625
cuda version           : None
num_gpus               : 0
gpu_ram_mb             : []
avail_disk_size_mb     : 134033

accelerate             : 0.21.0
async-timeout          : 4.0.3
autogluon              : 1.0.0
autogluon.common       : 1.0.0
autogluon.core         : 1.0.0
autogluon.features     : 1.0.0
autogluon.multimodal   : 1.0.0
autogluon.tabular      : 1.0.0
autogluon.timeseries   : 1.0.0
boto3                  : 1.34.29
catboost               : 1.2.2
defusedxml             : 0.7.1
evaluate               : 0.4.1
fastai                 : 2.7.13
gluonts                : 0.14.3
hyperopt               : 0.2.7
imodels                : None
jinja2                 : 3.1.2
joblib                 : 1.3.2
jsonschema             : 4.17.3
lightgbm               : 4.1.0
lightning              : 2.0.9.post0
matplotlib             : 3.8.2
mlforecast             : 0.10.0
networkx               : 3.0
nlpaug                 : 1.1.11
nltk                   : 3.8.1
nptyping               : 2.4.1
numpy                  : 1.24.1
nvidia-ml-py3          : 7.352.0
omegaconf              : 2.2.3
onnxruntime-gpu        : None
openmim                : 0.3.9
orjson                 : 3.9.12
pandas                 : 2.1.4
Pillow                 : 10.2.0
psutil                 : 5.9.8
PyMuPDF                : None
pytesseract            : 0.3.10
pytorch-lightning      : 2.0.9.post0
pytorch-metric-learning: 1.7.3
ray                    : 2.6.3
requests               : 2.28.2
scikit-image           : 0.20.0
scikit-learn           : 1.4.0
scikit-learn-intelex   : None
scipy                  : 1.12.0
seqeval                : 1.2.2
setuptools             : 60.2.0
skl2onnx               : None
statsforecast          : 1.4.0
statsmodels            : 0.14.1
tabpfn                 : None
tensorboard            : 2.15.1
text-unidecode         : 1.3
timm                   : 0.9.12
torch                  : 2.0.1+cpu
torchmetrics           : 1.1.2
torchvision            : 0.15.2+cpu
tqdm                   : 4.65.2
transformers           : 4.31.0
utilsforecast          : 0.0.10
vowpalwabbit           : None
xgboost                : 2.0.3

```

</details>

**Comment by dcizin** [comment]
I also encounter an issue like this when I train multiple autogluons in parallel on the cluster (version 1.0.0). 

`[2024-04-19 12:01:09,757 E 97644 101390] gcs_rpc_client.h:547: Failed to connect to GCS within 60 seconds. GCS may have been killed. It's either GCS is terminated by `ray stop` or is killed unexpectedly. If it is killed unexpectedly, see the log file gcs_server.out. https://docs.ray.io/en/master/ray-observability/ray-logging.html#logging-directory-structure. The program will terminate.`

more details:

`Fitting model: CatBoost_r70_BAG_L1 ... Training model for up to 29656.42s of the 29656.41s of remaining time.
        Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.01%)
        Warning: Exception caused CatBoost_r70_BAG_L1 to fail during training... Skipping this model.
                System error: Broken pipe
Detailed Traceback:
Traceback (most recent call last):
  File "/home/cizind/anaconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1817, in _train_and_save
    model = self._train_single(X, y, model, X_val, y_val, total_resources=total_resources, **model_fit_kwargs)
  File "/home/cizind/anaconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1763, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, total_resources=total_resources, **model_fit_kwargs)
  File "/home/cizind/anaconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 854, in fit
    out = self._fit(**kwargs)
  File "/home/cizind/anaconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py", line 165, in _fit
    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)
  File "/home/cizind/anaconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 273, in _fit
    self._fit_folds(
  File "/home/cizind/anaconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 689, in _fit_folds
    fold_fitting_strategy.after_all_folds_scheduled()
  File "/home/cizind/anaconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 649, in after_all_folds_scheduled
    X, y, X_pseudo, y_pseudo = self._prepare_data()
  File "/home/cizind/anaconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 814, in _prepare_data
    X = self.ray.put(self.X)
  File "/home/cizind/anaconda3/envs/autogluon/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/cizind/anaconda3/envs/autogluon/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/cizind/anaconda3/envs/autogluon/lib/python3.9/site-packages/ray/_private/worker.py", line 2597, in put
    object_ref = worker.put_object(value, owner_address=serialize_owner_address)
  File "/home/cizind/anaconda3/envs/autogluon/lib/python3.9/site-packages/ray/_private/worker.py", line 704, in put_object
    self.core_worker.put_serialized_object_and_increment_local_ref(
  File "python/ray/_raylet.pyx", line 2939, in ray._raylet.CoreWorker.put_serialized_object_and_increment_local_ref
  File "python/ray/_raylet.pyx", line 2831, in ray._raylet.CoreWorker._create_put_buffer
  File "python/ray/_raylet.pyx", line 412, in ray._raylet.check_status
ray.exceptions.RaySystemError: System error: Broken pipe
Fitting model: LightGBM_r196_BAG_L1 ... Training model for up to 29655.89s of the 29655.87s of remaining time.
        Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.01%)
        Warning: Exception caused LightGBM_r196_BAG_L1 to fail during training... Skipping this model.
                System error: Broken pipe
Detailed Traceback:
Traceback (most recent call last):
  File "/home/cizind/anaconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1817, in _train_and_save
    model = self._train_single(X, y, model, X_val, y_val, total_resources=total_resources, **model_fit_kwargs)
  File "/home/cizind/anaconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1763, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, total_resources=total_resources, **model_fit_kwargs)
  File "/home/cizind/anaconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 854, in fit
    out = self._fit(**kwargs)
  File "/home/cizind/anaconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py", line 165, in _fit
    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)
  File "/home/cizind/anaconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 273, in _fit
    self._fit_folds(
  File "/home/cizind/anaconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 689, in _fit_folds
    fold_fitting_strategy.after_all_folds_scheduled()
  File "/home/cizind/anaconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 649, in after_all_folds_scheduled
    X, y, X_pseudo, y_pseudo = self._prepare_data()
  File "/home/cizind/anaconda3/envs/autogluon/lib/python3.9/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 814, in _prepare_data
    X = self.ray.put(self.X)
  File "/home/cizind/anaconda3/envs/autogluon/lib/python3.9/site-packages/ray/_private/auto_init_hook.py", line 24, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/home/cizind/anaconda3/envs/autogluon/lib/python3.9/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/home/cizind/anaconda3/envs/autogluon/lib/python3.9/site-packages/ray/_private/worker.py", line 2597, in put
    object_ref = worker.put_object(value, owner_address=serialize_owner_address)
  File "/home/cizind/anaconda3/envs/autogluon/lib/python3.9/site-packages/ray/_private/worker.py", line 704, in put_object
    self.core_worker.put_serialized_object_and_increment_local_ref(
  File "python/ray/_raylet.pyx", line 2939, in ray._raylet.CoreWorker.put_serialized_object_and_increment_local_ref
  File "python/ray/_raylet.pyx", line 2831, in ray._raylet.CoreWorker._create_put_buffer
  File "python/ray/_raylet.pyx", line 412, in ray._raylet.check_status`

**Comment by shchur** [comment]
@namelessperson0 Can you please provide example code that reproduces this issue?
