### ISSUE TITLE
[BUG] Pip install with python 3.9 and 3.10 fails on windows at ray download

### ISSUE THREAD

**Issue by kaasproav** [autogluon/autogluon#3908]
**Bug Report Checklist**

- [ ] I provided code that demonstrates a minimal reproducible example.  
- [ ] I confirmed bug exists on the latest mainline of AutoGluon via source install.  
- [X] I confirmed bug exists on the latest stable version of AutoGluon.  

**Describe the bug**
 After pip install failed on 3.11, I created virtual environments with 3.9 and 3.10 and proceeded with all steps on Autogluon install page for windows, pip, cpu install. It works until i get to the ray package which never finishes collecting and fails. This occurs on both 3.9 and 3.10. I am using anaconda3 cmd.exe terminal to enter pip install commands. 

**Expected behavior**
 Normal pip install of autogluon 1.0.0.

**To Reproduce**
Simply followed steps of autogluon install page for windows, pip, and cpu. Failure happens on final step: pip install autogluon and the ray package is collecting.

**Screenshots / Logs**
Using cached accelerate-0.21.0-py3-none-any.whl (244 kB)
Using cached boto3-1.34.36-py3-none-any.whl (139 kB)
Using cached catboost-1.2.2-cp310-cp310-win_amd64.whl (101.0 MB)
Using cached evaluate-0.4.1-py3-none-any.whl (84 kB)
Using cached fastai-2.7.14-py3-none-any.whl (232 kB)
Using cached gluonts-0.14.4-py3-none-any.whl (1.5 MB)
Using cached joblib-1.3.2-py3-none-any.whl (302 kB)
Using cached lightgbm-4.1.0-py3-none-win_amd64.whl (1.3 MB)
Using cached lightning-2.0.9.post0-py3-none-any.whl (1.9 MB)
Using cached mlforecast-0.10.0-py3-none-any.whl (47 kB)
Using cached openmim-0.3.9-py2.py3-none-any.whl (52 kB)
Using cached orjson-3.9.13-cp310-none-win_amd64.whl (134 kB)
Using cached pandas-2.1.4-cp310-cp310-win_amd64.whl (10.7 MB)
Using cached pytorch_lightning-2.0.9.post0-py3-none-any.whl (727 kB)
Downloading ray-2.6.3-cp310-cp310-win_amd64.whl (22.4 MB)
   ----------------------------------- ---- 19.9/22.4 MB 741.4 kB/s eta 0:00:04
ERROR: Exception:
Traceback (most recent call last):
  File "C:\Users\dbourne\env310\lib\site-packages\pip\_vendor\urllib3\response.py", line 438, in _error_catcher
    yield
  File "C:\Users\dbourne\env310\lib\site-packages\pip\_vendor\urllib3\response.py", line 561, in read
    data = self._fp_read(amt) if not fp_closed else b""
  File "C:\Users\dbourne\env310\lib\site-packages\pip\_vendor\urllib3\response.py", line 527, in _fp_read
    return self._fp.read(amt) if amt is not None else self._fp.read()
  File "C:\Users\dbourne\env310\lib\site-packages\pip\_vendor\cachecontrol\filewrapper.py", line 98, in read
    data: bytes = self.__fp.read(amt)
  File "C:\Users\dbourne\AppData\Local\anaconda3\Python_versions\Python310\lib\http\client.py", line 466, in read
    s = self.fp.read(amt)
  File "C:\Users\dbourne\AppData\Local\anaconda3\Python_versions\Python310\lib\socket.py", line 705, in readinto
    return self._sock.recv_into(b)
  File "C:\Users\dbourne\AppData\Local\anaconda3\Python_versions\Python310\lib\ssl.py", line 1274, in recv_into
    return self.read(nbytes, buffer)
  File "C:\Users\dbourne\AppData\Local\anaconda3\Python_versions\Python310\lib\ssl.py", line 1130, in read
    return self._sslobj.read(len, buffer)
TimeoutError: The read operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\dbourne\env310\lib\site-packages\pip\_internal\cli\base_command.py", line 180, in exc_logging_wrapper
    status = run_func(*args)
  File "C:\Users\dbourne\env310\lib\site-packages\pip\_internal\cli\req_command.py", line 245, in wrapper
    return func(self, options, args)
  File "C:\Users\dbourne\env310\lib\site-packages\pip\_internal\commands\install.py", line 377, in run
    requirement_set = resolver.resolve(
  File "C:\Users\dbourne\env310\lib\site-packages\pip\_internal\resolution\resolvelib\resolver.py", line 179, in resolve
    self.factory.preparer.prepare_linked_requirements_more(reqs)
  File "C:\Users\dbourne\env310\lib\site-packages\pip\_internal\operations\prepare.py", line 552, in prepare_linked_requirements_more
    self._complete_partial_requirements(
  File "C:\Users\dbourne\env310\lib\site-packages\pip\_internal\operations\prepare.py", line 467, in _complete_partial_requirements
    for link, (filepath, _) in batch_download:
  File "C:\Users\dbourne\env310\lib\site-packages\pip\_internal\network\download.py", line 183, in __call__
    for chunk in chunks:
  File "C:\Users\dbourne\env310\lib\site-packages\pip\_internal\cli\progress_bars.py", line 53, in _rich_progress_bar
    for chunk in iterable:
  File "C:\Users\dbourne\env310\lib\site-packages\pip\_internal\network\utils.py", line 63, in response_chunks
    for chunk in response.raw.stream(
  File "C:\Users\dbourne\env310\lib\site-packages\pip\_vendor\urllib3\response.py", line 622, in stream
    data = self.read(amt=amt, decode_content=decode_content)
  File "C:\Users\dbourne\env310\lib\site-packages\pip\_vendor\urllib3\response.py", line 560, in read
    with self._error_catcher():
  File "C:\Users\dbourne\AppData\Local\anaconda3\Python_versions\Python310\lib\contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "C:\Users\dbourne\env310\lib\site-packages\pip\_vendor\urllib3\response.py", line 443, in _error_catcher
    raise ReadTimeoutError(self._pool, None, "Read timed out.")
pip._vendor.urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='files.pythonhosted.org', port=443): Read timed out.

**Installed Versions**
(env310) (base) C:\Users\dbourne>python -V
Python 3.10.11

(env310) (base) C:\Users\dbourne>pip list
Package            Version
------------------ ----------
certifi            2022.12.7
charset-normalizer 2.1.1
filelock           3.9.0
idna               3.4
Jinja2             3.1.2
MarkupSafe         2.1.3
mpmath             1.3.0
networkx           3.2.1
numpy              1.26.3
pillow             10.2.0
pip                24.0
requests           2.28.1
setuptools         69.0.3
sympy              1.12
torch              2.0.1+cpu
torchvision        0.15.2+cpu
typing_extensions  4.8.0
urllib3            1.26.13
wheel              0.42.0
```python


# Replace this code with the output of the following:
from autogluon.core.utils import show_versions
show_versions()
```

</details>

**Comment by AnirudhDagar** [comment]
this is now fixed with the ray upgrade in #3774
