### ISSUE TITLE
[BUG] Setting `ag_args_ensemble`  `num_folds` to 0 results in error when `num_bag_folds >= 2`  is set in the `.fit()`.

### ISSUE THREAD

**Issue by JSpenced** [autogluon/autogluon#3913]
**Bug Report Checklist**

- [X] I provided code that demonstrates a minimal reproducible example.  
- [] I confirmed bug exists on the latest mainline of AutoGluon via source install.  
- [X] I confirmed bug exists on the latest stable version of AutoGluon.  

**Describe the bug**
If you try to set the `"ag_args_ensemble": {"num_folds": 0}` in the hyperparameters dictionary when `num_bag_folds=2` is set in the `.fit`. It results in an error. A minimal example shown below, but swap in your dataset. I think if `num_folds` is `0` that it should exit the k_folds loop and not run the model through that processing of `k_folds` and just do a single model, but this doesn't happen. Also, if this is done the other way of specifying nothing and adding `num_folds` of 2 into `ag_args_ensemble` then it doesn't run bagged models. 

I want this because I prefer to bag and run hyperparameter tuning on the boosted models as it is quick, and then not do so on any of the neural network models. I couldn't figure out how to correctly specify that in the settings that would work.

**Expected behavior**
I expected it to break out of the k_fold loop and just train a single model. Instead it errors out with the logs in the section below under screenshots. I think it should check for the `num_folds` argument before creating the `BaggedEnsemble`.

**To Reproduce**

```python
import autogluon as ag
from autogluon.tabular import TabularDataset, TabularPredictor

hyperparams = {
    'GBM': {
        "ag_args": {"hyperparameter_tune_kwargs": {'num_trials': 2, 'scheduler' : 'local', 'searcher': 'auto'}},
        "ag_args_ensemble": {"num_folds": 0}
    },
    #  'AG_AUTOMM': {
    #  "ag_args": {"hyperparameter_tune_kwargs": {'num_trials': 0}},
    #  "ag_args_fit": {"max_time_limit": 60, "num_gpus": 1},
    #  "ag_args_ensemble": {"num_folds": 0}
    # },

predictor = TabularPredictor(problem_type="regression",
                             label='label',
                             path="~/data/models/temp",
                             eval_metric="root_mean_squared_error").fit(
    train_data=df_train[feature_cols].iloc[0:1000],
    hyperparameters=hyperparams,
    num_bag_folds=2,
    )
}


**Screenshots / Logs**
```
k_fold_end must be greater than k_fold_start, values: (0, 0)
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/envs/opcity-ml/lib/python3.9/site-packages/autogluon/core/models/abstract/model_trial.py", line 37, in model_trial
    model = fit_and_save_model(
  File "/home/ubuntu/miniconda/envs/opcity-ml/lib/python3.9/site-packages/autogluon/core/models/abstract/model_trial.py", line 96, in fit_and_save_model
    model.fit(**fit_args, time_limit=time_left)
  File "/home/ubuntu/miniconda/envs/opcity-ml/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 838, in fit
    out = self._fit(**kwargs)
  File "/home/ubuntu/miniconda/envs/opcity-ml/lib/python3.9/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py", line 165, in _fit
    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)
  File "/home/ubuntu/miniconda/envs/opcity-ml/lib/python3.9/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 211, in _fit
    self._validate_bag_kwargs(
  File "/home/ubuntu/miniconda/envs/opcity-ml/lib/python3.9/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 336, in _validate_bag_kwargs
    raise ValueError(f"k_fold_end must be greater than k_fold_start, values: ({k_fold_end}, {k_fold_start})")
ValueError: k_fold_end must be greater than k_fold_start, values: (0, 0)
k_fold_end must be greater than k_fold_start, values: (0, 0)
Traceback (most recent call last):
  File "/home/ubuntu/miniconda/envs/opcity-ml/lib/python3.9/site-packages/autogluon/core/models/abstract/model_trial.py", line 37, in model_trial
    model = fit_and_save_model(
  File "/home/ubuntu/miniconda/envs/opcity-ml/lib/python3.9/site-packages/autogluon/core/models/abstract/model_trial.py", line 96, in fit_and_save_model
    model.fit(**fit_args, time_limit=time_left)
  File "/home/ubuntu/miniconda/envs/opcity-ml/lib/python3.9/site-packages/autogluon/core/models/abstract/abstract_model.py", line 838, in fit
    out = self._fit(**kwargs)
  File "/home/ubuntu/miniconda/envs/opcity-ml/lib/python3.9/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py", line 165, in _fit
    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)
  File "/home/ubuntu/miniconda/envs/opcity-ml/lib/python3.9/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 211, in _fit
    self._validate_bag_kwargs(
  File "/home/ubuntu/miniconda/envs/opcity-ml/lib/python3.9/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 336, in _validate_bag_kwargs
    raise ValueError(f"k_fold_end must be greater than k_fold_start, values: ({k_fold_end}, {k_fold_start})")
ValueError: k_fold_end must be greater than k_fold_start, values: (0, 0)
No model was trained during hyperparameter tuning LightGBM_BAG_L1... Skipping this model.
No base models to train on, skipping auxiliary stack level 2...
```

INSTALLED VERSIONS
------------------
date                   : 2024-02-11
time                   : 05:13:25.987318
python                 : 3.9.16.final.0
OS                     : Linux
OS-release             : 5.15.0-1053-aws
Version                : #58~20.04.1-Ubuntu SMP Mon Jan 22 17:15:01 UTC 2024
machine                : x86_64
processor              : x86_64
num_cores              : 64
cpu_ram_mb             : 255018
cuda version           : 12.525.147.05
num_gpus               : 1
gpu_ram_mb             : [21576]
avail_disk_size_mb     : 425362

accelerate             : 0.16.0
autogluon              : 0.8.2
autogluon.common       : 0.8.2
autogluon.core         : 0.8.2
autogluon.features     : 0.8.2
autogluon.multimodal   : 0.8.2
autogluon.tabular      : 0.8.2
autogluon.timeseries   : 0.8.2
boto3                  : 1.24.34
catboost               : 1.2
defusedxml             : 0.7.1
evaluate               : 0.3.0
fastai                 : 2.7.12
gluonts                : 0.13.3
grpcio                 : 1.46.3
hyperopt               : 0.2.7
imodels                : 1.3.18
jinja2                 : 3.1.2
joblib                 : 1.3.1
jsonschema             : 4.17.3
lightgbm               : 3.3.5
matplotlib             : 3.7.2
mlforecast             : 0.7.3
networkx               : 3.1
nlpaug                 : 1.1.11
nltk                   : 3.6.7
nptyping               : 2.4.1
numpy                  : 1.22.4
omegaconf              : 2.2.3
onnxruntime-gpu        : 1.13.1
openmim                : 0.3.9
pandas                 : 1.5.1
Pillow                 : 9.4.0
psutil                 : 5.9.4
pydantic               : 1.10.12
PyMuPDF                : None
pytesseract            : 0.3.10
pytorch-lightning      : 1.9.5
pytorch-metric-learning: 1.7.3
ray                    : 2.3.1
requests               : 2.28.0
scikit-image           : 0.19.3
scikit-learn           : 1.1.1
scikit-learn-intelex   : 2023.1.1
scipy                  : 1.8.1
seqeval                : 1.2.2
setuptools             : 59.5.0
skl2onnx               : 1.13
statsforecast          : 1.4.0
statsmodels            : 0.13.2
tabpfn                 : 0.1.10
tensorboard            : 2.9.0
text-unidecode         : 1.3
timm                   : 0.9.5
torch                  : 1.12.0
torchmetrics           : 0.11.4
torchvision            : 0.13.0
tqdm                   : 4.65.0
transformers           : 4.26.1
ujson                  : 5.3.0
vowpalwabbit           : 9.4.0
xgboost                : 1.7.4
E0211 05:13:25.987650804   52419 fork_posix.cc:76]           Other threads are currently calling into gRPC, skipping fork() handlers

```

</details>

**Comment by Innixma** [comment]
Thanks for this issue! I've improved the logging to better communicate what is going on when `num_folds=0` (exception) and `num_folds=1` (warning). The change is in this PR: #4780
