### ISSUE TITLE
[BUG] I got error in running Deepar model

### ISSUE THREAD

**Issue by creamiracle** [autogluon/autogluon#4275]
**Bug Report Checklist**

- [ ] I provided code that demonstrates a minimal reproducible example.  
- [ ] I confirmed bug exists on the latest mainline of AutoGluon via source install.  
- [ ] I confirmed bug exists on the latest stable version of AutoGluon.  

**Describe the bug**
I use Deepar in this dataset and get error like this
```
Expected parameter df (Tensor of shape (1900, 1)) of distribution Chi2() to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values ensor([[3.2372],
        [3.2372],
        [3.2372],
        ...,
        [   nan],
        [   nan],
        [   nan]], device='cuda:0')
``` 
I have check the data and it contains no nan, and I write code like this
```
predictor.fit(
        train_df,
        hyperparameters={
            # "TemporalFusionTransformerModel": {},
            #"PatchTSTModel": {},
            #"ThetaModel": {},
            "DeepARModel": {},
            # "AutoARIMAModel": {}
        },
        refit_every_n_windows=1,
        presets="best_quality",
        num_val_windows=4
    )
```
it can finish training, but when I use predictor, and I get this error. I have no idea about this.

**Expected behavior**

Please give me some advice or guide about this bug and I can try to fix it.

**To Reproduce**

**Screenshots / Logs**

```
Inferred time series frequency: 'D'
train_data contains missing values represented by NaN. They have been filled by carrying forward the last valid observation.
Provided train_data has 6764 rows, 19 time series. Median time series length is 356 (min=356, max=356). 

Provided dataset contains following columns:
        target:           'target'
        known covariates: ['promote', 'order']

AutoGluon will gauge predictive performance using evaluation metric: 'RMSSE'
        This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
===================================================

Starting training. Start time is 2024-06-17 17:28:24
Models that will be trained: ['DeepAR']
Training timeseries model DeepAR. 
        -1.2500       = Validation score (-RMSSE)
        217.71  s     = Training runtime
        0.34    s     = Validation (prediction) runtime
Not fitting ensemble as only 1 model was trained.
Training complete. Models trained: ['DeepAR']
Total runtime: 218.08 s
Best model: DeepAR
Best model score: -1.2500
data contains missing values represented by NaN. They have been filled by carrying forward the last valid observation.
Model not specified in predict, will default to the model with the best validation score: DeepAR
data contains missing values represented by NaN. They have been filled by carrying forward the last valid observation.
Model not specified in predict, will default to the model with the best validation score: DeepAR
Model DeepAR failed to predict with the following exception:
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/autogluon/timeseries/trainer/abstract_trainer.py", line 944, in get_model_pred_dict
    model_pred_dict[model_name] = self._predict_model(
  File "/usr/local/lib/python3.8/dist-packages/autogluon/timeseries/trainer/abstract_trainer.py", line 874, in _predict_model
    return model.predict(data, known_covariates=known_covariates)
  File "/usr/local/lib/python3.8/dist-packages/autogluon/timeseries/models/abstract/abstract_timeseries_model.py", line 298, in predict
    predictions = self._predict(data=data, known_covariates=known_covariates, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/autogluon/timeseries/models/multi_window/multi_window_model.py", line 177, in _predict
    return self.most_recent_model.predict(data, known_covariates=known_covariates, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/autogluon/timeseries/models/abstract/abstract_timeseries_model.py", line 298, in predict
    predictions = self._predict(data=data, known_covariates=known_covariates, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/autogluon/timeseries/models/gluonts/abstract_gluonts.py", line 445, in _predict
    predicted_targets = self._predict_gluonts_forecasts(data, known_covariates=known_covariates, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/autogluon/timeseries/models/gluonts/abstract_gluonts.py", line 460, in _predict_gluonts_forecasts
    return list(self.gts_predictor.predict(**predictor_kwargs))
  File "/usr/local/lib/python3.8/dist-packages/gluonts/torch/model/predictor.py", line 90, in predict
    yield from self.forecast_generator(
  File "/usr/local/lib/python3.8/dist-packages/gluonts/model/forecast_generator.py", line 156, in __call__
    outputs = predict_to_numpy(prediction_net, inputs)
  File "/usr/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/usr/local/lib/python3.8/dist-packages/gluonts/torch/model/predictor.py", line 38, in _
    return prediction_net(**kwargs).cpu().numpy()
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gluonts/torch/model/deepar/lightning_module.py", line 68, in forward
    return self.model(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/gluonts/torch/model/deepar/module.py", line 448, in forward
    distr = self.output_distribution(
  File "/usr/local/lib/python3.8/dist-packages/gluonts/torch/model/deepar/module.py", line 357, in output_distribution
    return self.distr_output.distribution(sliced_params, scale=scale)
  File "/usr/local/lib/python3.8/dist-packages/gluonts/torch/distributions/distribution_output.py", line 137, in distribution
    distr = self._base_distribution(distr_args)
  File "/usr/local/lib/python3.8/dist-packages/gluonts/torch/distributions/distribution_output.py", line 114, in _base_distribution
    return self.distr_cls(*distr_args)
  File "/usr/local/lib/python3.8/dist-packages/gluonts/torch/distributions/studentT.py", line 39, in __init__
    super().__init__(
  File "/usr/local/lib/python3.8/dist-packages/torch/distributions/studentT.py", line 52, in __init__
    self._chi2 = Chi2(self.df)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributions/chi2.py", line 24, in __init__
    super().__init__(0.5 * df, 0.5, validate_args=validate_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributions/gamma.py", line 54, in __init__
    super().__init__(batch_shape, validate_args=validate_args)
  File "/usr/local/lib/python3.8/dist-packages/torch/distributions/distribution.py", line 62, in __init__
    raise ValueError(
ValueError: Expected parameter df (Tensor of shape (1900, 1)) of distribution Chi2() to satisfy the constraint GreaterThan(lower_bound=0.0), but found invalid values:
tensor([[3.2372],
        [3.2372],
        [3.2372],
        ...,
        [   nan],
        [   nan],
        [   nan]], device='cuda:0')

Traceback (most recent call last):
  File "long_term_main.py", line 11, in <module>
    main()
  File "/root/qilin/customer-service-predict/src/longterm.py", line 670, in main
    run(tasks[k], conf, k)
  File "/root/qilin/customer-service-predict/src/longterm.py", line 568, in run
    predictions = predictor.predict(pred_df,
  File "/usr/local/lib/python3.8/dist-packages/autogluon/timeseries/predictor.py", line 783, in predict
    predictions = self._learner.predict(data, known_covariates=known_covariates, model=model, use_cache=use_cache)
  File "/usr/local/lib/python3.8/dist-packages/autogluon/timeseries/learner.py", line 176, in predict
    return self.load_trainer().predict(
  File "/usr/local/lib/python3.8/dist-packages/autogluon/timeseries/trainer/abstract_trainer.py", line 807, in predict
    model_pred_dict = self.get_model_pred_dict(
  File "/usr/local/lib/python3.8/dist-packages/autogluon/timeseries/trainer/abstract_trainer.py", line 959, in get_model_pred_dict
    raise RuntimeError(f"Following models failed to predict: {failed_models}")
RuntimeError: Following models failed to predict: ['DeepAR']
```
**Installed Versions**

<details>

```python
# Replace this code with the output of the following:
from autogluon.core.utils import show_versions
show_versions()
```
INSTALLED VERSIONS
------------------
date                   : 2024-06-17
time                   : 17:49:46.730123
python                 : 3.8.10.final.0
OS                     : Linux
OS-release             : 4.18.0-193.el8.jd_206.x86_64
Version                : #1 SMP Thu Apr 21 10:52:31 CST 2022
machine                : x86_64
processor              : x86_64
num_cores              : 32
cpu_ram_mb             : 221401.57421875
cuda version           : 11.470.57.02
num_gpus               : 1
gpu_ram_mb             : [22917]
avail_disk_size_mb     : 19392

accelerate             : 0.21.0
async-timeout          : 4.0.3
autogluon              : 1.0.0
autogluon.common       : 1.0.0
autogluon.core         : 1.0.0
autogluon.features     : 1.0.0
autogluon.multimodal   : 1.0.0
autogluon.tabular      : 1.0.0
autogluon.timeseries   : 1.0.0
boto3                  : 1.34.20
catboost               : 1.1.1
defusedxml             : 0.7.1
evaluate               : 0.4.1
fastai                 : 2.7.13
gluonts                : 0.14.3
hyperopt               : 0.2.7
imodels                : None
jinja2                 : 3.1.3
joblib                 : 1.3.2
jsonschema             : 4.17.3
lightgbm               : 4.1.0
lightning              : 2.0.9.post0
matplotlib             : 3.7.5
mlforecast             : 0.10.0
networkx               : 3.1
nlpaug                 : 1.1.11
nltk                   : 3.8.1
nptyping               : 2.4.1
numpy                  : 1.24.4
nvidia-ml-py3          : 7.352.0
omegaconf              : 2.2.3
onnxruntime-gpu        : None
openmim                : 0.3.9
orjson                 : 3.9.10
pandas                 : 2.0.3
Pillow                 : 10.2.0
psutil                 : 5.9.7
PyMuPDF                : None
pytesseract            : 0.3.10
pytorch-lightning      : 2.0.9.post0
pytorch-metric-learning: 1.7.3
ray                    : 2.6.3
requests               : 2.28.2
scikit-image           : 0.20.0
scikit-learn           : 1.3.2
scikit-learn-intelex   : None
scipy                  : 1.9.1
seqeval                : 1.2.2
setuptools             : 60.2.0
skl2onnx               : None
statsforecast          : 1.4.0
statsmodels            : 0.14.1
tabpfn                 : None
tensorboard            : 2.14.0
text-unidecode         : 1.3
timm                   : 0.9.12
torch                  : 2.0.1
torchmetrics           : 1.1.2
torchvision            : 0.15.2
tqdm                   : 4.65.2
transformers           : 4.31.0
utilsforecast          : 0.0.10
vowpalwabbit           : None
xgboost                : 2.0.3
</details>

**Comment by shchur** [comment]
Hi @creamiracle, thank you for reporting the issue. Can you please check if the issue is still present in the latest AutoGluon version (v1.1.1)? Based on the logs it seems that the code uses AutoGluon v1.0. 

As far as I can tell from the logs, the issue is caused by numerical instabilities / NaN values appearing during the forward pass of the DeepAR model. Could you share the time series on which the model fails to predict? This would be helpful for debugging.

**Comment by creamiracle** [comment]
> Hi @creamiracle, thank you for reporting the issue. Can you please check if the issue is still present in the latest AutoGluon version (v1.1.1)? Based on the logs it seems that the code uses AutoGluon v1.0.
> 
> As far as I can tell from the logs, the issue is caused by numerical instabilities / NaN values appearing during the forward pass of the DeepAR model. Could you share the time series on which the model fails to predict? This would be helpful for debugging.

sure, let me check the version and data first, then I will post some of the data here. Thanks.

**Comment by shchur** [comment]
Fixed in the latest GluonTS hotfix.
