### ISSUE TITLE
[BUG] I run the hyper parameter optimization with these methods, so I always get this error

### ISSUE THREAD

**Issue by lukaspistelak** [autogluon/autogluon#4370]
I run the hyper parameter optimization with these methods, :

```
`# Instantiate the TabularPredictor with the custom metric
predictor = TabularPredictor(label='target', problem_type='regression', eval_metric=ag_mean_squared_error_custom_scorer)


# Fit the model with hyperparameter tuning
predictor.fit(
    train_data=train_data, 
    time_limit=3600, 
    presets='good_quality', 
   
)

```
`

so I always get this error :+1: 

```
toGluon will fit 2 stack levels (L1 to L2) ...
Fitting 9 L1 models ...
Fitting model: LightGBMXT_BAG_L1 ... Training model for up to 2395.88s of the 3594.71s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.41%)
	Warning: Exception caused LightGBMXT_BAG_L1 to fail during training... Skipping this model.
		ray::_ray_fit() (pid=13858, ip=10.233.115.226)
  File "/opt/conda/lib/python3.11/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 412, in _ray_fit
    save_path = fold_model.save()
                ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/autogluon/core/models/abstract/abstract_model.py", line 1096, in save
    save_pkl.save(path=file_path, object=self, verbose=verbose)
  File "/opt/conda/lib/python3.11/site-packages/autogluon/common/savers/save_pkl.py", line 27, in save
    save_with_fn(validated_path, object, pickle_fn, format=format, verbose=verbose, compression_fn=compression_fn, compression_fn_kwargs=compression_fn_kwargs)
  File "/opt/conda/lib/python3.11/site-packages/autogluon/common/savers/save_pkl.py", line 47, in save_with_fn
    pickle_fn(object, fout)
  File "/opt/conda/lib/python3.11/site-packages/autogluon/common/savers/save_pkl.py", line 25, in pickle_fn
    return pickle.dump(o, buffer, protocol=4)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.PicklingError: Can't pickle <function metric_1 at 0x7fd2d6747ce0>: attribute lookup metric_1 on __main__ failed
Detailed Traceback:
Traceback (most recent call last):
  File "/opt/conda/lib/python3.11/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1904, in _train_and_save
    model = self._train_single(X, y, model, X_val, y_val, total_resources=total_resources, **model_fit_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/autogluon/core/trainer/abstract_trainer.py", line 1844, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, total_resources=total_resources, **model_fit_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/autogluon/core/models/abstract/abstract_model.py", line 856, in fit
    out = self._fit(**kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py", line 165, in _fit
    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 288, in _fit
    self._fit_folds(
  File "/opt/conda/lib/python3.11/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py", line 714, in _fit_folds
    fold_fitting_strategy.after_all_folds_scheduled()
  File "/opt/conda/lib/python3.11/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 668, in after_all_folds_scheduled
    self._run_parallel(X, y, X_pseudo, y_pseudo, model_base_ref, time_limit_fold, head_node_id)
  File "/opt/conda/lib/python3.11/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 610, in _run_parallel
    self._process_fold_results(finished, unfinished, fold_ctx)
  File "/opt/conda/lib/python3.11/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 572, in _process_fold_results
    raise processed_exception
  File "/opt/conda/lib/python3.11/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 537, in _process_fold_results
    fold_model, pred_proba, time_start_fit, time_end_fit, predict_time, predict_1_time, predict_n_size = self.ray.get(finished)
                                                                                                         ^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/ray/_private/worker.py", line 2667, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/ray/_private/worker.py", line 864, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(PicklingError): ray::_ray_fit() (pid=13858, ip=10.233.115.226)
  File "/opt/conda/lib/python3.11/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 412, in _ray_fit
    save_path = fold_model.save()
                ^^^^^^^^^^^^^^^^^
  File "/opt/conda/lib/python3.11/site-packages/autogluon/core/models/abstract/abstract_model.py", line 1096, in save
    save_pkl.save(path=file_path, object=self, verbose=verbose)
  File "/opt/conda/lib/python3.11/site-packages/autogluon/common/savers/save_pkl.py", line 27, in save
    save_with_fn(validated_path, object, pickle_fn, format=format, verbose=verbose, compression_fn=compression_fn, compression_fn_kwargs=compression_fn_kwargs)
  File "/opt/conda/lib/python3.11/site-packages/autogluon/common/savers/save_pkl.py", line 47, in save_with_fn
    pickle_fn(object, fout)
  File "/opt/conda/lib/python3.11/site-packages/autogluon/common/savers/save_pkl.py", line 25, in pickle_fn
    return pickle.dump(o, buffer, protocol=4)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_pickle.PicklingError: Can't pickle <function metric_1 at 0x7fd2d6747ce0>: attribute lookup metric_1 on __main__ failed
Fitting model: LightGBM_BAG_L1 ... Training model for up to 2377.7s of the 3576.54s of remaining time.
	Fitting 8 child models (S1F1 - S1F8) | Fitting with ParallelLocalFoldFittingStrategy (8 workers, per: cpus=2, gpus=0, memory=0.43%)
2024-08-07 08:39:39,345	ERROR worker.py:406 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
2024-08-07 08:39:39,356	ERROR worker.py:406 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
2024-08-07 08:39:39,358	ERROR worker.py:406 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
2024-08-07 08:39:39,358	ERROR worker.py:406 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
2024-08-07 08:39:39,359	ERROR worker.py:406 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
2024-08-07 08:39:39,359	ERROR worker.py:406 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
2024-08-07 08:39:39,360	ERROR worker.py:406 -- Unhandled error (suppress with 'RAY_IGNORE_UNHANDLED_ERRORS=1'): The worker died unexpectedly while executing this task. Check python-core-worker-*.log files for more information.
	Warning: Exception caused LightGBM_BAG_L1 to fail during training... Skipping this model.
		ray::_ray_fit() (pid=14813, ip=10.233.115.226)
  File "/opt/conda/lib/python3.11/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py", line 412, in _ray_f
```

I want to ask what the code should look like in order for some normal hyper parameter tuning to take place and it would take a maximum of a few days. The data is small , about 500 features and 24,000 lines, so I don't understand why this piece of code took five days and hasn't finished yet

[log_autogluon.txt](https://github.com/user-attachments/files/16521006/log_autogluon.txt)
**Screenshots / Logs**

```python
# Replace this code with the output of the following:
from autogluon.core.utils import show_versions
show_versions()
```INSTALLED VERSIONS
------------------
date                   : 2024-08-07
time                   : 09:03:48.396743
python                 : 3.11.6.final.0
OS                     : Linux
OS-release             : 5.15.0-79-generic
Version                : #86-Ubuntu SMP Mon Jul 10 16:07:21 UTC 2023
machine                : x86_64
processor              : x86_64
num_cores              : 16
cpu_ram_mb             : 127944.47265625
cuda version           : None
num_gpus               : 0
gpu_ram_mb             : []
avail_disk_size_mb     : 581903

accelerate             : 0.21.0
autogluon              : 1.1.1
autogluon.common       : 1.1.1
autogluon.core         : 1.1.1
autogluon.features     : 1.1.1
autogluon.multimodal   : 1.1.1
autogluon.tabular      : 1.1.1
autogluon.timeseries   : 1.1.1
boto3                  : 1.34.154
catboost               : 1.2.5
defusedxml             : 0.7.1
evaluate               : 0.4.2
fastai                 : 2.7.16
gluonts                : 0.15.1
hyperopt               : 0.2.7
imodels                : None
jinja2                 : 3.1.2
joblib                 : 1.3.2
jsonschema             : 4.19.1
lightgbm               : 4.3.0
lightning              : 2.3.3
matplotlib             : 3.8.0
mlforecast             : 0.10.0
networkx               : 3.1
nlpaug                 : 1.1.11
nltk                   : 3.8.1
nptyping               : 2.4.1
numpy                  : 1.24.4
nvidia-ml-py3          : 7.352.0
omegaconf              : 2.2.3
onnxruntime-gpu        : None
openmim                : 0.3.9
optimum                : 1.18.1
optimum-intel          : None
orjson                 : 3.10.6
pandas                 : 2.1.1
pdf2image              : 1.17.0
Pillow                 : 10.0.1
psutil                 : 5.9.5
pytesseract            : 0.3.10
pytorch-lightning      : 2.3.3
pytorch-metric-learning: 2.3.0
ray                    : 2.10.0
requests               : 2.32.3
scikit-image           : 0.20.0
scikit-learn           : 1.3.1
scikit-learn-intelex   : None
scipy                  : 1.11.3
seqeval                : 1.2.2
setuptools             : 68.2.2
skl2onnx               : None
statsforecast          : 1.4.0
tabpfn                 : None
tensorboard            : 2.17.0
text-unidecode         : 1.3
timm                   : 0.9.16
torch                  : 2.3.1
torchmetrics           : 1.2.1
torchvision            : 0.18.1
tqdm                   : 4.66.5
transformers           : 4.39.3
utilsforecast          : 0.0.10
vowpalwabbit           : None
xgboost                : 2.0.3

</details>

**Comment by Innixma** [comment]
Try not specifying your custom eval_metric. The eval_metric appears to not be pickle-able.

For more information, refer to the tutorial on serialization of custom metrics: https://auto.gluon.ai/stable/tutorials/tabular/advanced/tabular-custom-metric.html#ensuring-metric-is-serializable

**Comment by Innixma** [comment]
As an example, the following code works for me without issue:

```python
import pandas as pd
import sklearn.metrics

from autogluon.tabular import TabularPredictor
from autogluon.core.metrics import make_scorer


if __name__ == '__main__':
    label = 'class'
    train_data = pd.read_csv('https://autogluon.s3.amazonaws.com/datasets/Inc/train.csv')
    subsample_size = 1000  # subsample subset of data for faster demo, try setting this to much larger values
    if subsample_size is not None and subsample_size < len(train_data):
        train_data = train_data.sample(n=subsample_size, random_state=0)
    test_data = pd.read_csv('https://autogluon.s3.amazonaws.com/datasets/Inc/test.csv')

    ag_accuracy_scorer = make_scorer(name='accuracy_custom',
                                     score_func=sklearn.metrics.accuracy_score,
                                     optimum=1,
                                     greater_is_better=True,
                                     needs_class=True)

    predictor = TabularPredictor(
        label=label,
        eval_metric=ag_accuracy_scorer,
    )

    predictor = predictor.fit(
        train_data=train_data,
        presets="good_quality",
        time_limit=30,
    )

    predictor.leaderboard(test_data, display=True)

    predictor_loaded = TabularPredictor.load(predictor.path)
    predictor_loaded.leaderboard(test_data, display=True)

```
