### ISSUE TITLE
Feature Selection in Tabular predictor failed when the number of trianing data is larger than the ''n_train_subsample' setting

### ISSUE THREAD

**Issue by jmren168** [autogluon/autogluon#4390]
Hi @Innixma 

When 'n_train_subsmaple' is set to 5000, and the number of train_data is larger than 5000, say, 40000, the following error is reported. 

### **Error messages**

File "C:\miniconda3\envs\ag100.tabular_mini\Lib\site-packages\autogluon\core\trainer\abstract_trainer.py", line 2583, in _proxy_model_feature_prune   
    candidate_features = selector.select_features(**feature_prune_kwargs, **model_fit_kwargs)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniconda3\envs\ag100.tabular_mini\Lib\site-packages\autogluon\core\utils\feature_selection.py", line 222, in select_features
    X, y, X_val, y_val, X_fi, y_fi, prune_threshold, noise_columns, feature_metadata = self.setup(
                                                                                       ^^^^^^^^^^^
  File "C:\miniconda3\envs\ag100.tabular_mini\Lib\site-packages\autogluon\core\utils\feature_selection.py", line 543, in setup
    X_train, _, y_train, _ = generate_train_test_split(X=X, y=y, problem_type=self.problem_type, random_state=random_state, test_size=drop_ratio)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^       
  File "C:\miniconda3\envs\ag100.tabular_mini\Lib\site-packages\autogluon\core\utils\utils.py", line 513, in generate_train_test_split
    random.seed(random_state)
  File "C:\miniconda3\envs\ag100.tabular_mini\Lib\random.py", line 160, in seed
    raise TypeError('The only supported seed types are: None,\n'
TypeError: The only supported seed types are: None,
int, float, str, bytes, and bytearray.

### **Environments**
Windows 10
Python 3.11
Autogluon 1.0.0

### **Reproduce Code**
PS. **please change the link to load a binary classificatin dataset which has more than 5000 data samples**

```
from autogluon.tabular import TabularDataset, TabularPredictor

train_data = TabularDataset('https://autogluon.s3.amazonaws.com/datasets/Inc/train.csv') 
# please change the link to a binary classification dataset which has more than 5000 data samples

save_path = r'.'
label = train_data.columns[-1]
train_data = train_data.drop(columns=label)

hyperparameter_tune_kwargs['num_trials'] = 5
# use lgbm for feature_prune
custom_model_hyperparameters = {'GBM':{}}

# Define feature_prune_kwargs
feature_prune_kwargs = {
    'n_train_subsample': 5000,
    'n_fi_subsample': 1000,
    'prune_ratio': 0.2,
    'stopping_round': 5,
    'min_improvement': 1e-6,
    'force_prune': True,
}

predictor = TabularPredictor(label=label, path=save_path).fit(
                                    train_data,
                                    hyperparameters=custom_model_hyperparameters, 
                                    hyperparameter_tune_kwargs=hyperparameter_tune_kwargs,
                                    feature_prune_kwargs=feature_prune_kwargs,
                                    verbosity=4)
```

**Comment by Innixma** [comment]
Hi @jmren168, I'm unable to reproduce the error. Your code provided is not directly runnable as `hyperparameter_tune_kwargs` is not defined and `label` is not present in `train_data` after dropping it. Can you please create a Colab notebook and share it here demonstrating the problem?

For reference, this altered code works for me:

```python
import pandas as pd
from autogluon.tabular import TabularPredictor


if __name__ == '__main__':
    from autogluon.tabular import TabularDataset, TabularPredictor

    train_data = TabularDataset('https://autogluon.s3.amazonaws.com/datasets/Inc/train.csv')
    # please change the link to a binary classification dataset which has more than 5000 data samples

    label = train_data.columns[-1]

    hyperparameter_tune_kwargs = {
        'num_trials': 5,
        'scheduler': 'local',
        'searcher': 'auto',
    }
    # use lgbm for feature_prune
    custom_model_hyperparameters = {'GBM': {}}

    # Define feature_prune_kwargs
    feature_prune_kwargs = {
        'n_train_subsample': 5000,
        'n_fi_subsample': 1000,
        'prune_ratio': 0.2,
        'stopping_round': 5,
        'min_improvement': 1e-6,
        'force_prune': True,
    }

    predictor = TabularPredictor(label=label).fit(
        train_data,
        hyperparameters=custom_model_hyperparameters,
        hyperparameter_tune_kwargs=hyperparameter_tune_kwargs,
        feature_prune_kwargs=feature_prune_kwargs,
        verbosity=4
    )
```

**Comment by jmren168** [comment]
It works on colab, however, it failed on local system, a little bit wired...

### **Colab (works)**

https://colab.research.google.com/drive/1EwmTrDtyfzD2QoZGKek8s14uE0tY599q?usp=sharing

### **Local System (failed)**

```
No path specified. Models will be saved in: "AutogluonModels\ag-20240816_044559"
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
        Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
        presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
        presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
        presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
        presets='medium_quality' : Fast training time, ideal for initial prototyping.
============ fit kwarg info ============
User Specified kwargs:
{'feature_prune_kwargs': {'force_prune': True,
                          'min_improvement': 1e-06,
                          'n_fi_subsample': 1000,
                          'n_train_subsample': 5000,
                          'prune_ratio': 0.2,
                          'stopping_round': 5},
 'hyperparameter_tune_kwargs': {'num_trials': 5,
                                'scheduler': 'local',
                                'searcher': 'auto'},
 'verbosity': 4}
Full kwargs:
{'_feature_generator_kwargs': None,
 '_save_bag_folds': None,
 'ag_args': None,
 'ag_args_ensemble': None,
 'ag_args_fit': None,
 'auto_stack': False,
 'calibrate': 'auto',
 'ds_args': {'clean_up_fits': True,
             'detection_time_frac': 0.25,
             'holdout_data': None,
             'holdout_frac': 0.1111111111111111,
             'memory_safe_fits': True,
             'n_folds': 2,
             'n_repeats': 1,
             'validation_procedure': 'holdout'},
 'excluded_model_types': None,
 'feature_generator': 'auto',
 'feature_prune_kwargs': {'force_prune': True,
                          'min_improvement': 1e-06,
                          'n_fi_subsample': 1000,
                          'n_train_subsample': 5000,
                          'prune_ratio': 0.2,
                          'stopping_round': 5},
 'holdout_frac': None,
 'hyperparameter_tune_kwargs': {'num_trials': 5,
                                'scheduler': 'local',
                                'searcher': 'auto'},
 'included_model_types': None,
 'keep_only_best': False,
 'name_suffix': None,
 'num_bag_folds': None,
 'num_bag_sets': None,
 'num_stack_levels': None,
 'pseudo_data': None,
 'refit_full': False,
 'save_space': False,
 'set_best_to_refit_full': False,
 'unlabeled_data': None,
 'use_bag_holdout': False,
 'verbosity': 4}
========================================
Warning: hyperparameter tuning is currently experimental and may cause the process to hang.
Saving AutogluonModels\ag-20240816_044559\learner.pkl
Saving AutogluonModels\ag-20240816_044559\predictor.pkl
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels\ag-20240816_044559"
=================== System Info ===================
AutoGluon Version:  1.0.0
Python Version:     3.11.8
Operating System:   Windows
Platform Machine:   AMD64
Platform Version:   10.0.19045
CPU Count:          8
GPU Count:          0
Memory Avail:       45.59 GB / 63.92 GB (71.3%)    
Disk Space Avail:   406.42 GB / 1863.01 GB (21.8%) 
===================================================
Train Data Rows:    10000
Train Data Columns: 40
Label Column:       y
AutoGluon infers your prediction problem is: 'binary' (because only two unique label-values observed).
        2 unique label values:  [0.0, 1.0]
        If 'binary' is not the correct problem_type, please manually specify the problem_type parameter during predictor init (You may specify problem_type as one of: ['binary', 'multiclass', 'regression'])
Problem Type:       binary
Preprocessing data ...
C:\miniconda3\envs\ag100.tabular_mini\Lib\site-packages\autogluon\tabular\learner\default_learner.py:189: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  X[self.label].replace([np.inf, -np.inf], np.nan, inplace=True)
Selected class <--> label mapping:  class 1 = 1, class 0 = 0
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
        Available Memory:                    46535.67 MB
        Train Data (Original)  Memory Usage: 3.05 MB (0.0% of available memory)
        Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes 
of the features.
        Stage 1 Generators:
                Fitting AsTypeFeatureGenerator...
                        Original Features (exact raw dtype, raw dtype):
                                ('float64', 'float') : 40 | ['x0', 'x1', 'x2', 'x3', 'x4', ...]
                        Types of features in original data (raw dtype, special dtypes):
                                ('float', []) : 40 | ['x0', 'x1', 'x2', 'x3', 'x4', ...]
                        Types of features in processed data (exact raw dtype, raw dtype):
                                ('float64', 'float') : 40 | ['x0', 'x1', 'x2', 'x3', 'x4', ...]
                        Types of features in processed data (raw dtype, special dtypes):
                                ('float', []) : 40 | ['x0', 'x1', 'x2', 'x3', 'x4', ...]
                        0.0s = Fit runtime
                        40 features in original data used to generate 40 features in processed data.
        Stage 2 Generators:
                Fitting FillNaFeatureGenerator...
                        Types of features in original data (raw dtype, special dtypes):
                                ('float', []) : 40 | ['x0', 'x1', 'x2', 'x3', 'x4', ...]
                        Types of features in processed data (exact raw dtype, raw dtype):
                                ('float64', 'float') : 40 | ['x0', 'x1', 'x2', 'x3', 'x4', ...]
                        Types of features in processed data (raw dtype, special dtypes):
                                ('float', []) : 40 | ['x0', 'x1', 'x2', 'x3', 'x4', ...]
                        0.0s = Fit runtime
                        40 features in original data used to generate 40 features in processed data.
        Stage 3 Generators:
                Fitting IdentityFeatureGenerator...
                        Types of features in original data (raw dtype, special dtypes):
                                ('float', []) : 40 | ['x0', 'x1', 'x2', 'x3', 'x4', ...]
                        Types of features in processed data (exact raw dtype, raw dtype):
                                ('float64', 'float') : 40 | ['x0', 'x1', 'x2', 'x3', 'x4', ...]
                        Types of features in processed data (raw dtype, special dtypes):
                                ('float', []) : 40 | ['x0', 'x1', 'x2', 'x3', 'x4', ...]
                        0.0s = Fit runtime
                        40 features in original data used to generate 40 features in processed data.
                Skipping CategoryFeatureGenerator: No input feature with required dtypes.
                Skipping DatetimeFeatureGenerator: No input feature with required dtypes.
                Skipping TextSpecialFeatureGenerator: No input feature with required dtypes.
                Skipping TextNgramFeatureGenerator: No input feature with required dtypes.
                Skipping IdentityFeatureGenerator: No input feature with required dtypes.
                Skipping IsNanFeatureGenerator: No input feature with required dtypes.
        Stage 4 Generators:
                Fitting DropUniqueFeatureGenerator...
                        Types of features in original data (raw dtype, special dtypes):
                                ('float', []) : 40 | ['x0', 'x1', 'x2', 'x3', 'x4', ...]
                        Types of features in processed data (exact raw dtype, raw dtype):
                                ('float64', 'float') : 40 | ['x0', 'x1', 'x2', 'x3', 'x4', ...]
                        Types of features in processed data (raw dtype, special dtypes):
                                ('float', []) : 40 | ['x0', 'x1', 'x2', 'x3', 'x4', ...]
                        0.0s = Fit runtime
                        40 features in original data used to generate 40 features in processed data.
        Stage 5 Generators:
                Fitting DropDuplicatesFeatureGenerator...
                        Types of features in original data (raw dtype, special dtypes):
                                ('float', []) : 40 | ['x0', 'x1', 'x2', 'x3', 'x4', ...]
                        Types of features in processed data (exact raw dtype, raw dtype):
                                ('float64', 'float') : 40 | ['x0', 'x1', 'x2', 'x3', 'x4', ...]
                        Types of features in processed data (raw dtype, special dtypes):
                                ('float', []) : 40 | ['x0', 'x1', 'x2', 'x3', 'x4', ...]
                        0.2s = Fit runtime
                        40 features in original data used to generate 40 features in processed data.
        Types of features in original data (exact raw dtype, raw dtype):
                ('float64', 'float') : 40 | ['x0', 'x1', 'x2', 'x3', 'x4', ...]
        Types of features in original data (raw dtype, special dtypes):
                ('float', []) : 40 | ['x0', 'x1', 'x2', 'x3', 'x4', ...]
        Types of features in processed data (exact raw dtype, raw dtype):
                ('float64', 'float') : 40 | ['x0', 'x1', 'x2', 'x3', 'x4', ...]
        Types of features in processed data (raw dtype, special dtypes):
                ('float', []) : 40 | ['x0', 'x1', 'x2', 'x3', 'x4', ...]
        0.4s = Fit runtime
        40 features in original data used to generate 40 features in processed data.
        Train Data (Processed) Memory Usage: 3.05 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.44s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
        To change this, specify the eval_metric parameter of Predictor()
Saving AutogluonModels\ag-20240816_044559\learner.pkl
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 8000, Val Rows: 2000
User-specified model hyperparameters to be fit:
{
        'GBM': {},
}
Saving AutogluonModels\ag-20240816_044559\utils\data\X.pkl
Saving AutogluonModels\ag-20240816_044559\utils\data\y.pkl
Saving AutogluonModels\ag-20240816_044559\utils\data\X_val.pkl
Saving AutogluonModels\ag-20240816_044559\utils\data\y_val.pkl
Model configs that will be trained (in order):
        LightGBM:       {'ag_args': {'hyperparameter_tune_kwargs': {'num_trials': 5, 'scheduler': 'local', 'searcher': 'auto'}, 'model_type': <class 'autogluon.tabular.models.lgb.lgb_model.LGBModel'>, 'priority': 90}}
Fitting 1 L1 models ...
Hyperparameter tuning model: LightGBM ...
        Dropped 0 of 40 features.
        Fitting LightGBM with 'num_gpus': 0, 'num_cpus': 4
custom backend resource: {'num_gpus': 0, 'num_cpus': 4}, per trial resource: {'num_trials': 5, 'scheduler': 'local', 'searcher': 'auto', 'resources_per_trial': {'num_cpus': 4, 'num_gpus': 0.0}}
Starting generic AbstractModel hyperparameter tuning for LightGBM model...
        Hyperparameter search space for LightGBM:
learning_rate:   Real: lower=0.005, upper=0.2
feature_fraction:   Real: lower=0.75, upper=1.0
min_data_in_leaf:   Int: lower=2, upper=60
num_leaves:   Int: lower=16, upper=96
  0%|                                                                                                   | 0/5 [00:00<?, ?it/s]Loading: AutogluonModels\ag-20240816_044559\models\LightGBM\dataset_train.pkl
Loading: AutogluonModels\ag-20240816_044559\models\LightGBM\dataset_val.pkl
        Dropped 0 of 40 features.
        Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.05, 'feature_fraction': 1.0, 'min_data_in_leaf': 20, 'num_leaves': 31}
Saving AutogluonModels\ag-20240816_044559\models\LightGBM\T1\model.pkl
 20%|██████████████████▏                                                                        | 1/5 [00:02<00:11,  2.99s/it]Loading: AutogluonModels\ag-20240816_044559\models\LightGBM\dataset_train.pkl
Loading: AutogluonModels\ag-20240816_044559\models\LightGBM\dataset_val.pkl
        Dropped 0 of 40 features.
        Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.06994332504138302, 'feature_fraction': 0.8872033759818312, 'min_data_in_leaf': 5, 'num_leaves': 83}
Saving AutogluonModels\ag-20240816_044559\models\LightGBM\T2\model.pkl
 40%|████████████████████████████████████▍                                                      | 2/5 [00:05<00:08,  2.70s/it]Loading: AutogluonModels\ag-20240816_044559\models\LightGBM\dataset_train.pkl
Loading: AutogluonModels\ag-20240816_044559\models\LightGBM\dataset_val.pkl
        Dropped 0 of 40 features.
        Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.049883446878335284, 'feature_fraction': 0.9618129346960314, 'min_data_in_leaf': 52, 'num_leaves': 52}
Saving AutogluonModels\ag-20240816_044559\models\LightGBM\T3\model.pkl
 60%|██████████████████████████████████████████████████████▌                                    | 3/5 [00:07<00:04,  2.24s/it]Loading: AutogluonModels\ag-20240816_044559\models\LightGBM\dataset_train.pkl
Loading: AutogluonModels\ag-20240816_044559\models\LightGBM\dataset_val.pkl
        Dropped 0 of 40 features.
        Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.006163502781172818, 'feature_fraction': 0.824383651636118, 'min_data_in_leaf': 14, 'num_leaves': 74}
Saving AutogluonModels\ag-20240816_044559\models\LightGBM\T4\model.pkl
 80%|████████████████████████████████████████████████████████████████████████▊                  | 4/5 [00:09<00:02,  2.26s/it]Loading: AutogluonModels\ag-20240816_044559\models\LightGBM\dataset_train.pkl
Loading: AutogluonModels\ag-20240816_044559\models\LightGBM\dataset_val.pkl
        Dropped 0 of 40 features.
        Fitting 10000 rounds... Hyperparameters: {'learning_rate': 0.1000260297171191, 'feature_fraction': 0.8694162793303375, 
'min_data_in_leaf': 48, 'num_leaves': 53}
Saving AutogluonModels\ag-20240816_044559\models\LightGBM\T5\model.pkl
100%|███████████████████████████████████████████████████████████████████████████████████████████| 5/5 [00:10<00:00,  2.19s/it]
Time for LightGBM model HPO: 10.997283458709717
Best hyperparameter configuration for LightGBM model:
{'learning_rate': 0.05, 'feature_fraction': 1.0, 'min_data_in_leaf': 20, 'num_leaves': 31}
Loading: AutogluonModels\ag-20240816_044559\models\LightGBM\T1\model.pkl
Fitted model: LightGBM\T1 ...
        0.5195   = Validation score   (accuracy)
        2.95s    = Training   runtime
        0.01s    = Validation runtime
Loading: AutogluonModels\ag-20240816_044559\models\LightGBM\T2\model.pkl
Fitted model: LightGBM\T2 ...
        0.5085   = Validation score   (accuracy)
        2.46s    = Training   runtime
        0.0s     = Validation runtime
Loading: AutogluonModels\ag-20240816_044559\models\LightGBM\T3\model.pkl
Fitted model: LightGBM\T3 ...
        0.5115   = Validation score   (accuracy)
        1.65s    = Training   runtime
        0.0s     = Validation runtime
Loading: AutogluonModels\ag-20240816_044559\models\LightGBM\T4\model.pkl
Fitted model: LightGBM\T4 ...
        0.513    = Validation score   (accuracy)
        2.27s    = Training   runtime
        0.0s     = Validation runtime
Loading: AutogluonModels\ag-20240816_044559\models\LightGBM\T5\model.pkl
Fitted model: LightGBM\T5 ...
        0.519    = Validation score   (accuracy)
        1.46s    = Training   runtime
        0.0s     = Validation runtime
Saving AutogluonModels\ag-20240816_044559\models\trainer.pkl
Loading: AutogluonModels\ag-20240816_044559\models\LightGBM\T1\model.pkl
Performing feature pruning with model: FeatureSelector_LightGBM\T1, total time limit: 300s, stop threshold: 5, prune ratio: 0.2, prune threshold: noise.
        Number of training samples 8000 is greater than 5000. Using 5000 samples as training data.
Traceback (most recent call last):
  File "path\to\project\test_fs.py", line 39, in <module>
    hyperparameter_tune_kwargs=hyperparameter_tune_kwargs,
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniconda3\envs\ag100.tabular_mini\Lib\site-packages\autogluon\core\utils\decorators.py", line 31, in _call
    return f(*gargs, **gkwargs)
           ^^^^^^^^^^^^^^^^^^^^
  File "C:\miniconda3\envs\ag100.tabular_mini\Lib\site-packages\autogluon\tabular\predictor\predictor.py", line 1109, in fit   
    self._fit(ag_fit_kwargs=ag_fit_kwargs, ag_post_fit_kwargs=ag_post_fit_kwargs)
  File "C:\miniconda3\envs\ag100.tabular_mini\Lib\site-packages\autogluon\tabular\predictor\predictor.py", line 1115, in _fit  
    self._learner.fit(**ag_fit_kwargs)
  File "C:\miniconda3\envs\ag100.tabular_mini\Lib\site-packages\autogluon\tabular\learner\abstract_learner.py", line 159, in fit
    return self._fit(X=X, X_val=X_val, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniconda3\envs\ag100.tabular_mini\Lib\site-packages\autogluon\tabular\learner\default_learner.py", line 128, in _fit
    trainer.fit(
  File "C:\miniconda3\envs\ag100.tabular_mini\Lib\site-packages\autogluon\tabular\trainer\auto_trainer.py", line 125, in fit   
    self._train_multi_and_ensemble(
  File "C:\miniconda3\envs\ag100.tabular_mini\Lib\site-packages\autogluon\core\trainer\abstract_trainer.py", line 2503, in _train_multi_and_ensemble
    model_names_fit = self.train_multi_levels(
                      ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniconda3\envs\ag100.tabular_mini\Lib\site-packages\autogluon\core\trainer\abstract_trainer.py", line 388, in train_multi_levels
    base_model_names, aux_models = self.stack_new_level(
                                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniconda3\envs\ag100.tabular_mini\Lib\site-packages\autogluon\core\trainer\abstract_trainer.py", line 536, in stack_new_level
    core_models = self.stack_new_level_core(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniconda3\envs\ag100.tabular_mini\Lib\site-packages\autogluon\core\trainer\abstract_trainer.py", line 666, in stack_new_level_core
    return self._train_multi(
           ^^^^^^^^^^^^^^^^^^
  File "C:\miniconda3\envs\ag100.tabular_mini\Lib\site-packages\autogluon\core\trainer\abstract_trainer.py", line 2453, in _train_multi
    model_names_trained = self._train_multi_initial(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniconda3\envs\ag100.tabular_mini\Lib\site-packages\autogluon\core\trainer\abstract_trainer.py", line 2336, in _train_multi_initial
    candidate_features = self._proxy_model_feature_prune(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniconda3\envs\ag100.tabular_mini\Lib\site-packages\autogluon\core\trainer\abstract_trainer.py", line 2583, in _proxy_model_feature_prune
    candidate_features = selector.select_features(**feature_prune_kwargs, **model_fit_kwargs)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\miniconda3\envs\ag100.tabular_mini\Lib\site-packages\autogluon\core\utils\feature_selection.py", line 222, in select_features
ypes are: None,
int, float, str, bytes, and bytearray.
```

### **Reproduce Codes**

```
from autogluon.tabular import TabularDataset, TabularPredictor
import pandas as pd
import numpy as np

data_num=10000
feature_num=40

train_data = np.random.random((data_num, feature_num))
y = np.random.randint(0,2,data_num)

train_data = np.hstack((train_data, y.reshape(-1,1)))
cols = ['x'+str(_) for _ in range(feature_num)] + ['y']

train_data = pd.DataFrame(train_data, columns=cols)

label = train_data.columns[-1]

hyperparameter_tune_kwargs = {
    'num_trials': 5,
    'scheduler': 'local',
    'searcher': 'auto',
}
# use lgbm for feature_prune
custom_model_hyperparameters = {'GBM': {}}

# Define feature_prune_kwargs
feature_prune_kwargs = {
    'n_train_subsample': 5000,
    'n_fi_subsample': 1000,
    'prune_ratio': 0.2,
    'stopping_round': 5,
    'min_improvement': 1e-6,
    'force_prune': True,
}

predictor = TabularPredictor(label=label).fit(
    train_data,
    hyperparameters=custom_model_hyperparameters,
    hyperparameter_tune_kwargs=hyperparameter_tune_kwargs,
    feature_prune_kwargs=feature_prune_kwargs,
    verbosity=4
)
```

**Comment by Innixma** [comment]
@jmren168 Can you try upgrading your local AutoGluon install? You are using AutoGluon 1.0, but the latest AutoGluon release is 1.1.1. The latest release might fix the error.

**Comment by Innixma** [comment]
Otherwise because we can't get a reproducible example, it might be that your environment is non-standard or it is related to using Windows OS. Hard to say.

**Comment by Innixma** [comment]
@jmren168 Actually, I took a dive into this, I think I have implemented a fix in #4405.

Please give it a try. I am pretty confident it should fix the issue, as the problem is related to Windows OS.

**Comment by jmren168** [comment]
@Innixma Thanks for the quick reply.

So far I test several python environments; the problem is related to virtual environments: Anaconda or Miniconda.

### **Environment 1 works**
OS: Windows 10
Autogluon: 1.0.0
**Conda: Anaconda** 
Python: 3.10

### **Environment 2 failed**
OS: Windows 10
Autogluon.tabular: 1.0.0
**Conda: Miniconda**
Python: 3.11

### **Environment 3 works**
OS: Windows 10
Autogluon: 0.8.2
**Conda: Aanconda**
Python: 3.9

### **Environment 4 failed**
OS: Windows 10
Autogluon: 1.0.0
**Conda: Miniconda**
Python: 3.10

I think the problem is really related to conda environments, rather than autogluon version. 

I may give a try on the latest autogluon 1.1.1 on miniconda environments. 

Please let me know whatever I could do to help fix this bug. Many thanks.

**Comment by jmren168** [comment]
@Innixma

Any comments about my tries? Many thanks.

**Comment by Innixma** [comment]
@jmren168 please wait 24 hours, then try:

```
pip install --pre autogluon
```

with a fresh Python environment. Hopefully #4405 fixed this.

**Comment by jmren168** [comment]
@Innixma Hi, 
Any schedule about releasing autogluon 1.2?

**Comment by Innixma** [comment]
@jmren168 Probably November
