### ISSUE TITLE
[BUG] RaySystemError: System error: Failed to unpickle serialized exception

### ISSUE THREAD

**Issue by celestinoxp** [autogluon/autogluon#4702]
**Bug Report Checklist**

**Describe the bug**

Using many columns ex: 11000 the ray reproduces an error related to catboost...

The error is confusing, because the root of the problem is the number of columns (many)... if you use, for example, only 1,000 there are no errors, but 11,000 the error appears...

![image](https://github.com/user-attachments/assets/aa6e29ec-7480-472f-a217-4be0bbb81f14)

```python
Skipping CatBoost_r177_BAG_L1 due to exception: RaySystemError: System error: Failed to unpickle serialized exception
traceback: Traceback (most recent call last):
  File "[C:\Users\celes\anaconda3\Lib\site-packages\ray\exceptions.py", line 51](file:///C:/Users/celes/anaconda3/Lib/site-packages/ray/exceptions.py#line=50), in from_ray_exception
    return pickle.loads(ray_exception.serialized_exception)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_catboost'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "[C:\Users\celes\anaconda3\Lib\site-packages\ray\_private\serialization.py", line 460](file:///C:/Users/celes/anaconda3/Lib/site-packages/ray/_private/serialization.py#line=459), in deserialize_objects
    obj = self._deserialize_object(data, metadata, object_ref)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[C:\Users\celes\anaconda3\Lib\site-packages\ray\_private\serialization.py", line 342](file:///C:/Users/celes/anaconda3/Lib/site-packages/ray/_private/serialization.py#line=341), in _deserialize_object
    return RayError.from_bytes(obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "[C:\Users\celes\anaconda3\Lib\site-packages\ray\exceptions.py", line 45](file:///C:/Users/celes/anaconda3/Lib/site-packages/ray/exceptions.py#line=44), in from_bytes
    return RayError.from_ray_exception(ray_exception)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[C:\Users\celes\anaconda3\Lib\site-packages\ray\exceptions.py", line 54](file:///C:/Users/celes/anaconda3/Lib/site-packages/ray/exceptions.py#line=53), in from_ray_exception
    raise RuntimeError(msg) from e
RuntimeError: Failed to unpickle serialized exception
```

**Expected behavior**

**To Reproduce**

```python
import pandas as pd
import numpy as np
from autogluon.tabular import TabularPredictor

# dataset 11.000 columns and 1.000 rows
num_rows = 1000
num_columns = 11000
data = pd.DataFrame(np.random.rand(num_rows, num_columns), columns=[f'col_{i}' for i in range(num_columns)])

# create column with 's', 'd' or 'i' values
data['n2_sdi'] = np.random.choice(['s', 'd', 'i'], size=num_rows)

# convert data type from object to category
data['n2_sdi'] = data['n2_sdi'].astype('category')

# define the target column
target_column = 'n2_sdi'

predictor = TabularPredictor(label=target_column, path='autogluon_ray_investigation')
predictor.fit(
    train_data=data,
    presets='best_quality',
    hyperparameters={'CAT': {}},  # only catBoost to investigate
    time_limit=1000
)
```

**Screenshots / Logs**

**Installed Versions**

<details>

```python
NSTALLED VERSIONS
------------------
date                : 2024-11-28
time                : 14:07:47.346096
python              : 3.11.9.final.0
OS                  : Windows
OS-release          : 10
Version             : 10.0.22631
machine             : AMD64
processor           : AMD64 Family 23 Model 96 Stepping 1, AuthenticAMD
num_cores           : 16
cpu_ram_mb          : 32175.171875
cuda version        : None
num_gpus            : 1
gpu_ram_mb          : [3935]
avail_disk_size_mb  : None

autogluon           : None
autogluon.common    : 1.2
autogluon.core      : 1.2
autogluon.features  : 1.2
autogluon.tabular   : 1.2
boto3               : 1.35.55
catboost            : 1.2.7
einops              : 0.8.0
fastai              : 2.7.18
huggingface-hub     : 0.26.3
hyperopt            : 0.2.7
imodels             : 2.0.0
lightgbm            : 4.5.0.99
matplotlib          : 3.10.0rc1
networkx            : 3.4.2
numpy               : 1.26.4
onnx                : 1.17.0
onnxruntime         : 1.20.1
onnxruntime-gpu     : 1.20.1
pandas              : 2.2.3
psutil              : 6.1.0
pyarrow             : 18.0.0
ray                 : 2.39.0
requests            : 2.28.2
scikit-learn        : 1.5.2
scikit-learn-intelex: 2025.0.0
scipy               : 1.14.1
skl2onnx            : 1.17.0
spacy               : 3.8.2
tabpfn              : 0.1.10
torch               : 2.6.0.dev20241127+cu118
tqdm                : 4.65.2
vowpalwabbit        : None
xgboost             : 2.1.3
```

</details>

**Comment by rsj123** [comment]
I think you're having the same problem as me.
#3249

**Comment by celestinoxp** [comment]
@Innixma can you help investigate this case? From what I've researched, I'm not the only one with this problem.

Some points that I think are important:
- I'm using the latest version of autogluon.tabular, ray and catboost
- the problem only occurs with catboost
- with little training time the problem doesn't appear (maybe because there isn't time to go through all the steps), so in my case it happens after 2 hours or more of training.
- I'm using the new experimental_quality
- will the problem be the autogluon or the ray? (or from catboost?)
- why underscore catboost (_catboost) ?

What does the error mean: Failed to unpickle serialized exception

the problem is in deserialize_objects function of ray? see https://github.com/ray-project/ray/blob/master/python/ray/_private/serialization.py#L449

**Comment by celestinoxp** [comment]
UPDATE: I think I found the root of the problem but I'm not sure and I would like someone to help investigate... in my project I have a dataset with many columns, so as I can't publish the original code, I created a similar reproducible code:

```python
import pandas as pd
import numpy as np
from autogluon.tabular import TabularPredictor

# dataset 11.000 columns and 1.000 rows
num_rows = 1000
num_columns = 11000
data = pd.DataFrame(np.random.rand(num_rows, num_columns), columns=[f'col_{i}' for i in range(num_columns)])

# create column with 's', 'd' or 'i' values
data['n2_sdi'] = np.random.choice(['s', 'd', 'i'], size=num_rows)

# convert data type from object to category
data['n2_sdi'] = data['n2_sdi'].astype('category')

# define the target column
target_column = 'n2_sdi'

predictor = TabularPredictor(label=target_column, path='autogluon_ray_investigation')
predictor.fit(
    train_data=data,
    presets='best_quality',
    hyperparameters={'CAT': {}},  # only catBoost to investigate
    time_limit=1000
)
```

**Comment by celestinoxp** [comment]
> I think you're having the same problem as me. #3249

@rsj123 what is the size of your dataset?

**Comment by celestinoxp** [comment]
I found a related problem in catboost github,  https://github.com/catboost/catboost/issues/2752

**Comment by celestinoxp** [comment]
@Innixma any idea how to fix it?

**Comment by celestinoxp** [comment]
I updated Ray to version 2.40.0 released 10 hours ago, and it seems to have resolved the issue...
