### ISSUE TITLE
[BUG] custom metric with weights - error from xgboost

### ISSUE THREAD

**Issue by mglowacki100** [autogluon/autogluon#4724]
**Describe the bug**
I wanted to train regression model with custom metric that uses weight:

```
def ma_map(y_true, y_pred, sample_weight):
    return np.mean(sample_weight*np.abs(y_true - y_pred))

custom_metric = make_scorer(name='custom_metric',
                            score_func=ma_map,
                            optimum=0,
                            greater_is_better=False, 
                            )
```
unfortunately during training, I've got error from xgboost:

```Fitting model: XGBoost ...
	Warning: Exception caused XGBoost to fail during training... Skipping this model.
		ma_map() missing 1 required positional argument: 'sample_weight'
```
In documentation (https://auto.gluon.ai/stable/tutorials/tabular/advanced/tabular-custom-metric.html) there is no example with weight, so maybe this just a wrong usage. If this is a case then example with proper usage should be added.

**To Reproduce**
```
!pip install autogluon.tabular
from autogluon.tabular import TabularDataset, TabularPredictor
from autogluon.core.metrics import make_scorer
import numpy as np
import pandas as pd

# Set random seed for reproducibility
np.random.seed(42)

# Number of samples
n_samples = 1000

# Generate features
X1 = np.random.uniform(0, 10, n_samples)  # Feature 1: Uniformly distributed
X2 = np.random.normal(5, 2, n_samples)   # Feature 2: Normally distributed
X3 = np.random.randint(0, 2, n_samples)  # Feature 3: Binary feature (e.g., 0 or 1)

# Generate target with some noise
y = 3 * X1 + 2 * X2 - 5 * X3 + np.random.normal(0, 2, n_samples)

# Combine into a DataFrame
data = pd.DataFrame({
    'X1': X1,
    'X2': X2,
    'X3': X3,
    'y': y
})
data['weights'] = 1

train_data = TabularDataset(data)
label='y'

hyperparameters = {'XGB': {}}

def ma_map(y_true, y_pred, sample_weight):
    return np.mean(sample_weight*np.abs(y_true - y_pred))

custom_metric = make_scorer(name='custom_metric',
                            score_func=ma_map,
                            optimum=0,
                            greater_is_better=False, 
                            )

predictor = TabularPredictor(label=label,
                             problem_type='regression',
                             sample_weight='weights',
                             weight_evaluation=True,
                             eval_metric=custom_metric).fit(train_data, hyperparameters=hyperparameters)

```
https://colab.research.google.com/drive/1fH_HDotVQRE-dzdnKLQryZaMMMAfufmr#scrollTo=bWjx_jERZBUE

**Screenshots / Logs**
```
No path specified. Models will be saved in: "AutogluonModels/ag-20241209_124718"
Verbosity: 2 (Standard Logging)
=================== System Info ===================
AutoGluon Version:  1.2
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #1 SMP PREEMPT_DYNAMIC Thu Jun 27 21:05:47 UTC 2024
CPU Count:          2
Memory Avail:       11.13 GB / 12.67 GB (87.8%)
Disk Space Avail:   75.03 GB / 107.72 GB (69.7%)
===================================================
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets. Defaulting to `'medium'`...
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='experimental' : New in v1.2: Pre-trained foundation model + parallel fits. The absolute best accuracy without consideration for inference speed. Does not support GPU.
	presets='best'         : Maximize accuracy. Recommended for most users. Use in competitions and benchmarks.
	presets='high'         : Strong accuracy with fast inference speed.
	presets='good'         : Good accuracy with very fast inference speed.
	presets='medium'       : Fast training time, ideal for initial prototyping.
Values in column 'weights' used as sample weights instead of predictive features. Evaluation will report weighted metrics, so ensure same column exists in test data.
Beginning AutoGluon training ...
AutoGluon will save models to "/content/AutogluonModels/ag-20241209_124718"
Train Data Rows:    1000
Train Data Columns: 4
Label Column:       y
Problem Type:       regression
Preprocessing data ...
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    11400.14 MB
	Train Data (Original)  Memory Usage: 0.02 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('float', []) : 2 | ['X1', 'X2']
		('int', [])   : 1 | ['X3']
	Types of features in processed data (raw dtype, special dtypes):
		('float', [])     : 2 | ['X1', 'X2']
		('int', ['bool']) : 1 | ['X3']
	0.1s = Fit runtime
	3 features in original data used to generate 3 features in processed data.
	Train Data (Processed) Memory Usage: 0.02 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.12s ...
AutoGluon will gauge predictive performance using evaluation metric: 'custom_metric'
	This metric's sign has been flipped to adhere to being higher_is_better. The metric score can be multiplied by -1 to get the metric value.
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 800, Val Rows: 200
User-specified model hyperparameters to be fit:
{
	'XGB': [{}],
}
Fitting 1 L1 models, fit_strategy="sequential" ...
Fitting model: XGBoost ...
	Warning: Exception caused XGBoost to fail during training... Skipping this model.
		ma_map() missing 1 required positional argument: 'sample_weight'
Detailed Traceback:
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/autogluon/core/trainer/abstract_trainer.py", line 2106, in _train_and_save
    model = self._train_single(**model_fit_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/autogluon/core/trainer/abstract_trainer.py", line 1993, in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, X_test=X_test, y_test=y_test, total_resources=total_resources, **model_fit_kwargs)
  File "/usr/local/lib/python3.10/dist-packages/autogluon/core/models/abstract/abstract_model.py", line 925, in fit
    out = self._fit(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/autogluon/tabular/models/xgboost/xgboost_model.py", line 194, in _fit
    self.model.fit(X=X, y=y, eval_set=eval_set, verbose=False, sample_weight=sample_weight)
  File "/usr/local/lib/python3.10/dist-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xgboost/sklearn.py", line 1108, in fit
    self._Booster = train(
  File "/usr/local/lib/python3.10/dist-packages/xgboost/core.py", line 726, in inner_f
    return func(**kwargs)
  File "/usr/local/lib/python3.10/dist-packages/xgboost/training.py", line 182, in train
    if cb_container.after_iteration(bst, i, dtrain, evals):
  File "/usr/local/lib/python3.10/dist-packages/xgboost/callback.py", line 258, in after_iteration
    score: str = model.eval_set(evals, epoch, self.metric, self._output_margin)
  File "/usr/local/lib/python3.10/dist-packages/xgboost/core.py", line 2225, in eval_set
    feval_ret = feval(
  File "/usr/local/lib/python3.10/dist-packages/xgboost/sklearn.py", line 151, in inner
    return func.__name__, func(y_true, y_score)
  File "/usr/local/lib/python3.10/dist-packages/autogluon/tabular/models/xgboost/xgboost_utils.py", line 71, in custom_metric
    return sign * metric(y_true, y_hat)
  File "/usr/local/lib/python3.10/dist-packages/autogluon/core/metrics/__init__.py", line 97, in __call__
    return self._score(y_true=y_true, y_pred=y_pred, **k)
  File "/usr/local/lib/python3.10/dist-packages/autogluon/core/metrics/__init__.py", line 135, in _score
    return self._sign * self._score_func(y_true, y_pred, **kwargs)
TypeError: ma_map() missing 1 required positional argument: 'sample_weight'
No base models to train on, skipping auxiliary stack level 2...
Warning: AutoGluon did not successfully train any models
AutoGluon training complete, total runtime = 0.52s ... Best model: None
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
[<ipython-input-37-bdae215efbc3>](https://localhost:8080/#) in <cell line: 1>()
----> 1 predictor = TabularPredictor(label=label,
      2                              problem_type='regression',
      3                              sample_weight='weights',
      4                              weight_evaluation=True,
      5                              eval_metric=custom_metric).fit(train_data, hyperparameters=hyperparameters)

3 frames
[/usr/local/lib/python3.10/dist-packages/autogluon/core/utils/decorators.py](https://localhost:8080/#) in _call(*args, **kwargs)
     29         def _call(*args, **kwargs):
     30             gargs, gkwargs = g(*other_args, *args, **kwargs)
---> 31             return f(*gargs, **gkwargs)
     32 
     33         return _call

[/usr/local/lib/python3.10/dist-packages/autogluon/tabular/predictor/predictor.py](https://localhost:8080/#) in fit(self, train_data, tuning_data, time_limit, presets, hyperparameters, feature_metadata, infer_limit, infer_limit_batch_size, fit_weighted_ensemble, fit_full_last_level_weighted_ensemble, full_weighted_ensemble_additionally, dynamic_stacking, calibrate_decision_threshold, num_cpus, num_gpus, fit_strategy, memory_limit, callbacks, **kwargs)
   1297         self._fit_strategy = fit_strategy
   1298 
-> 1299         self._fit(ag_fit_kwargs=ag_fit_kwargs, ag_post_fit_kwargs=ag_post_fit_kwargs)
   1300 
   1301         return self

[/usr/local/lib/python3.10/dist-packages/autogluon/tabular/predictor/predictor.py](https://localhost:8080/#) in _fit(self, ag_fit_kwargs, ag_post_fit_kwargs)
   1305         self._learner.fit(**ag_fit_kwargs)
   1306         self._set_post_fit_vars()
-> 1307         self._post_fit(**ag_post_fit_kwargs)
   1308         self.save()
   1309 

[/usr/local/lib/python3.10/dist-packages/autogluon/tabular/predictor/predictor.py](https://localhost:8080/#) in _post_fit(self, keep_only_best, refit_full, set_best_to_refit_full, save_space, calibrate, calibrate_decision_threshold, infer_limit, num_cpus, num_gpus, refit_full_kwargs, fit_strategy, raise_on_no_models_fitted)
   1628         if not self.model_names():
   1629             if raise_on_no_models_fitted:
-> 1630                 raise RuntimeError(
   1631                     "No models were trained successfully during fit()."
   1632                     " Inspect the log output or increase verbosity to determine why no models were fit."

RuntimeError: No models were trained successfully during fit(). Inspect the log output or increase verbosity to determine why no models were fit. Alternatively, set `raise_on_no_models_fitted` to False during the fit call.
```
<details>

```python
INSTALLED VERSIONS
------------------
date                : 2024-12-09
time                : 12:48:23.493790
python              : 3.10.12.final.0
OS                  : Linux
OS-release          : 6.1.85+
Version             : #1 SMP PREEMPT_DYNAMIC Thu Jun 27 21:05:47 UTC 2024
machine             : x86_64
processor           : x86_64
num_cores           : 2
cpu_ram_mb          : 12978.96484375
cuda version        : None
num_gpus            : 0
gpu_ram_mb          : []
avail_disk_size_mb  : 76834

autogluon           : None
autogluon.common    : 1.2
autogluon.core      : 1.2
autogluon.features  : 1.2
autogluon.tabular   : 1.2
boto3               : 1.35.76
catboost            : None
einops              : 0.8.0
fastai              : 2.7.18
huggingface-hub     : 0.26.3
hyperopt            : 0.2.7
imodels             : None
lightgbm            : 4.5.0
matplotlib          : 3.8.0
networkx            : 3.4.2
numpy               : 1.26.4
onnx                : None
onnxruntime         : None
onnxruntime-gpu     : None
pandas              : 2.2.2
psutil              : 5.9.5
pyarrow             : 17.0.0
ray                 : None
requests            : 2.32.3
scikit-learn        : 1.5.2
scikit-learn-intelex: None
scipy               : 1.13.1
skl2onnx            : None
spacy               : 3.7.5
tabpfn              : None
torch               : 2.5.1+cu121
tqdm                : 4.66.6
vowpalwabbit        : None
xgboost             : 2.1.3
```

</details>

**Comment by mglowacki100** [comment]
This modification of custom metric removes error, but I'm not sure if `sample_weight` is used by xgboost.
```
def ma_map(y_true, y_pred, sample_weight=None):
    if sample_weight is None:
        sample_weight = np.ones_like(y_true)
    return np.mean(sample_weight*np.abs(y_true - y_pred))
```
