### ISSUE TITLE
[BUG][tabular] Catboost error: bad allocation

### ISSUE THREAD

**Issue by celestinoxp** [autogluon/autogluon#4738]
Using autogluon.tabular 1.2 with a normal code:

```python
predictor = TabularPredictor(
    label="linha7",
    path="modelos/linha7",
    eval_metric="log_loss"
).fit(
    train_data=dados_treino_linha7,
    presets='experimental_quality',
    excluded_model_types=['KNN', 'XT', 'RF'], # Remove low scores
    ds_args={'enable_ray_logging': False},
    num_gpus = 1,
    time_limit = 5 * 3600
)
```

i give this message error:

```python
Warning: Exception caused CatBoost_BAG_L1 to fail during training... Skipping this model.
		bad allocation
Detailed Traceback:
Traceback (most recent call last):
  File "[C:\Users\celes\anaconda3\Lib\site-packages\autogluon\core\trainer\abstract_trainer.py", line 2106](file:///C:/Users/celes/anaconda3/Lib/site-packages/autogluon/core/trainer/abstract_trainer.py#line=2105), in _train_and_save
    model = self._train_single(**model_fit_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[C:\Users\celes\anaconda3\Lib\site-packages\autogluon\core\trainer\abstract_trainer.py", line 1993](file:///C:/Users/celes/anaconda3/Lib/site-packages/autogluon/core/trainer/abstract_trainer.py#line=1992), in _train_single
    model = model.fit(X=X, y=y, X_val=X_val, y_val=y_val, X_test=X_test, y_test=y_test, total_resources=total_resources, **model_fit_kwargs)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[C:\Users\celes\anaconda3\Lib\site-packages\autogluon\core\models\abstract\abstract_model.py", line 925](file:///C:/Users/celes/anaconda3/Lib/site-packages/autogluon/core/models/abstract/abstract_model.py#line=924), in fit
    out = self._fit(**kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "[C:\Users\celes\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\stacker_ensemble_model.py", line 270](file:///C:/Users/celes/anaconda3/Lib/site-packages/autogluon/core/models/ensemble/stacker_ensemble_model.py#line=269), in _fit
    return super()._fit(X=X, y=y, time_limit=time_limit, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[C:\Users\celes\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\bagged_ensemble_model.py", line 298](file:///C:/Users/celes/anaconda3/Lib/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py#line=297), in _fit
    self._fit_folds(
  File "[C:\Users\celes\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\bagged_ensemble_model.py", line 724](file:///C:/Users/celes/anaconda3/Lib/site-packages/autogluon/core/models/ensemble/bagged_ensemble_model.py#line=723), in _fit_folds
    fold_fitting_strategy.after_all_folds_scheduled()
  File "[C:\Users\celes\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\fold_fitting_strategy.py", line 317](file:///C:/Users/celes/anaconda3/Lib/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py#line=316), in after_all_folds_scheduled
    self._fit_fold_model(job)
  File "[C:\Users\celes\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\fold_fitting_strategy.py", line 322](file:///C:/Users/celes/anaconda3/Lib/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py#line=321), in _fit_fold_model
    fold_model = self._fit(self.model_base, time_start_fold, time_limit_fold, fold_ctx, self.model_base_kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "[C:\Users\celes\anaconda3\Lib\site-packages\autogluon\core\models\ensemble\fold_fitting_strategy.py", line 358](file:///C:/Users/celes/anaconda3/Lib/site-packages/autogluon/core/models/ensemble/fold_fitting_strategy.py#line=357), in _fit
    fold_model.fit(X=X_fold, y=y_fold, X_val=X_val_fold, y_val=y_val_fold, time_limit=time_limit_fold, num_cpus=num_cpus, num_gpus=num_gpus, **kwargs_fold)
  File "[C:\Users\celes\anaconda3\Lib\site-packages\autogluon\core\models\abstract\abstract_model.py", line 925](file:///C:/Users/celes/anaconda3/Lib/site-packages/autogluon/core/models/abstract/abstract_model.py#line=924), in fit
    out = self._fit(**kwargs)
          ^^^^^^^^^^^^^^^^^^^
  File "[C:\Users\celes\anaconda3\Lib\site-packages\autogluon\tabular\models\catboost\catboost_model.py", line 243](file:///C:/Users/celes/anaconda3/Lib/site-packages/autogluon/tabular/models/catboost/catboost_model.py#line=242), in _fit
    self.model.fit(X, **fit_final_kwargs)
  File "[C:\Users\celes\anaconda3\Lib\site-packages\catboost\core.py", line 5245](file:///C:/Users/celes/anaconda3/Lib/site-packages/catboost/core.py#line=5244), in fit
    self._fit(X, y, cat_features, text_features, embedding_features, None, graph, sample_weight, None, None, None, None, baseline, use_best_model,
  File "[C:\Users\celes\anaconda3\Lib\site-packages\catboost\core.py", line 2410](file:///C:/Users/celes/anaconda3/Lib/site-packages/catboost/core.py#line=2409), in _fit
    self._train(
  File "[C:\Users\celes\anaconda3\Lib\site-packages\catboost\core.py", line 1790](file:///C:/Users/celes/anaconda3/Lib/site-packages/catboost/core.py#line=1789), in _train
    self._object._train(train_pool, test_pool, params, allow_clear_pool, init_model._object if init_model else None)
  File "_catboost.pyx", line 5017, in _catboost._CatBoost._train
  File "_catboost.pyx", line 5066, in _catboost._CatBoost._train
_catboost.CatBoostError: bad allocation
```

**Installed Versions**

<details>

```python
INSTALLED VERSIONS
------------------
date                : 2024-12-14
time                : 17:56:22.467895
python              : 3.11.9.final.0
OS                  : Windows
OS-release          : 10
Version             : 10.0.22631
machine             : AMD64
processor           : AMD64 Family 23 Model 96 Stepping 1, AuthenticAMD
num_cores           : 16
cpu_ram_mb          : 32175.171875
cuda version        : None
num_gpus            : 1
gpu_ram_mb          : [3883]
avail_disk_size_mb  : None

autogluon           : None
autogluon.common    : 1.2
autogluon.core      : 1.2
autogluon.features  : 1.2
autogluon.tabular   : 1.2
boto3               : 1.35.55
catboost            : None
einops              : 0.8.0
fastai              : 2.7.18
huggingface-hub     : 0.26.5
hyperopt            : 0.2.7
imodels             : 2.0.0
lightgbm            : 4.5.0.99
matplotlib          : 3.10.0rc1
networkx            : 3.4.2
numpy               : 1.26.4
onnx                : 1.17.0
onnxruntime         : 1.20.1
onnxruntime-gpu     : 1.20.1
pandas              : 2.2.3
psutil              : 6.1.0
pyarrow             : 18.1.0
ray                 : 2.40.0
requests            : 2.32.3
scikit-learn        : 1.5.2
scikit-learn-intelex: 2025.0.0
scipy               : 1.14.1
skl2onnx            : 1.17.0
spacy               : 3.8.2
tabpfn              : 0.1.10
torch               : 2.6.0.dev20241214+cu118
tqdm                : 4.67.1
vowpalwabbit        : None
xgboost             : 3.0.0.dev0
```

</details>

**Comment by andrey-khropov** [comment]
"bad allocation" error means that memory allocation failed. Most likely you ran out of memory with no memory swapping enabled (although I wouldn't recommend turning on memory swapping anyway in this case because working with swapped out data would be very slow).

**Comment by celestinoxp** [comment]
@andrey-khropov 
I created reproducible code. I bought as much memory as possible for my notebook, now it has 32GB of RAM. Only catboost cannot train the model because it needs more RAM.
1 - Shouldn't it show how much memory you need instead of "bad allocation"? Like axample: "trying allocate X GBytes but you have x GBytes available"...
2 - Apparently this is a catboost problem and not autogluon... Should I open an issue on catboost's github?

Reproduzible code for laptop with 32gb ram:

```python
import pandas as pd
import numpy as np
from autogluon.tabular import TabularPredictor

# dataset 11.000 columns and 1.000 rows
num_rows = 3000
num_columns = 12000
data = pd.DataFrame(np.random.rand(num_rows, num_columns), columns=[f'col_{i}' for i in range(num_columns)])

# create column
data['target'] = np.random.choice([0, 1, 2, 3, 4], size=num_rows)

# convert data type if it's object to category
#data['target'] = data['target'].astype('category')

# define the target column name
target_column = 'target'

predictor = TabularPredictor(label=target_column, path='autogluon_catboost_issue_4738')
predictor.fit(
    train_data=data,
    presets='experimental_quality',
    hyperparameters={'CAT': {}},  # only catBoost to investigate
    time_limit=2000
)
```

**Comment by andrey-khropov** [comment]
@celestinoxp What CatBoost version is used? 

In 'Installed versions' above it says `catboost            : None` for some reason.

**Comment by celestinoxp** [comment]
@andrey-khropov the version I'm using is the latest "catboost-dev" version. Normally the names should remain and the version name changes, but catboost is different. It has 1.27 in the version and changes the name to catboost-dev... you should also pay attention to this, it should have the name "catboost" and the version "1.2.7-dev"

**Comment by Killer3048** [comment]
@celestinoxp 

### **Problem Overview**
The issue occurs when CatBoost in AutoGluon throws a `bad allocation` error due to insufficient memory while training on high-dimensional data (12,000+ features). This typically happens when the model tries to allocate more memory than available.

### **Solution**
Below are the steps to address the memory allocation issue, including reducing dimensionality, optimizing hyperparameters, and using alternative models where necessary.

### 1. **Use Stable CatBoost Version**
Switch from the development version to the latest stable release.

```bash
pip uninstall catboost
pip install catboost==1.2.7
```

### 2. **Reduce Feature Dimensionality**
Apply PCA to lower the number of features.

```python
from sklearn.decomposition import PCA

pca = PCA(n_components=1000, random_state=42)
features_reduced = pca.fit_transform(data.drop('target', axis=1))
data_pca = pd.DataFrame(features_reduced, columns=[f'pca_{i}' for i in range(1000)])
data_pca['target'] = data['target']
```

### 3. **Optimize CatBoost Hyperparameters**
Adjust settings to use less memory.

```python
hyperparameters = {
    'CAT': {
        'depth': 6,
        'subsample': 0.8,
        'colsample_bytree': 0.8,
        'early_stopping_rounds': 50,
        'task_type': 'CPU'  # Use CPU instead of GPU
    }
}
```

### 4. **Modify Fit Call**
Update your training to incorporate changes.

```python
predictor = TabularPredictor(label='target', path='modelos/linha7')

predictor.fit(
    train_data=data_pca,
    presets='experimental_quality',
    hyperparameters=hyperparameters,
    num_gpus=0,  # Disable GPU
    time_limit=2000
)
```

### 5. **Monitor Memory Usage**
Use Task Manager (Windows) or similar tools to keep an eye on RAM during training.

### 6. **Alternative: Switch to LightGBM**
If issues persist, try a different model.

```python
predictor.fit(
    train_data=data_pca,
    presets='best_quality',
    hyperparameters={'GBM': {}},
    time_limit=2000
)
```

**Comment by celestinoxp** [comment]
Downgraded cuda version from 12.1 to 11.8 and forgot downgrade cudnn files to correct version
